### ISSUE TITLE
Move downloads and likes to playlists 

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#10]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

If possible, moving downloads and likes from the songs section to the playlists section would make it easier and more efficient to access them.

### Why do you want this feature?

It looks better like this 
![Screenshot_20240323_004006](https://github.com/Malopieds/InnerTune/assets/80542861/b0fcbf6d-e0c5-48b4-a5c5-d377810540fd)

**Comment by Malopieds** [comment]
Yes that's an idea I like. I was thinking about merging all of songs, artists albums and playlists as Library, what do you think ?

**Comment by mostafaalagamy** [comment]
> Yes that's an idea I like. I was thinking about merging all of songs, artists albums and playlists as Library, what do you think ?

Exactly do this like the library section in original YT Music it will be awesome.
