### ISSUE TITLE
Gradient Background

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#100]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

lately yt music added that feature and it looks so cool, I wish if we can get it on innertune

![o12ztgw0421d1_1](https://github.com/Malopieds/InnerTune/assets/156727749/1af91aed-dba3-4148-8561-00cc480d0dee)
![p6a9bljum01d1_1](https://github.com/Malopieds/InnerTune/assets/156727749/56c8d6b5-da54-42ab-a417-fb3206adb08b)

### Why do you want this feature?

its pretty cool and its better than "Dynamic theme"

**Comment by Malopieds** [comment]
What about something like this?

White theme:
![image](https://github.com/Malopieds/InnerTune/assets/74783202/e755e5cb-0073-4455-8aad-516859a15154)

Dark theme:
![image](https://github.com/Malopieds/InnerTune/assets/74783202/cd32378a-66ea-42cc-8b0b-30c17713b0a4)


Ideally I'd like to change the color scheme, but it's not for now.

**Comment by Spaceshiprace** [comment]
its cool, anyway do what you think would fit more this was just my suggestion and also you can improve it later if its not for now.

**Comment by Username1-a** [comment]
Would be great if it was optional or if there was completely black background for Black Dark theme

**Comment by Malopieds** [comment]
I'm closing this with the final result being pushed, it will be the same in white theme or dark theme, it's optional of course.

![image](https://github.com/Malopieds/InnerTune/assets/74783202/4b17bfb4-f616-454c-a51d-3b5131a80e6d)
