### ISSUE TITLE
Plz add fluid gradient in player

### ISSUE THREAD

**Issue by Fxrrcrxdsccexxe** [Malopieds/InnerTune#101]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Plz add fluid gradient in player

### Why do you want this feature?

This feature looking so awesome👍 so please kindly add 

### Additional information

Plz add

**Comment by Malopieds** [comment]
You mean #100?

**Comment by Fxrrcrxdsccexxe** [comment]
Plz add fluid gradient like ri music player
