### ISSUE TITLE
On newest version built from source (28/05/2024) or in the debug version: songs in an album randomly disappear after playing other songs from the Album

### ISSUE THREAD

**Issue by EisregenHaha** [Malopieds/InnerTune#104]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go onto an Album (e.g Kids see Ghosts)
2. click on Track 3/4 (doesnt really matter)
3. see how the last track or sometimes a random one are just gone now, and now the Album is only 4/5 songs long instead of the original 7. 

### Expected behavior

It should show all songs in an album

### Actual behavior

well songs disappear

### Screenshots/Screen recordings

![Screenshot_20240528-004246](https://github.com/Malopieds/InnerTune/assets/98850034/e6b6beb5-47ce-4bf5-8348-d7a60ea4355f)
![Screenshot_20240528-004251](https://github.com/Malopieds/InnerTune/assets/98850034/0e83d46b-0d73-4c3b-93af-5298f00548a2)

### Logs

[log.txt](https://github.com/Malopieds/InnerTune/files/15462220/log.txt)

### InnerTune version

latest debug/latest source

### Android version

14

### Additional information

-

**Comment by EisregenHaha** [comment]
also thanks for this fork, the improvements are great

**Comment by EisregenHaha** [comment]
i backtracked versions and it seems to only happen after the commit which fixes #67, so the commit db3d8f9

**Comment by Malopieds** [comment]
Thank you for doing the research part, I really appreciate it! I'll look into it later today if I have time, but it's really weird.

**Comment by EisregenHaha** [comment]
> Thank you for doing the research part, I really appreciate it! I'll look into it later today if I have time, but it's really weird.

yeah sure no problem, i appreciate the work. i just reverted the commit for now and that fixed it

**Comment by Spaceshiprace** [comment]
btw this album is a trip fr

**Comment by EisregenHaha** [comment]
> btw this album is a trip fr

yeah, sadly kanye washed now 💔

**Comment by Spaceshiprace** [comment]
don't mind whatever he did if you like the music you like it, that has nothing to do with his music.

**Comment by EisregenHaha** [comment]
> don't mind whatever he did if you like the music you like it, that has nothing to do with his music.

not true, he spreads his messages in his new music. you cant seperate art from artist here. also thats not even what i meant, the new music just sucks altogether, vultures was straight ass lmfao

**Comment by Spaceshiprace** [comment]
I didn't even mention vultures.. what I was saying that if you like the music whatever the artist is or whatever he's trying to spread through it if the music is good then its good you can't deny that.

**Comment by EisregenHaha** [comment]
> I didn't even mention vultures.. what I was saying that if you like the music whatever the artist is or whatever he's trying to spread through it if the music is good then its good you can't deny that.

i can and will deny that, there is no good music if the message is shit

**Comment by Spaceshiprace** [comment]
if you deny it, you're simply lying to yourself.

**Comment by EisregenHaha** [comment]
> if you deny it, you're simply lying to yourself.

sounds more like you are delusional. music is a form of art, if the message behind it is bad it itself is too

**Comment by Malopieds** [comment]
This is certainly not the place do have this debate. I will be removing those comments.

**Comment by EisregenHaha** [comment]
> This is certainly not the place do have this debate. I will be removing those comments.

literally 1984

**Comment by Spaceshiprace** [comment]
ay @Malopieds are u workin' on a new release any time soon..

**Comment by Malopieds** [comment]
> ay @Malopieds are u workin' on a new release any time soon..

Yep I will maybe do one over the weekend.

This is now fixed, I reverted from the commit. Seems like the other issue is no longer one anyway...
