### ISSUE TITLE
Ugly Icons for buttons in the media player

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#105]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

please fix (change) those icons they're so ugly

### Why do you want this feature?

they're big and ugly

### Additional information

and also please @Malopieds can u release an official release cuz dat debug version is so buggy for me and i don't know why

**Comment by freezedudu** [comment]
it's an hyper os issue, dev can't do anything about it

**Comment by Spaceshiprace** [comment]
> it's an hyper os issue, dev can't do anything about it

ok then.
