### ISSUE TITLE
Innertune Breaks Scrobbles

### ISSUE THREAD

**Issue by kaneryu** [Malopieds/InnerTune#109]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Find any song with multilingual titles

### Expected behavior

Only one language shows in the title

### Actual behavior

Both languages show, separated by the dash

### Screenshots/Screen recordings

![Screenshot_20240601-100353](https://github.com/Malopieds/InnerTune/assets/72762358/43a79d35-d783-4f97-a6ec-77485da27149)

### Logs

_y_

### InnerTune version

0.5.6

### Android version

Android 11

### Additional information

Only one language should show. If both languages show, it completely breaks scrobbling, because every scrobbling website only has one title, which causes incorrect scribbling. This was not an issue in the old version of InnerTune (Zion's ver) which means it was added on purpose. Please remove this so I can  scrobbler from innertune again. (also  preferably allow the user to pick either the original language or the translated one.

**Comment by Malopieds** [comment]
Hi, this is not InnerTune fault, it's Youtube Music's name, you can check the title from the original youtube music website. I can't (and won't) do anything for this. All you can do is edit you scrobbles. I know that panoScrobbler allows you to do that.
