### ISSUE TITLE
Open the song link via InnerTune. The song will be played directly 

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#11]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_20240323_020609](https://github.com/Malopieds/InnerTune/assets/80542861/fca0d6f7-f2c0-4ba0-ac6c-2dddcc15e004)
When opening a song link and being redirected to InnerTune, the song does not play directly, but this menu opens.

### Why do you want this feature?

The song must be played directly.

**Comment by Malopieds** [comment]
Yep I think the action when you click a link like `/watch?v=` should be immediate. I still like the idea of giving a choice to the user though. Maybe a choice of the action in the settings can help with this?

**Comment by mostafaalagamy** [comment]
Yes, but there is no option to play the song in the menu, and I have to press the radio button for it to work. I think the song should play directly, with options in the settings to disable this and provide alternatives.

**Comment by Malopieds** [comment]
This will be on the next release.
I'll see if I implement a choice later on.
