### ISSUE TITLE
Make long press possible in all sections for songs

### ISSUE THREAD

**Issue by BluePixel4k** [Malopieds/InnerTune#110]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It is currently not possible to long press a song in all sections:

https://github.com/Malopieds/InnerTune/assets/77979781/2e275c2a-a45f-4145-936a-a6d3fe2d2b4f

It would be nice if this were possible in all sections.

### Why do you want this feature?

It would be more generic.

**Comment by ReallyYug** [comment]
Bump fr

**Comment by BluePixel4k** [comment]
I figured out, that this issue is a duplicate of #51 and was implemented in the meantime.
