### ISSUE TITLE
Latest build

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#112]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Not a feature request but I wondered where can I find the latest build is there a page where this can be accessed while 0.57 is being worked on?

### Why do you want this feature?

N/a

**Comment by Malopieds** [comment]
You can either try the debug app version, every push (the green tick) then summary and at the end of the page there will be an app file, that's the debug version (a bit laggy). Otherwise I just published a new release !
