### ISSUE TITLE
Delete Playlist 

### ISSUE THREAD

**Issue by feelsavvy** [Malopieds/InnerTune#113]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

• Currently, InnerTune lacks the ability to delete playlists. This poses a problem for users who wish to remove unwanted playlists from their library.

### Why do you want this feature?

This feature needs to be added because there are a few playlists I want to delete, but I can't and the playlist imported from YouTube Music.

**Comment by Malopieds** [comment]
You can long press to have a menu. From there you can delete the playlist.

**Comment by feelsavvy** [comment]
Ok thank you
