### ISSUE TITLE
Multiple select songs to playlist

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#12]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Innertune 0.44 and earlier had the abily to select multiple songs and options appeared to add to playlist, queue and download (√see screenshot)

![Screenshot_2024-03-23-19-17-51-02_f4703f2d42345ac28c56f11a6100c500.jpg](https://github.com/Malopieds/InnerTune/assets/81394097/7a4e50ca-28f7-441e-9eb3-9aee99583795)

### Why do you want this feature?

You bulk add to playlist, queue and download songs. At the moment it's very slow having to do this one by one. Please reintroduce

**Comment by Malopieds** [comment]
The issue I have with this is the fact that I was thinking about binding long press to open the menu. I don't know what else could lead to a multiple selection.

**Comment by owenconnorz** [comment]
What about an icon at the top of  the page to use multiple select

**Comment by Malopieds** [comment]
> What about an icon at the top of the page to use multiple select

That could be an idea, where would you see it ?
Another way I was thinking of was to implement a "swipe to actions" that would either launch the menu or do a quick action (such as we see in spotify). That would leave the long press for multiple selection. The downside of swipe to actions is that it can be triggered too easily in my opinion.

**Comment by owencz1998** [comment]
That's a better idea mate I think you have it spot on there 👍

**Comment by owencz1998** [comment]
Maybe add a delay so it's harder to trigger maybe swipe and hold for like a second or 2 so it can't be triggered to easy

**Comment by owenconnorz** [comment]
That's a better idea mate I think you have it spot on there 👍 
Maybe add a delay so it's harder to trigger maybe swipe and hold for like a second or 2 so it can't be triggered to easy

**Comment by Lorestan00** [comment]
Swipe to action and long press for multi select seems a great solution.

**Comment by Malopieds** [comment]
This will be implemented using the button idea. It will only be present on playlists and albums.

Edit:
Maybe also present on 'Songs' chip of the library

**Comment by Lorestan00** [comment]
Sounds great. Looking forward to trying it out

**Comment by Malopieds** [comment]
Should be done by now. You can try it in the latest debug version. If you have any inquiries, please let me know here !

**Comment by Lorestan00** [comment]
That's great. How do I access the debug version?

**Comment by mostafaalagamy** [comment]
> That's great. How do I access the debug version?

This [Link](https://github.com/Malopieds/InnerTune/actions/runs/8635444896/artifacts/1402425044)

**Comment by mostafaalagamy** [comment]
> Should be done by now. You can try it in the latest debug version. If you have any inquiries, please let me know here !

It is possible to add delete/remove option 

![Screenshot_2024-04-10-21-14-59-20_5399807b941effa97489f80037469fbd.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/66f58a1d-cbbc-4b9b-9d5d-74f30ef81fb1)

**Comment by Lorestan00** [comment]
Thanks! Great work! Game changer

Some feedback on this version:-

'Add to library' isn't available in the multi select options. This would be helpful. 

'Add to library' for individual song appears an option but doesn't do anything. Songs aren't added to the library

 my playlists, songs downloaded, library etc don't appear I'm assuming as  it's a debug version and a separate installation.  The released version however will retain playlists, downloaded songs etc from the stable version?

**Comment by Malopieds** [comment]
> 'Add to library' isn't available in the multi select options. This would be helpful.

The library is entirely revisited. The release note will talk about it too. To make it simple, previously it worked as, if you liked a song, the artists and album linked to the song will be also added to the library. It does not make sens as of now for me. If you want to have an artist in the artist section you have to like the artist. I maybe can work on bulk like if that what's you're looking for.

> 'Add to library' for individual song appears an option but doesn't do anything. Songs aren't added to the library

This will therefore disappear.

> my playlists, songs downloaded, library etc don't appear I'm assuming as it's a debug version and a separate installation. The released version however will retain playlists, downloaded songs etc from the stable version?

Of course, those 2 apps are 2 different packages.

> It is possible to add delete/remove option

Yes should be. I'll look into it

**Comment by mostafaalagamy** [comment]
The multiple select icon layout looks really weird in the albums! Can you move it upwards or to the menu?


![Screenshot_2024-04-11-17-02-49-93_5399807b941effa97489f80037469fbd.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/bba1a9b9-47e8-41f7-9796-fa53a3aedb0b)

**Comment by Lorestan00** [comment]
> > 'Add to library' isn't available in the multi select options. This would be helpful.
> 
> The library is entirely revisited. The release note will talk about it too. To make it simple, previously it worked as, if you liked a song, the artists and album linked to the song will be also added to the library. It does not make sens as of now for me. If you want to have an artist in the artist section you have to like the artist. I maybe can work on bulk like if that what's you're looking for.

> okay that makes sense. Yep a way to bulk like songs would be great

> > 'Add to library' for individual song appears an option but doesn't do anything. Songs aren't added to the library
> 
> This will therefore disappear.
> 
> > my playlists, songs downloaded, library etc don't appear I'm assuming as it's a debug version and a separate installation. The released version however will retain playlists, downloaded songs etc from the stable version?
> 
> Of course, those 2 apps are 2 different packages.
> 
> > It is possible to add delete/remove option
> 
> Yes should be. I'll look into it

**Comment by Lorestan00** [comment]
> > 'Add to library' isn't available in the multi select options. This would be helpful.
> 
> The library is entirely revisited. The release note will talk about it too. To make it simple, previously it worked as, if you liked a song, the artists and album linked to the song will be also added to the library. It does not make sens as of now for me. If you want to have an artist in the artist section you have to like the artist. I maybe can work on bulk like if that what's you're looking for.

> Okay makes sense. Would be great to have an option to bulk like songs. 

> > 'Add to library' for individual song appears an option but doesn't do anything. Songs aren't added to the library
> 
> This will therefore disappear.
> 
> > my playlists, songs downloaded, library etc don't appear I'm assuming as it's a debug version and a separate installation. The released version however will retain playlists, downloaded songs etc from the stable version?
> 
> Of course, those 2 apps are 2 different packages.
> 
> > It is possible to add delete/remove option
> 
> Yes should be. I'll look into it

**Comment by Lorestan00** [comment]
> > 'Add to library' isn't available in the multi select options. This would be helpful.
> 
> The library is entirely revisited. The release note will talk about it too. To make it simple, previously it worked as, if you liked a song, the artists and album linked to the song will be also added to the library. It does not make sens as of now for me. If you want to have an artist in the artist section you have to like the artist. I maybe can work on bulk like if that what's you're looking for.
> 
> Okay makes sense. Would be great to have an option to bulk like songs. 
```

> > 'Add to library' for individual song appears an option but doesn't do anything. Songs aren't added to the library
> 
> This will therefore disappear.
> 
> > my playlists, songs downloaded, library etc don't appear I'm assuming as it's a debug version and a separate installation. The released version however will retain playlists, downloaded songs etc from the stable version?
> 
> Of course, those 2 apps are 2 different packages.
> 
> > It is possible to add delete/remove option
> 
> Yes should be. I'll look into it

**Comment by Lorestan00** [comment]
Add to library' isn't available in the multi select options. This would be helpful.

The library is entirely revisited. The release note will talk about it too. To make it simple, previously it worked as, if you liked a song, the artists and album linked to the song will be also added to the library. It does not make sens as of now for me. If you want to have an artist in the artist section you have to like the artist. I maybe can work on bulk like if that what's you're looking for.

> okay makes sense. Liking songs in bulk would be great

**Comment by Malopieds** [comment]
The two issues should be fixed now. Tell me if there is anything else, otherwise I'll close this.

**Comment by owenconnorz** [comment]
@Malopieds what about delete song from playlist and not just delete download

**Comment by Lorestan00** [comment]
> The two issues should be fixed now. Tell me if there is anything else, otherwise I'll close this.

That's great. Where can I download the latest debut version?

**Comment by Malopieds** [comment]
> @Malopieds what about delete song from playlist and not just delete download

You're right, I forgot about that !

> That's great. Where can I download the latest debut version?

[here](https://github.com/Malopieds/InnerTune/actions/runs/8719835592/artifacts/1421442786)

**Comment by Lorestan00** [comment]
The multi select as well as songs and albums can it also appear in playlists such as ones auto generated by YouTube which appear on the home and explore tabs. Quite often you won't to like or add some of the songs to a playlist but not all
