### ISSUE TITLE
Can't install latest version

### ISSUE THREAD

**Issue by Deemitry88** [Malopieds/InnerTune#120]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Have version 0.5.3 installed
2. Try to install latest version
3. Can't install
![Screenshot_20240622_212747_Package installer](https://github.com/Malopieds/InnerTune/assets/91915462/dd7a9920-1e4e-45e8-8730-69d599ac42cc)

### Expected behavior

It should install

### Actual behavior

It doesn't 

### Logs

.

### InnerTune version

0.5.3 to 0.5.7-rc2

### Android version

Android 12

**Comment by Malopieds** [comment]
I'm guessing you're coming from the main repo's app? If so, you just can't install this app in top of the original. They are signed apps (signed with a secret key) so my app isn't signed with the same key as the original so you CAN'T install it on top. All you can do is backup and uninstall the app and restore it in the newly installed app. There might be some other way with cloning apps.

**Comment by Deemitry88** [comment]
Oh wow I didn't see at all you were a fork, well I did what you did, and your fork is way better, it could be cool if you replaced the lyrics button by the shuffle button, like the others platform, thanks for your help !

**Comment by Malopieds** [comment]
> it could be cool if you replaced the lyrics button by the shuffle button

It's been a long debate and tbh and don't know what to choose

**Comment by Deemitry88** [comment]
well maybe add an option so we can choose
