### ISSUE TITLE
Album's songs doesn't load

### ISSUE THREAD

**Issue by Francis-Carvalho** [Malopieds/InnerTune#123]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Click on search bar, and search for some album that you like, for example "Etazhi". 
Click in the album icon, and it will load forever and never show the album's songs.

### Expected behavior

The app should show the album's songs 

### Actual behavior

The app loads forever and doesn't show the songs
![Screenshot_20240623-101506](https://github.com/Malopieds/InnerTune/assets/104478034/118dded0-d7f8-4c92-91ea-283a494ee803)

### Logs

Without logs

### InnerTune version

0.5.6

### Android version

Android 10

**Comment by ReallyYug** [comment]
@Francis-Carvalho it's fixed in the latest version, use app-fix-login.apk of the latest release https://github.com/Malopieds/InnerTune/releases/download/v0.5.7-rc2/app-fix-login.apk

**Comment by Francis-Carvalho** [comment]
It works! Thanks sir

**Comment by ReallyYug** [comment]
Np :)
