### ISSUE TITLE
History changes duration

### ISSUE THREAD

**Issue by Revita787** [Malopieds/InnerTune#124]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Listened to a dozen of songs
2. Still only one song is showing in my history

### Expected behavior

Should've shown all the songs I've listened to till now

### Actual behavior

It shows only one song (earlier when I tried with app.apk, I got no songs)

### Screenshots/Screen recordings

![Screenshot_2024-06-23-21-11-16-95_f4703f2d42345ac28c56f11a6100c500](https://github.com/Malopieds/InnerTune/assets/173621634/9c5da1bd-f7e6-42d7-a27b-ff647f62cd7e)

### Logs

No logs

### InnerTune version

V0.5.7 rc2

### Android version

Android 14

**Comment by Malopieds** [comment]
Works fine for me. You have to listen to it to a certain time for it to count (I think it's 30 but I'm sure that 1 minute is enough). Have you done anything particular while listening to the music ?

**Comment by Revita787** [comment]
> Works fine for me. You have to listen to it to a certain time for it to count (I think it's 30 but I'm sure that 1 minute is enough). Have you done anything particular while listening to the music ?

It seems like you were right
I usually listen to the main part of the song and then end up skipping it so it's less than 30. Thanks for replying, could you please make it 15 tho? Just a suggestion/request


I will close this issue when you feel right 👍

**Comment by Malopieds** [comment]
> could you please make it 15 tho? Just a suggestion/request

I could maybe let the user choose the time, I'll see in the future releases.
