### ISSUE TITLE
Add a home button to go to home page quickly after a song search

### ISSUE THREAD

**Issue by Richard38907** [Malopieds/InnerTune#125]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I use an other variant of innertune who has the albums not loading bug. The feature I want was implemented in this variant.
![Screenshot_20240623-175215](https://github.com/Malopieds/InnerTune/assets/148692265/ef4ecf6d-64b0-45df-8822-c7f65b0614bc)

### Why do you want this feature?

To avoid tapping the back button as many times as songs searches

**Comment by mostafaalagamy** [comment]
You can do it by long click in back arrow to go to home

**Comment by Richard38907** [comment]
Nice, thank you for your answer🙂.

**Comment by Malopieds** [comment]
> You can do it by long click in back arrow to go to home

Exactly, thanks.

Closing since solved.
