### ISSUE TITLE
Annoying issue

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#126]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

check the video recording below

### Expected behavior

the video recording says it all

### Actual behavior

the video recording says it all

### Logs

idk

### InnerTune version

0.5.7-rc2

### Android version

Android 12

**Comment by Malopieds** [comment]
Weird thing, I can't even unlock to change the order. I'll investigate maybe tomorrow.

**Comment by Spaceshiprace** [comment]
okey thanks.

**Comment by Spaceshiprace** [comment]
@Malopieds Hi, So I see that you closed the issue as fixed but I'm just commenting to tell u that i tried the latest debug version and its still there not fixed and also #73 is still not fixed even if u closed that issue too, So please look into them more because it seems that these issues still not fixed.

**Comment by Malopieds** [comment]
> So I see that you closed the issue as fixed but I'm just commenting to tell u that i tried the latest debug version and its still there

Yep, your playlist is basically ruined, you need to create it again, that should solve the issue. In addition make sure you're using the right version, I have changed the package name so, there are 2 innertune in your phone now. please do check because everything works right for me, even #73  

Edit:
To do so, you can just select all of them and add them in another playlist

**Comment by Spaceshiprace** [comment]
> > So I see that you closed the issue as fixed but I'm just commenting to tell u that i tried the latest debug version and its still there
> 
> Yep, your playlist is basically ruined, you need to create it again, that should solve the issue. In addition make sure you're using the right version, I have changed the package name so, there are 2 innertune in your phone now. please do check because everything works right for me, even #73
> 
> Edit: To do so, you can just select all of them and add them in another playlist

I'm using the latest debug version so everything should be fixed right? but the issues still appear.. regarding the playlist so everytime its ruined I have to create another cuz i thought that the issue is fixed..?

**Comment by Malopieds** [comment]
> regarding the playlist so everytime the its ruined I have to create another cuz i thought that the issue is fixed..?

You only to do this once. And after it should be back to normal. Just do as the edit says and tell me.

**Comment by Spaceshiprace** [comment]
> You only to do this once. And after it should be back to normal. Just do as the edit says and tell me.

Okey.

**Comment by Spaceshiprace** [comment]
@Malopieds Hi so I'm back to this issue because I'm facing it again on the latest version, and also the only way to fix it is to clear the data of the app and lose all your playlists cuz if you did the restore the bug will appear again so please can u fix it or reopen the issue

**Comment by Malopieds** [comment]
I don't have enough information. What was the bug? Where is the video? How does it happens, etc...

**Comment by Spaceshiprace** [comment]
@Malopieds 
its that unlock thing to change songs order in a playlist ?

**Comment by Spaceshiprace** [comment]
@Malopieds still having this bug even on the latest version, am i the only one, is it working well for you ?

**Comment by Malopieds** [comment]
> @Malopieds still having this bug even on the latest version, am i the only one, is it working well for you ?

Are you sure you are using the pre release? It works fine for me, the songs with no time, I can see them fetching automatically

**Comment by Spaceshiprace** [comment]
> 
> Are you sure you are using the pre release? It works fine for me, the songs with no time, I can see them fetching automatically

I'm not talking about the songs with no runtime, I'm here for the songs order cuz its not working for me and yes I'm using the pre release.
