### ISSUE TITLE
IzzyOnDroid repo

### ISSUE THREAD

**Issue by Malopieds** [Malopieds/InnerTune#128]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

As seen [here](https://github.com/z-huang/InnerTune/issues/1295) it would be nice to have this application on IzzyOnDroid's repo.
@IzzySoft since this is a fork, and I kept the same package name, it will be conflicting with the original one, right? If I understand correctly the apk you would be providing would be the one on the github release? So people won't be able to upgrade from the original to this fork since those are signed differently.
Tell me what you think.

### Why do you want this feature?

More people could see the app.

**Comment by IzzySoft** [comment]
You'll need at least a different `applicationId`/`packageName`, else your APKs would overwrite the originals and vice versa. So:

> it will be conflicting with the original one, right?

Yes, that.the apk you would be providing would be the one on the github release? 

> the apk you would be providing would be the one on the github release? 

True. And another question is: What is different with your fork? Does it add something the original does not have? If so, no way to integrate it there?

**Comment by Malopieds** [comment]
> You'll need at least a different applicationId/packageName, else your APKs would overwrite the originals and vice versa.

Okay, that's what I thought.

> What is different with your fork? Does it add something the original does not have? If so, no way to integrate it there?

The original dev has not been recently updating,  so even the merge request are not treated. And yesterday YouTube changed their API so the original InnerTune won't work on playlist and albums, that's why people wanted this fork to be on Izzy. It has some fix of other bugs and some revamp of screen mainly.

**Comment by IzzySoft** [comment]
Usually there are two ways from there. If the original dev(s) no longer want to maintain their project, they could transfer it to another maintainer (e.g. you) – ideally passing the new maintainer(s) the signing keys as well; in this case the original packageName can be kept and, provided the signing keys were passed, too, all is transparent for those using the app.

If this option does not exist, a fork (like yours) would be needed. But that must go with its own packageName then – also to make clear it's a fork and not a direct continuation of the original app. Given the explanations you provided, it would be welcome at IzzyOnDroid the same way as the original is.

**Comment by Malopieds** [comment]
> If the original dev(s) no longer want to maintain their project

I don't think that's the plan here, they are mainly focused on the their study.

> If this option does not exist, a fork (like yours) would be needed. But that must go with its own packageName

Ok then. The next (stable) release will have its own package name.

> also to make clear it's a fork and not a direct continuation of the original app

Duly noted.

I'll ping you again in this issue when it's all done if that's good for you.
Thanks again for your time and your implication!

**Comment by IzzySoft** [comment]
> they are mainly focused on the their study.

Yeah, sometimes real-live intervenes with our hobbies… But then maybe there's the chance your changes might be "upstreamed" one day – or both projects "stream to each other" at least. Thanks for your engagement there!

> I'll ping you again in this issue when it's all done if that's good for you.

Yes please!

**Comment by Malopieds** [comment]
Hey @IzzySoft I just pushed a stable release! Take your time to analyze everything you need, please ask if you have any questions !

**Comment by IzzySoft** [comment]
Scanner just complains about:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

which can easily be avoided by a minor adjustment to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Would be great if you'd consider that for the next release. Apart from that, all looks fine – so be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app's new home, where [it will show up](https://apt.izzysoft.de/packages/com.malopieds.innertune) with the next sync!

Wait, oof, what's that?

    com.malopieds.innertune_24.apk|4 malware alerts|20 libs

Can you [please take a look](https://www.virustotal.com/gui/file/1fe3a2ce2edeb899dac979bb77c76b2aa565584dfa9694ddfe05d34982488612/detection/f-1fe3a2ce2edeb899dac979bb77c76b2aa565584dfa9694ddfe05d34982488612-1720354506)?

**Comment by Malopieds** [comment]
Thank you for answering :)

> Would be great if you'd consider that for the next release

Will be done !

> Wait, oof, what's that?
```com.malopieds.innertune_24.apk|4 malware alerts|20 libs```
Can you [please take a look](https://www.virustotal.com/gui/file/1fe3a2ce2edeb899dac979bb77c76b2aa565584dfa9694ddfe05d34982488612/detection/f-1fe3a2ce2edeb899dac979bb77c76b2aa565584dfa9694ddfe05d34982488612-1720354506)?

I've already sent a false positive to Avast, and seems that they removed it from their database. In a previous issue raising this, I sent two file to test on virustotal:
> [This](https://www.virustotal.com/gui/file/a4b7f3762f6130e6b9026c10db8130c69cb658f388e9c0a36fa2a0d7e314ca81?nocache=1) is latest debug build
And [this](https://www.virustotal.com/gui/file/87fc3ceece376986c9cf76d178de25c9a1fd12c88292159982a2858c95241e1e?nocache=1) is a build I just made.

I don't know why it's bringing this, and seems like it's not always here... If you have any idea where this could be from I'll take any hint, I didn't had a lot from the original, maybe just more api request (on the home screen mainly)

**Comment by IzzySoft** [comment]
> Will be done !

Great, thanks!

> I've already sent a false positive to Avast, and seems that they removed it from their database.

Ah, OK. Last scan of the file was 2 hours ago, still all 4 engines there (oops, one down another jumped in it seems). Might take a little I guess – but should be gone with the next release then.

> If you have any idea where this could be from

Unfortunately not… Should it be gone for the current release (or the counter having decreased) due to another scan, please give me a ping so I trigger an update of the database here.

**Comment by Malopieds** [comment]
Hey @IzzySoft, 
I just pushed a new release, with the blobs!

About the scan, yours still has one I don't know why, I haven't done anything...

I [sent the last release](https://www.virustotal.com/gui/file/156acc5bd4e8d96bdda595e8de77c9d6e90e87cc9a030444bd93872c0c26812e?nocache=1) to virsustotal, and 0 viruses! I let you check on your side, and if everything is good I'll close this issue.

Thank you :)

**Comment by IzzySoft** [comment]
> I just pushed a new release, with the blobs!

Confirmed:

```
$ iod repo get com.malopieds.innertune
com.malopieds.innertune: looking for 'https://api.github.com/repos/Malopieds/InnerTune/releases'
com.malopieds.innertune: checking tag 'v0.5.8'
com.malopieds.innertune: lastRelNo set to '0.5.8', checking for files
com.malopieds.innertune: Upstream file date (2024-07-11 20:00) is newer than ours (2024-07-08 08:42).
com.malopieds.innertune: returning ['0.5.8','https://github.com/Malopieds/InnerTune/releases/download/v0.5.8/app.apk',1720720807]
com.malopieds.innertune: 0.5.7/0.5.8, https://github.com/Malopieds/InnerTune/releases: https://github.com/Malopieds/InnerTune/releases/download/v0.5.8/app.apk
- Grabbing update for com.malopieds.innertune: OK
- Checking 'repo/com.malopieds.innertune_25.apk' for libraries and malware …
- Checking the app's AndroidManifest.xml …
com.malopieds.innertune: check if repo contains FUNDING.yml
com.malopieds.innertune: looking for 'https://api.github.com/repos/Malopieds/InnerTune/contents/.github'
com.malopieds.innertune: FUNDING.yml already up-to-date.
com.malopieds.innertune: calling 'getFastlaneMeta(github,[host:github.com,owner:Malopieds,repo:InnerTune,path:/fastlane/metadata/android])'
...
```

> About the scan, yours still has one I don't know why, I haven't done anything...

I've triggered a rescan, and indeed they should be gone now. "Infection report" (for the full repo) returns "clean" – so nothing there with more than 2 hits ("false positive threshold"). So I'd say all good now! New release will be pushed with the next sync as usual, but is already on staging now.

**Comment by Malopieds** [comment]
Perfect, thank you!
