### ISSUE TITLE
"My Top x"-Playlist 

### ISSUE THREAD

**Issue by siggi1984** [Malopieds/InnerTune#13]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The "My Top x" playlist is an automatic playlist that is created based on listening behavior (the number of songs can be freely selected in the settings). I saw this on a ViMusic fork and I think it's really cool.
Maybe you can take a look at it and, if you like, implement it.

https://github.com/25huizengek1/ViTune

### Why do you want this feature?

![307603617-f1b433e1-63b5-4bc9-a4ce-0cba09cb01a9](https://github.com/Malopieds/InnerTune/assets/103368536/e1dfed71-ed11-4180-80ea-ba9ac07adc1c)

**Comment by Malopieds** [comment]
Yes, it can be a cool implementation. I just don't know if it will belong in the playlist section or in the home screen.

**Comment by siggi1984** [comment]
> Yes, it can be a cool implementation. I just don't know if it will belong in the playlist section or in the home screen.

At ViTune it is in the playlist area but there is also a cool idea in the home screen, so you would always have quick access to your playlist with the most played songs within 24 hours, 1 week, 1 month, 6 months, total period.

**Comment by mostafaalagamy** [comment]
> Yes, it can be a cool implementation. I just don't know if it will belong in the playlist section or in the home screen.

I have a suggestion, after removing songs, artists, and albums from the navigation bar and adding the library, I suggest adding a page called Explore containing New album, Mood and Genres, My Top x playlist, and trending, and making the navigation bar consist of 3 or 4 items.

**Comment by siggi1984** [comment]
> > Yes, it can be a cool implementation. I just don't know if it will belong in the playlist section or in the home screen.
> 
> I have a suggestion, after removing songs, artists, and albums from the navigation bar and adding the library, I suggest adding a page called Explore containing New album, Mood and Genres, My Top x playlist, and trending, and making the navigation bar consist of 3 or 4 items.

Yes, that sounds good, I'm looking forward to it.

**Comment by Malopieds** [comment]
> I have a suggestion, after removing songs, artists, and albums from the navigation bar and adding the library, I suggest adding a page called Explore containing New album, Mood and Genres, My Top x playlist, and trending, and making the navigation bar consist of 3 or 4 items.

Yes, it was the main idea between refactoring everything into "Library". But this will take some time. The code for Explore page is actually already implemented, but I first need to put everything into one tab.

**Comment by Malopieds** [comment]
There is now all playlist like "Offline", "Liked" and "My Top -x", you can change the number of songs to be displayed in the settings -> content.
I will leave this issue open for now, if you find any bugs or have any idea how to make it better, share it here !

**Comment by Malopieds** [comment]
Closing it since it's now implemented.
