### ISSUE TITLE
Change the shuffle button in queue

### ISSUE THREAD

**Issue by ReallyYug** [Malopieds/InnerTune#130]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

So as you know there is a shuffle button when you have multiple songs playing, so when you press that button it does shuffle but if you press it again it comes back to original form so it's one time use only cuz the shuffle is the same if you press it again, so instead just make it a whole shuffle button so it puts the currently playing song on top of the queue and then shuffle all the other songs in queue differently everytime the person clicks that button

### Why do you want this feature?

Shuffle is useful. That's it lmao

**Comment by Malopieds** [comment]
There already is a shuffle button, it's in the queue bottom left! Idk if you wanted something more out of it?

**Comment by ReallyYug** [comment]
> There already is a shuffle button, it's in the queue bottom left! Idk if you wanted something more out of it?

Well it doesnt work as it should, i explain more in feature description, read that

**Comment by wglee99** [comment]
This is a longstanding feature/bug (depends how you see it) from the original app. I believe the creator of the original InnerTune intended for it to be a functionality where you could always return to the original song order. I tested this out, and I found that if I press the shuffle button once, songs are shuffled. Press it again, songs return to the original order. But if I press the shuffle button once again, the songs are shuffled again, but in an order that is different from the first shuffle.

Perhaps this might be of some help to you if this feature is not changed. :)

**Comment by ReallyYug** [comment]
@wglee99 huh weird cuz it wasnt working like that before for me but now it does :/// tf, but thanks ig
