### ISSUE TITLE
Playlist items in the library are moving

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#131]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

.

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/335087ac-646f-4a4e-af38-c757e13f304f

### Logs

.

### InnerTune version

C2

### Android version

13

**Comment by Malopieds** [comment]
Yes, that's because of the fact that I was sorting elements by their dates (but they don't have any...) I would have to implement a way to update the date of the date of the playlist but that's kinda messy. I could still remove it or all put them at 0 for maybe a later implementation...

**Comment by mostafaalagamy** [comment]
> or all put them at 0 for maybe a later implementation...

Yes, that's fine until it's resolved later.
