### ISSUE TITLE
Release on official f-droid repository

### ISSUE THREAD

**Issue by ghost** [Malopieds/InnerTune#132]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add this app on official f-droid repository

### Why do you want this feature?

For more exposure and easier installation

### Additional information

https://f-droid.org/en/contribute/

**Comment by Malopieds** [comment]
Hi, this will be added to IzzyOnDroid, see #128.

**Comment by EmanuelLoos** [comment]
@Malopieds Would you allow the app to be added to F-Droid as well, though?

If it supports reproducible builds, F-Droid could redistribute your unmodified APK signed by you after checking reproducibility.

If the app is in the official F-Droid repository, it might reach a larger user base.
