### ISSUE TITLE
Download status/button does not display properly in bigger playlists

### ISSUE THREAD

**Issue by Irobrine** [Malopieds/InnerTune#133]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to a playlist with more than a certain number of songs (not sure how many exactly, tested on 2 playlists with more than 900 songs).
2. Download every song in the playlist.

### Expected behavior

The playlist download button should show that the playlist is downloaded when every song in the playlist is downloaded.

### Actual behavior

The playlist download button shows that the playlist is not downloaded.

### Screenshots/Screen recordings

Playlist where the bug occurs (Big playlists):
![Screenshot_2024-06-25-17-57-27-514_com zionhuang music](https://github.com/Malopieds/InnerTune/assets/81823105/f22e9195-051a-4df5-8919-eaede97f71b6)
Playlist where the bug doesn't occur (Small playlists):
![Screenshot_2024-06-25-17-58-10-634_com zionhuang music](https://github.com/Malopieds/InnerTune/assets/81823105/c42a68d8-e715-4d3a-b83c-96e1d8e18369)

### Logs

[log.txt](https://github.com/user-attachments/files/15969183/log.txt)

### InnerTune version

0.5.7-rc-2

### Android version

Android 14

### Additional information

Doesn't seem to only be a visual bug as it causes the "Do you really want to remove all "playlist name" playlist songs from the Downloaded Songs storage?" (Shown in the screenshot below) to not appear when the download button is tapped. 
![Screenshot_2024-06-25-18-22-33-986_com zionhuang music](https://github.com/Malopieds/InnerTune/assets/81823105/0ef04dd6-d45c-4a7c-9cb4-c7c0ccb33254)
This causes the downloads of some songs in the playlist to be inadvertently deleted when the download button is tapped. Weirdly, after some songs are deleted, it starts to download every song in the playlist again.

**Comment by Malopieds** [comment]
Where did you found a 900+ song playlists? Does this apply to local playlist only ? What happens if you click on select all?

**Comment by Irobrine** [comment]
> Where did you found a 900+ song playlists?

I imported the playlist from YouTube.

> Does this apply to local playlist only ?

Doesn't every playlist become local when imported?

> What happens if you click on select all?

It displays 946 elements selected.
After tapping select all and then the three dots, the download button is still in the incorrect state (not downloaded).
![Screenshot_2024-06-27-00-57-24-750_com.zionhuang.music.jpg](https://github.com/Malopieds/InnerTune/assets/81823105/8d533efa-383a-46e0-84ae-fea887da9ce1)

Here's the playlist in question if it helps with debugging:
https://youtube.com/playlist?list=PL1fqDrekyiuQ-EaVKtJs5CMZxQiQ0ZEnV

**Comment by Malopieds** [comment]
> Doesn't every playlist become local when imported?

Yes exactly, but it was a imported playlist and I think some of the issue might come from YouTube that's why I asked.

> It displays 946 elements selected.

From you local playlist or from the YouTube playlist?

For example, from your link it only shows 166 songs and when selecting all it show only 100:
![Screenshot_20240626-211142.png](https://github.com/Malopieds/InnerTune/assets/74783202/803147e9-ad43-4cff-bf13-4aac108bd9ce)

But if I import it and then sync it, it shows 936. I will check if the 100 songs limits apply also to the downloading songs...

**Comment by Irobrine** [comment]
> From you local playlist or from the YouTube playlist?

Local playlist imported from YT.

> But if I import it and then sync it, it shows 936. I will check if the 100 songs limits apply also to the downloading songs...

It downloaded ~930 songs when the playlist had ~940 songs.

Found a song in the playlist that can't be downloaded due to "No stream available":
![Screenshot_2024-06-27-13-10-07-573_com.zionhuang.music.jpg](https://github.com/Malopieds/InnerTune/assets/81823105/83c6e058-72b4-4856-9308-e567111dc477)

![Screenshot_2024-06-27-13-10-16-846_com.zionhuang.music.jpg](https://github.com/Malopieds/InnerTune/assets/81823105/146995a2-2ea3-4dc5-827a-656f9282996f)

Is there any way to remedy this? (i.e. Remove the song from the complete download count)

**Comment by Irobrine** [comment]
>Found a song in the playlist that can't be downloaded due to "No stream available":

Managed to fix it by following #87 (Deleted the app and not use a backup)
![Screenshot_2024-06-27-13-27-12-476_com.zionhuang.music.jpg](https://github.com/Malopieds/InnerTune/assets/81823105/22f2be94-5739-471b-a880-7621427d8359)

Close the issue if you deem it appropriate

**Comment by Malopieds** [comment]
Hi, the no stream available has been solved in latest commits, could you tell me if it fixes your issue too?

**Comment by Irobrine** [comment]
Yep, it did. Thank you.
