### ISSUE TITLE
Scroll back to top with a floating button

### ISSUE THREAD

**Issue by Irobrine** [Malopieds/InnerTune#134]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like a floating button somewhere (preferably around the bottom above the miniplayer) that allows me to scroll all the way to the top of the current page.

### Why do you want this feature?

Makes it easier to scroll back to the top of a page.

**Comment by Irobrine** [comment]
#96 is even better

**Comment by Malopieds** [comment]
Hi, now you can tap on the bottom navbar to go at the top, is it good enough?

**Comment by Irobrine** [comment]
Yes, thank you.
