### ISSUE TITLE
App crashes when long click on the song in the Smiler section

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#138]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

.

### Expected behavior

Options for sharing, downloading, etc., should appear.

### Actual behavior

The app crashes 

### Logs

![Screenshot_2024-06-26-16-42-48-033_com miui bugreport-edit](https://github.com/Malopieds/InnerTune/assets/80542861/1c5c3d68-816f-471c-b573-5cad2e7720d0)

### InnerTune version

debug version

### Android version

13

### Additional information

The issue is related to the same issue NO #28

**Comment by Malopieds** [comment]
Yep this is clearly the same issue as #28. Can you send something so that I can reproduce, I've never experienced that either...

**Comment by mostafaalagamy** [comment]
> Yep this is clearly the same issue as #28. Can you send something so that I can reproduce, I've never experienced that either...

I'll send a song and a link to the artist. Then, play the song multiple times repeatedly until it appears in the suggestions for similar sections. If the suggested songs don't appear, close the app and reopen it several times until you see the suggestions.

Song link : https://music.youtube.com/watch?v=dVTfLAq17ZA

Song name to copy : Etganen - Cairokee Feat. Aida El Ayouby & Zap Tharwat

Artist Link : https://music.youtube.com/channel/UCyIQoaB2Z1rowQNg7jlTWRw

Artist name to copy : Coca-Cola Egypt

![Screenshot_2024-06-26-18-27-55-501_com.metrolist.music-edit.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/eb0a008d-195c-4bba-be76-6e62b7510dd0)

**Comment by Malopieds** [comment]
Tell me if it fixes something

**Comment by mostafaalagamy** [comment]
It was resolved for some artists but appeared again with other artists.

![Screenshot_2024-06-26-19-23-17-451_com.zionhuang.music.debug-edit.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/a35bc8ff-bc74-400f-aa00-b0303c806896)



This is a backup that you can restore, and you will find the issue in it.


  ![InnerTune Debug_20240626191855.zip](https://github.com/user-attachments/files/15992233/InnerTune.Debug_20240626191855.zip)

**Comment by mostafaalagamy** [comment]
> This is a backup that you can restore, and you will find the issue in it.

[InnerTune_20240626193417.zip](https://github.com/user-attachments/files/15992335/InnerTune_20240626193417.zip)

**Comment by mostafaalagamy** [comment]
> This is a backup that you can restore, and you will find the issue in it.

[InnerTune_20240626193417.zip](https://github.com/user-attachments/files/15992335/InnerTune_20240626193417.zip)

**Comment by mostafaalagamy** [comment]
The issue back again!

https://github.com/Malopieds/InnerTune/assets/80542861/066199af-0328-435a-b870-c4a0afdc6749

backup of the issue

[InnerTune Debug_issue.zip](https://github.com/user-attachments/files/16042110/InnerTune.Debug_issue.zip)

**Comment by mostafaalagamy** [comment]
The issue back again!


https://github.com/Malopieds/InnerTune/assets/80542861/40388da7-5f59-4549-9d32-2376225cf6f2

backup of the issue

[InnerTune Debug_issue.zip](https://github.com/user-attachments/files/16042144/InnerTune.Debug_issue.zip)
