### ISSUE TITLE
Music recommendation

### ISSUE THREAD

**Issue by siggi1984** [Malopieds/InnerTune#14]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Spotify displays music recommendations at the end of a playlist, which you can then add to a playlist or play next, for example.

I know that YouTube also offers this based on the currently playing song.

This implementation would be cool for discovering new music that suits your tastes.
See screenshot.

I think this developer has implemented it well. 
https://github.com/25huizengek1/ViTune

### Why do you want this feature?

![302751670-77c1cbc3-10b8-4968-9324-e5c51380cbf0](https://github.com/Malopieds/InnerTune/assets/103368536/a3c521f9-651f-4f32-a884-0c0a26cdd60a)

**Comment by Malopieds** [comment]
Hi, I like the idea, but don't like ViTune's implementation. For each song that is currently playing, the recommendations changes. It's really not optimized since it requires an api call for EVERY songs. I will look how YouTube music handles it on their end !

**Comment by Malopieds** [comment]
It seems that youtube have their own implementation of this feature. I will then use their endpoint.

**Comment by siggi1984** [comment]
> It seems that youtube have their own implementation of this feature. I will then use their endpoint.

Sounds good. I can't wait to see how it turns out.

**Comment by fanieko** [comment]
I like this, but i just use the "radio" feature i don't even know how it works but it does.

**Comment by siggi1984** [comment]
> I like this, but i just use the "radio" feature i don't even know how it works but it does.

I hardly like any song from the radio function

**Comment by Filipexos** [comment]
> I hardly like any song from the radio function

I think the radio feature is just YouTube autoplay, so it shows the most popular songs people listen after the current song. 

It works fine for me idk.

**Comment by Malopieds** [comment]
I finally implemented it! You can check it out and tell me what you think about it. It is available for playlist and albums.

**Comment by siggi1984** [comment]
> I finally implemented it! You can check it out and tell me what you think about it. It is available for playlist and albums.

Sorry, I'm somehow blind. I can't see the music recommendations. I have the latest debug installed.

**Comment by Malopieds** [comment]
Play an album, scroll down to the bottom of the songs from this album and you'll see a "similar content" with a divider. I can't provide you with a screenshot. Hope this helps otherwise I'll add a screenshot when I can.

**Comment by siggi1984** [comment]
> Play an album, scroll down to the bottom of the songs from this album and you'll see a "similar content" with a divider. I can't provide you with a screenshot. Hope this helps otherwise I'll add a screenshot when I can.

I don't see any recommendations. See screenshot.

![Screenshot_2024-08-19-19-38-47-419_com malopieds innertune debug](https://github.com/user-attachments/assets/4bfe497b-7cc0-4c87-a8c4-1ebb7462cbe6)

**Comment by Malopieds** [comment]
![image](https://github.com/user-attachments/assets/699b8436-6ec5-4d01-b691-60e6c2b514f8)

Here is the example. Are you sure you're using [this](https://github.com/Malopieds/InnerTune/actions/runs/10454929811/artifacts/1827772174).

**Comment by siggi1984** [comment]
> ![image](https://private-user-images.githubusercontent.com/74783202/359194733-699b8436-6ec5-4d01-b691-60e6c2b514f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTQwNjksIm5iZiI6MTcyNDA5Mzc2OSwicGF0aCI6Ii83NDc4MzIwMi8zNTkxOTQ3MzMtNjk5Yjg0MzYtNmVjNS00ZDAxLWI2OTEtNjBlNmMyYjUxNGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE4NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOGNlNDg3NmM2ZWQ0MGRjOTk5OTk3MmIxMWQ0ODcyYWYyODY5NGE4Y2IxY2YxNGQ2Njg0YTJiZThhNDIwNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DATb3RyAYlnEd0MkPhi404gG7mhLOj-19UOo3n-bHeE)
> 
> Here is the example. Are you sure you're using [this](https://github.com/Malopieds/InnerTune/actions/runs/10454929811/artifacts/1827772174).

I installed the debug from your link. Unfortunately it doesn't work either. No idea why???

**Comment by Malopieds** [comment]
Did you pressed play or directly on the song? If directly on the song, press play and tell me if it works. I'll add the press on the song directly asap.

**Comment by siggi1984** [comment]
> Did you pressed play or directly on the song? If directly on the song, press play and tell me if it works. I'll add the press on the song directly asap.

okay, now we have it. I kept tapping on the song. when I press play it works. very well done, thank you very much 👍👍👍

**Comment by Malopieds** [comment]
Should be good now!

**Comment by mostafaalagamy** [comment]
> Should be good now!

Please add it new releases

**Comment by Malopieds** [comment]
> Please add it new releases

New releases are albums so yeah it already works.

**Comment by mostafaalagamy** [comment]
> > Please add it new releases
> 
> New releases are albums so yeah it already works.

No I mean when you click on the song from outside

![Screenshot_2024-08-19-23-25-25-321_com.malopieds.innertune.debug-edit.jpg](https://github.com/user-attachments/assets/6bcb74cc-600c-41c6-b7ee-37f861995c57)

Update:

Add it in all library albums screen and mix library screen

**Comment by Malopieds** [comment]
Ok I see, for the album it's possible but the local playlist (not from YTM) it's impossible.

**Comment by mostafaalagamy** [comment]
> Ok I see, for the album it's possible but the local playlist (not from YTM) it's impossible.

I know, I'm just talking about albums, thanks!
