### ISSUE TITLE
Smaller grid items

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#144]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can we get a smaller grid items just like in this screenshot :
![320232184-37cb5192-3e72-4230-aaf9-903e88e2b05a](https://github.com/Malopieds/InnerTune/assets/156727749/5658a696-b628-408c-a236-48ecad0d4cd6)

(the screenshot is from the UI Redesign discussion)

### Why do you want this feature?

the library would looks better than it is now

### Additional information

Notice:
- this enhancement was already mentioned in UI Redesign Discussion and I wanted to bring it here as a feature request, I wish if you can add it to the v0.5.8 milestone

**Comment by Spaceshiprace** [comment]
@Malopieds can you look into this one, i wish if you can add it to the milestone of any coming release.
thx for ur efforts 🙌

**Comment by Malopieds** [comment]
Yeah sure, but there won't be any push/release until august I guess, I'm on holiday!

**Comment by Spaceshiprace** [comment]
> Yeah sure, but there won't be any push/release until august I guess, I'm on holiday!

then have a good times 🙌
