### ISSUE TITLE
Some translations are missing in the code.

### ISSUE THREAD

**Issue by moxxaxx** [Malopieds/InnerTune#145]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to the library 
Missing translated words
( Liked, Offline, My Top)
And go to the settings 
Missing translated words
(Proxy)

### Expected behavior

It must have the option to be translated into the code files so that I can modify it 

### Actual behavior

There's no text to be translated inside Strings files

### Logs

No

### InnerTune version

Lastest

### Android version

14

### Additional information

Sorry for my English, because it's not my language

**Comment by moxxaxx** [comment]
there are some issues , I will show it in the screenshot

![Screenshot_2024-06-28-12-04-25-639_com malopieds innertune debug-edit](https://github.com/Malopieds/InnerTune/assets/174078460/b22b6833-b068-42ef-825b-86c7237465d3)
![Screenshot_2024-06-28-12-04-04-890_com malopieds innertune debug-edit](https://github.com/Malopieds/InnerTune/assets/174078460/953b230a-d224-4765-8075-bc05e738aaa9)

**Comment by Malopieds** [comment]
> there are some issues , I will show it in the screenshot

Thanks, fixed now

**Comment by moxxaxx** [comment]
> Thanks, fixed now

They're still problems

1- My Top Appear Liked in playlist filter section

![Screenshot_2024-06-28-12-23-29-458_com malopieds innertune debug-edit](https://github.com/Malopieds/InnerTune/assets/174078460/395302ac-eb8b-41e9-aec6-3c3e8b8502f4)

2- When translating into other languages, all icons appear as the queue icon 

![Screenshot_2024-06-28-12-24-45-318_com metrolist music-edit](https://github.com/Malopieds/InnerTune/assets/174078460/77391882-ec7a-4614-9748-ad5118322ed6)

**Comment by Malopieds** [comment]
> 1- My Top Appear Liked in playlist filter section

My bad I don't know why I messed up so much this easy one x) tell me if there are things that are still not done

**Comment by moxxaxx** [comment]
Firstly thanks , "Your YouTube playlists"  missing, I will tell you again if I find anything else

![Screenshot_2024-06-28-15-51-37-755_com metrolist music-edit](https://github.com/Malopieds/InnerTune/assets/174078460/b634a518-d87b-4ef0-adb9-fb819ef69b2b)

**Comment by moxxaxx** [comment]
> Firstly thanks , "Your YouTube playlists" missing, I will tell you again if I find anything else
> 
> ![Screenshot_2024-06-28-15-51-37-755_com metrolist music-edit](https://private-user-images.githubusercontent.com/174078460/344168657-b634a518-d87b-4ef0-adb9-fb819ef69b2b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Nzk3NTksIm5iZiI6MTcxOTU3OTQ1OSwicGF0aCI6Ii8xNzQwNzg0NjAvMzQ0MTY4NjU3LWI2MzRhNTE4LWQ4N2ItNGVmMC1hZGI5LWZiODE5ZWY2OWIyYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMjU3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGM5NDk0NDIyNWU1MWUxY2M3YzliZjkxNGZkMTM3YjIxYmZiMmU3MmY5YzAxZjhjZDM4NTFiMDAzMDQ2NGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8L4RmoxBRH6SkboChMYb13ojvzz9vRp5B6CTY6PkdHc)

Also "My Top X" List But from within the list

![Screenshot_2024-06-28-15-59-20-381_com metrolist music](https://github.com/Malopieds/InnerTune/assets/174078460/74408f4a-fd19-433a-b67f-9a822af3226d)

**Comment by Malopieds** [comment]
done

**Comment by moxxaxx** [comment]
> done

There's a word "Playlist" that hasn't been translated. You will find it in the warning text when removing downloads from Liked and Offline.

![Screenshot_2024-06-28-18-48-41-647_com metrolist music~2](https://github.com/Malopieds/InnerTune/assets/174078460/662d0fe1-96bb-4cd2-8a06-94f6eee9b365)

You will also find it at the top, as shown, when opening the queue while playing any song from the mentioned lists.

![Screenshot_2024-06-28-19-40-52-035_com metrolist music-edit](https://github.com/Malopieds/InnerTune/assets/174078460/74babf7e-663f-46e5-9cde-753251419a0e)

![Screenshot_2024-06-28-19-40-28-358_com metrolist music-edit](https://github.com/Malopieds/InnerTune/assets/174078460/a3d85a3f-b7e5-417c-a48e-3eea99f10c6f)

Also, the word "My Top X" hasn't been translated. You will find it at the top when opening the queue while playing any song in the "My Top X" list.

![Screenshot_2024-06-28-19-39-29-398_com metrolist music-edit](https://github.com/Malopieds/InnerTune/assets/174078460/fe279630-6c9a-435d-9c81-2e1d2ec08d5b)

**Comment by Malopieds** [comment]
Ok now.

**Comment by moxxaxx** [comment]
"Other versions" Missing translation in latest commit .
