### ISSUE TITLE
Account section playlists wont load

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#150]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

If you go home and the account and then pick a playlist

### Expected behavior

It should lead to you viewing the playlist

### Actual behavior

But instead the playlist doesn't appear to load. You just get a black screen with certain UI elements trying to load see screenshot

### Screenshots/Screen recordings

![Screenshot_2024-06-29-12-22-41-97_f4703f2d42345ac28c56f11a6100c500](https://github.com/Malopieds/InnerTune/assets/81394097/3b754f82-20c2-4e56-aba0-06938c93cd04)

### Logs

Don't know how to do this

### InnerTune version

0.5.7 rc 2

### Android version

Android 14

**Comment by Malopieds** [comment]
You're not using the right version. Please select the apk with fix-login in the name.

**Comment by Lorestan00** [comment]
Thanks. I've found the right version
