### ISSUE TITLE
Songs are not deleted in the likes, offline, and My Top X lists.

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#154]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Check secren record 

### Expected behavior

__

### Actual behavior

__

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/e30baf80-bf7e-4bbe-9539-7358f4178d57

### Logs

__

### InnerTune version

debug version

### Android version

13

**Comment by Malopieds** [comment]
Yep, ultimately this will be deleted since it has no purpose.

**Comment by mostafaalagamy** [comment]
> Yep, ultimately this will be deleted since it has no purpose.

Okay

**Comment by Malopieds** [comment]
Now done in [a2e694e](https://github.com/Malopieds/InnerTune/commit/a2e694e19923c47ff88888b98a8d81b403dc7051)
