### ISSUE TITLE
Please add 2 more section on Home Page

### ISSUE THREAD

**Issue by Sunilr001** [Malopieds/InnerTune#158]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In previous beta version there are 2 sections "Global Hit and Devotional Tune" But these 2 sections missing in this version, if you can so please add these 2 sections.

### Why do you want this feature?

It easy to listen Global & Devotional songs without deep search.

**Comment by Malopieds** [comment]
What you are referring to are the playlists made by YouTube music, I don't have any power on this.
