### ISSUE TITLE
Recently Liked Songs Don't Appear On Top of Liked Song Playlist(Out of Order)

### ISSUE THREAD

**Issue by ThalesX777** [Malopieds/InnerTune#160]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.Open the app.
2.Import Library from original app.
3.Like a song.
4.Navigate to the "Liked Songs" section in the library.
5.Like count increases, but newly liked song does not appear on top

### Expected behavior

Newly liked song should appear at top of the liked song playlist.

### Actual behavior

Song instead appears in the middle/out of order of the playlist.

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/167493903/1ec2366e-199c-4fcc-8fc1-6eb3ab7d01ff

### Logs

.

### InnerTune version

0.5.7

### Android version

Android 14

**Comment by Malopieds** [comment]
Yep, good catch, this is because I wasn't updating the time added in liked. It should work now, but the ones you liked before are going to be wrong, you might want to unlike then like.
