### ISSUE TITLE
Swipe to Next track or previous

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#164]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Ability to swipe left or right for previous or next track while in player or on mini player

### Why do you want this feature?

Essentially just quicker to skip or go back to track rather than press a smaller next track button in the mini player but also in the main player just naturally quicker motion. Essentially same as spotify

Main player
![Screenshot_2024-07-04-05-15-28-76_56635af9b6ad4512d4187a5a49185a25](https://github.com/Malopieds/InnerTune/assets/81394097/956210d7-bc71-4159-b296-d6bfc5784e89)

Mini player at the bottom
![Screenshot_2024-07-04-05-15-22-97_56635af9b6ad4512d4187a5a49185a25](https://github.com/Malopieds/InnerTune/assets/81394097/69828821-c2ac-4a68-ae0c-0d017089cb88)

**Comment by Malopieds** [comment]
There once has been this feature in the app. But the animation were not ready because they were causing some bugs. I could do it but there will be no animations (at least for now) will that be enough?

**Comment by Lorestan00** [comment]
That would be amazing. Not bothered about animations. 

Sorry to ask again when you make changes with new commits where can I find the updated version? I think you might call it debug version

**Comment by Malopieds** [comment]
> Not bothered about animations.

Okay then should be fairly easy then !

> where can I find the updated version

Go to the commits, see the latest, and click on the green checkmark, details, summary, at the bottom of the page you will find app.apk.

The link for this one is [this](https://github.com/Malopieds/InnerTune/actions/runs/9767786318/artifacts/1661371343)

**Comment by h-s-u-y-a** [comment]
I have installed the latest release, 0.5.8. This feature seems to not have been implemented.
Are there any plans to implement it, with or without the animation ?

**Comment by darumanzane** [comment]
Hello! Could you make this an option that can be activated from the settings menu? I find it more convenient to prevent changing songs by dragging because sometimes an unintended movement skips the song accidentally.

**Comment by Malopieds** [comment]
Please tell me if this is what you wanted and I'll need some feedback on the sensitivity of it. 

It is optional and can be deactivated in the settings.

**Comment by Lorestan00** [comment]
It works great ! Thanks. No issues for me
