### ISSUE TITLE
Add a repeat button

### ISSUE THREAD

**Issue by RUDRA78372** [Malopieds/InnerTune#168]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can a button be added on the player to repeat the current song over and over? Thanks
![Screenshot_20240705-111757_InnerTune](https://github.com/Malopieds/InnerTune/assets/34397749/139f4f56-22a1-4507-842b-e6a0e1ece80e)

### Why do you want this feature?

It was available in the original innertune app

**Comment by Malopieds** [comment]
Still available in the queue, bottom right.
