### ISSUE TITLE
Completion 05.7

### ISSUE THREAD

**Issue by computerclic** [Malopieds/InnerTune#171]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

How long until release 05.7 is complete?

### Why do you want this feature?

To solve the problems of 05.3

### Additional information

None

**Comment by Malopieds** [comment]
> How long until release 05.7 is complete?

It has been released 7 days ago

**Comment by computerclic** [comment]
Here I only see 05.3, where can I download 0.5.7? Anyway, congratulations
for the work done

[image: image.png]

Il giorno sab 6 lug 2024 alle ore 11:17 Malopieds ***@***.***>
ha scritto:

**Comment by Malopieds** [comment]
This is a fork repository, this will be another app installed than the original one

[Here](https://github.com/Malopieds/InnerTune/releases) is the link for my releases

**Comment by computerclic** [comment]
It's a release final?
Thank for all


Il giorno sab 6 lug 2024 alle ore 11:30 Malopieds ***@***.***>
ha scritto:

**Comment by computerclic** [comment]
There are some links not translated into Italian like home, explorer, library


Il giorno sab 6 lug 2024 alle ore 11:30 Malopieds ***@***.***>
ha scritto:

**Comment by Malopieds** [comment]
> It's a release final?

For now yes.

> There are some links not translated into Italian like home, explorer, library

You can help translating them ! See [this](https://github.com/Malopieds/InnerTune?tab=readme-ov-file#contributing-translations)

**Comment by computerclic** [comment]
I can't help us, I don't know how to do it, but thanks anyway.


Il giorno sab 6 lug 2024 alle ore 11:40 Malopieds ***@***.***>
ha scritto:
