### ISSUE TITLE
Bad traduction in french

### ISSUE THREAD

**Issue by ghost** [Malopieds/InnerTune#172]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

https://github.com/Malopieds/InnerTune/blob/dev/app/src/main/res/values-fr-rFR/strings.xml

### Expected behavior

`<item quantity="one">%d an</item>`

in singular, you write "an", not "ans"

### Actual behavior

`<item quantity="one">%d ans</item>`

### Logs

no

### InnerTune version

0.5.7

### Android version

Android 13

**Comment by Malopieds** [comment]
Sure I can change it, you can also add other translations that are missing in french if you want ?

**Comment by ghost** [comment]
Thanks.

Yes, I can.
I think the best solution is to create your project on Weblate, no ?

Example : https://hosted.weblate.org/projects/breezy-weather/breezy-weather-android/
https://hosted.weblate.org/projects/

**Comment by Malopieds** [comment]
Yes indeed Weblate is a nice feature to have, but the original repo had one too, so I cannot create one with the same name :/
I'll see what I can do later on.

**Comment by ghost** [comment]
No prob ;)

Full French version :
[fr_strings.zip](https://github.com/user-attachments/files/16119977/fr_strings.zip)
