### ISSUE TITLE
Some songs won't play but if there are alternatives, they will

### ISSUE THREAD

**Issue by ReallyYug** [Malopieds/InnerTune#174]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

N/A

### Expected behavior

The songs should play

### Actual behavior

There are probably more but so far I have only encountered 2 songs that doesn't play so I have to use their alternatives ( uploaded by someone else ) the songs are Fuck love - xxxtenctacion and Jocelyn Flores - xxxtenctacion

### Screenshots/Screen recordings

![Screenshot_2024-07-07-10-08-18-24_56635af9b6ad4512d4187a5a49185a25](https://github.com/Malopieds/InnerTune/assets/112211279/23eb1a79-1175-4462-b83d-f6bea98515b8)
![Screenshot_2024-07-07-10-08-09-66_56635af9b6ad4512d4187a5a49185a25](https://github.com/Malopieds/InnerTune/assets/112211279/84e4a8e1-7dbc-49d7-950c-2ac9881899af)

### Logs

Idk where to get logs from sorry, but you can just try to play those songs on your device and can see ig

### InnerTune version

0.5.7

### Android version

Android 13

**Comment by ReallyYug** [comment]
I was forgetting Grammer 😭😭

**Comment by ReallyYug** [comment]
@Malopieds help 🥺 ( sorry for notification 😭 )

**Comment by Malopieds** [comment]
Hi, this is actually related to the fact that this audio is age restricted, I don't think I can bypass this. I think youtube asks for a connected account on the original youtube. I don't know if I can bypass it, even if a user is logged in.

**Comment by ReallyYug** [comment]
Oh alright no problem ig
