### ISSUE TITLE
Optional Gradient in Music Player

### ISSUE THREAD

**Issue by ThalesX777** [Malopieds/InnerTune#175]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There's a new feature that includes a gradient background in the music player. While this is a cool feature in dark mode, I am not a fan of how it looks in light mode. Would it be possible to make this feature optional?
![Screenshot_20240707_141906_InnerTune Debug](https://github.com/Malopieds/InnerTune/assets/167493903/4a2010a6-9fcd-4849-8c86-bf5423fa0c51)

### Why do you want this feature?

Would add customization

**Comment by Malopieds** [comment]
What version are you using? It's not how it looks in the app, even with this song

**Comment by ThalesX777** [comment]
> What version are you using? It's not how it looks in the app, even with this song

This is using the latest debug version

**Comment by mostafaalagamy** [comment]
![Screenshot_2024-07-09-16-37-06-872_com.malopieds.innertune.debug.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/89496b99-8115-411f-aba6-2697ec7e82ff)

And me

**Comment by mostafaalagamy** [comment]
After enabling gradient and playing a song with a white cover, the background and lyrics appear in this way.


![Screenshot_2024-07-10-20-24-34-948_com.malopieds.innertune.debug.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/19bcbc2d-9fbd-4aca-88d6-0370edf2c56a)

![Screenshot_2024-07-10-20-24-32-020_com.malopieds.innertune.debug.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/e5efee05-060e-49cd-ad08-ab83616665d4)

**Comment by Malopieds** [comment]
> After enabling gradient and playing a song with a white cover, the background and lyrics appear in this way.

Send the name of the song here

**Comment by mostafaalagamy** [comment]
> > After enabling gradient and playing a song with a white cover, the background and lyrics appear in this way.
> 
> Send the name of the song here

Song name: جامدين جامدين

Song link : https://music.youtube.com/watch?v=k--8iGPXZ8E

**Comment by Malopieds** [comment]
Should be good now

**Comment by mostafaalagamy** [comment]
> Should be good now

Now it has been fixed, but the words become transparent and hard to see.

**Comment by Malopieds** [comment]
> Now it has been fixed, but the words become transparent and hard to see.

wdym? The lyrics?

**Comment by mostafaalagamy** [comment]
> > Should be good now
> 
> Now it has been fixed, but the lyrics become transparent and hard to see.

**Comment by mostafaalagamy** [comment]
> > Now it has been fixed, but the words become transparent and hard to see.
> 
> wdym? The lyrics?

Sorry, lyrics yes

**Comment by mostafaalagamy** [comment]
![Screenshot_2024-07-10-21-42-40-602_com.malopieds.innertune.debug.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/52c95681-8730-4a6c-87cd-baa5e17ee21a)

**Comment by mostafaalagamy** [comment]
> ![Screenshot_2024-07-10-21-42-40-602_com.malopieds.innertune.debug.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/52c95681-8730-4a6c-87cd-baa5e17ee21a)
> 
> 

![Screenshot_2024-07-10-21-57-08-964_com.malopieds.innertune.debug.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/aa2b1983-4e50-41a2-b896-f247fd3c4796)

**Comment by Malopieds** [comment]
I think it's better now
