### ISSUE TITLE
Stop music playback when app is closed and cleared from recent tasks

### ISSUE THREAD

**Issue by dainvincible1** [Malopieds/InnerTune#18]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A setting to stop music playback when app is closed and cleared from recent tasks. 

### Why do you want this feature?

Its easier to close the app with the feature. A toggle option will be great.
![image](https://github.com/Malopieds/InnerTune/assets/127825700/7649f01d-fc34-442c-8cd0-ac037a29cfd8)

**Comment by Malopieds** [comment]
I personally don't like this idea. If you want to stop it, you just have to pause the music and close the app. I'm not gonna implement it right now, PR are welcomed though.
