### ISSUE TITLE
Import from innertune shows all library songs considered as liked songs

### ISSUE THREAD

**Issue by Eliya-Manoj** [Malopieds/InnerTune#180]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

InnerTune - add some songs to library without liking the song because, the liked songs automatically add to library.

1. Backup from InnerTune ( Original )
2. Restore from backup file 
3. shows library songs considered as liked songs

### Expected behavior

Liked Songs are already in Library. Consider Library songs not always as Liked songs ( Like Original ). Actually, i manually added songs to library.

### Actual behavior

All library songs considered as liked songs ( Only Import from backup )

### Screenshots/Screen recordings

InnerTune

![photo_2024-07-09_08-59-45](https://github.com/Malopieds/InnerTune/assets/90308888/ed42f22b-ed0e-46de-abdc-f1a18151d9e8)

InnerTune Fork

![photo_2024-07-09_08-59-49](https://github.com/Malopieds/InnerTune/assets/90308888/bc765e77-dd37-48fc-9bd7-0a8c3b7b51fe)

### Logs

It is actually easy to find.

### InnerTune version

0.5.7

### Android version

Android 12

**Comment by Malopieds** [comment]
Yep, that's how it has been done from now on. It will likely changed after some discussions. I will soon publish a release that revert this to avoid too much lose of information. But yeah keep a copy of the old backup.

**Comment by Malopieds** [comment]
It should be fixed in the latest version, can you confirm this and close the issue?
