### ISSUE TITLE
The animation has become extremely slow.

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#182]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Slow animation in the app causes some things to happen via the settings, such as opening windows while exiting and bad touch. the animation speed was previously perfect.

### Expected behavior

__

### Actual behavior

__

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/9e9fb51a-2e85-40f1-84a8-0eb2a7c23fcb

### Logs

__

### InnerTune version

debug version

### Android version

13

**Comment by Malopieds** [comment]
No it's not. It's because in version 2.7.0 of navigation they added animations, which they were not really before. So yeah what you see are animations, I don't like them either so I will roll back to just before that version, and waiting for it to become stable enough to remove those animations entirely.

**Comment by mostafaalagamy** [comment]
> No it's not. It's because in version 2.7.0 of navigation they added animations, which they were not really before. So yeah what you see are animations, I don't like them either so I will roll back to just before that version, and waiting for it to become stable enough to remove those animations entirely.

Great, thanks
