### ISSUE TITLE
Export database as CSV or JSON

### ISSUE THREAD

**Issue by airon90** [Malopieds/InnerTune#183]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to export my music into a common format like csv or json

### Why do you want this feature?

Exported data can be used with other apps and can be managed better

**Comment by Malopieds** [comment]
Won't be done in the app, you can sure use [external tools](https://stackoverflow.com/a/53231260) for this

**Comment by Ahamed07** [comment]
@Malopieds 
I tried to open the .backup file using the DB Browser for SQLite it asks for password ? so how to open it ? what should i do?
![Screenshot 2024-12-12 at 8 22 34 PM](https://github.com/user-attachments/assets/65c5fc82-2f80-4bcb-9f6d-f57e9951c48d)
