### ISSUE TITLE
Offline music

### ISSUE THREAD

**Issue by Mrunknow3** [Malopieds/InnerTune#186]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to app
2. Offline download
3. Play
4. But that's not playing
5. But i touch shuffle button that's plya

### Expected behavior

They directly playing. 

### Actual behavior

That not playing offline music when nets off. 

### Screenshots/Screen recordings

Uploading Screenrecorder-2024-07-10-13-47-00-674.mp4…

### Logs

Idk

### InnerTune version

0.5.7

### Android version

Android 13

### Additional information

That bug also have old versions.

**Comment by Mrunknow3** [comment]
That was fixed after the new update come
Bcz now not fixed I see.

**Comment by Malopieds** [comment]
It's fixed in the commit linked to this issue, it will come in the next release.

**Comment by Mrunknow3** [comment]
Arigato gozaimusu
