### ISSUE TITLE
Add an option to add to/remove from the library in the menu. 

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#189]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Since the situation has returned to the old state, it is important to bring back this option to control the library.

### Expected behavior

__

### Actual behavior

__

### Logs

__

### InnerTune version

debug version

### Android version

13

**Comment by Malopieds** [comment]
It's planned yes
