### ISSUE TITLE
Artist section being replaced by album name

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#19]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Search for a song
- click on the song at the "songs" section :

![Screenshot_2024-03-25-19-51-18-793_com zionhuang music_1_1](https://github.com/Malopieds/InnerTune/assets/156727749/802a4597-aa96-45e0-92e1-21084407971a)

### Expected behavior

It supposed to be the name of the artist there

### Actual behavior

it appears the name of the album

### Screenshots/Screen recordings

![Screenshot_2024-03-25-19-51-26-343_com zionhuang music_1_1](https://github.com/Malopieds/InnerTune/assets/156727749/df6365ea-6b6b-4965-810d-03f28a8bb77a)

### Logs

idk

### InnerTune version

0.5.5

### Android version

Android

### Additional information
Notes :
- when I click on that album name that i mentioned it takes me to this page ( seems like artist page) and it keeps loading as in this screenshot :
![Screenshot_2024-03-25-20-02-35-073_com zionhuang music_1](https://github.com/Malopieds/InnerTune/assets/156727749/eb477f44-292c-4319-a016-03a24fc4630b)
- also the song name when I click on it didn't takes me to the album as it should do
(Please try it by yourself and figure out what I'm talking about)

**Comment by Malopieds** [comment]
Rightly spotted. Youtube changes it a lot and it is such a headache to fix it every time. I'll look into the issue ASAP.

**Comment by Spaceshiprace** [comment]
appreciate your effort to look into it ❤️
