### ISSUE TITLE
Button Missing from Music Player 

### ISSUE THREAD

**Issue by filinux13** [Malopieds/InnerTune#191]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Open any song
- 1650x720 with 380 dp Minimum width (i don't think this is needed to reproduce the "bug")

### Expected behavior

This should have an option, like Advanced, or be spaced, so there isn't a gap on the interface

### Actual behavior

its blank, its ugly and it shouldn't be like this
![fix this hole pls](https://github.com/Malopieds/InnerTune/assets/131296086/e494d787-1de6-47c1-aaf0-eb1d260cdb5f)
 
(also, i noticed the Sleep Timer is offset, that could be also fixed..)
![sleep timer slighty offset](https://github.com/Malopieds/InnerTune/assets/131296086/4de08293-5227-4425-b471-1e717edbf16a)

### Logs

Not needed, this is a UI "bug"

### InnerTune version

0.5.7

### Android version

Android 13

**Comment by Malopieds** [comment]
> its blank, its ugly and it shouldn't be like this

This is how it is.

> (also, i noticed the Sleep Timer is offset, that could be also fixed..)

This can be worked on

**Comment by 9glenda** [comment]
Does this also fix the sleep timer cutting of part of the remaining time?

![1000033409](https://github.com/Malopieds/InnerTune/assets/69043370/59d57b92-49ab-40c8-aa2a-0ab9e4cd40cf)

**Comment by Malopieds** [comment]
> Does this also fix the sleep timer cutting of part of the remaining time?

No, I didn't thought of that, but that about the fact that it's too big i'll try to put it in marquee and hope it looks good enough !
