### ISSUE TITLE
When scrolling in quick picks, there is lag.

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#193]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When scrolling, it should scroll step by step, but here it scrolls quickly to the end.

### Expected behavior

__

### Actual behavior

__

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/e0564862-9b75-4422-8669-dbeafaa26bbc

### Logs

__

### InnerTune version

debug version

### Android version

13

**Comment by EisregenHaha** [comment]
it doesnt lag for me but the reason for your lag is probably that it scrolls so extremely fast now since a few days, idk since what commit but he changed it. its horrible, you cant even swipe a single page anymore. idk why he changed something that already was perfect tbh but maybe it was accidental

**Comment by Malopieds** [comment]
Yeah this is not lag, it's from updating the dependencies of compose, they changed things :/ I it will be better now, I will push a fix in the next minute.

Edit: pushed now, tell me if it fixes

**Comment by mostafaalagamy** [comment]
> Yeah this is not lag, it's from updating the dependencies of compose, they changed things :/ I it will be better now, I will push a fix in the next minute.
> 
> Edit: pushed now, tell me if it fixes

Fixed now

**Comment by EisregenHaha** [comment]
> Yeah this is not lag, it's from updating the dependencies of compose, they changed things :/ I it will be better now, I will push a fix in the next minute.
> 
> Edit: pushed now, tell me if it fixes

yippie thanks
