### ISSUE TITLE
Show line animation (from MaterialYou Design)

### ISSUE THREAD

**Issue by GuiSousa135** [Malopieds/InnerTune#194]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When the music is playing, show an animation in the timeline of reproduction in the standard MaterialYou Design.

### Why do you want this feature?

The MaterialYou standard makes the application interface more elegant and intrusive. The animation helps the user to see when the music is playing.

### Additional information

![Screenshot_20240710-104720_Cromite_1_1](https://github.com/Malopieds/InnerTune/assets/55188286/d8883393-6050-49f5-8569-ba8c20aacc09)

**Comment by Malopieds** [comment]
It is [not](https://m3.material.io/components/progress-indicators/specs) part of material design, but I might add it as an optional
