### ISSUE TITLE
Missing "Repeat"/" Repeat all" button

### ISSUE THREAD

**Issue by foxyseta** [Malopieds/InnerTune#196]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Use the music player
2. Look for the "Repeat"/" Repeat all" button

### Expected behavior

The upstream version has a "loop"/"loop all" button.

### Actual behavior

My player is stuck in "Repeat one" mode.

### Logs

N/D

### InnerTune version

0.5.7

### Android version

LineageOS 20

**Comment by Malopieds** [comment]
There still is one. It is at the bottom right of the queue.

**Comment by foxyseta** [comment]
Thank you!
