### ISSUE TITLE
App crashes on download (Android 14)

### ISSUE THREAD

**Issue by Malopieds** [Malopieds/InnerTune#2]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Download any song

### Expected behavior

Should not crash

### Actual behavior

Crash

### Logs

MissingForegroundServiceTypeException

### InnerTune version

0.5.5

### Android version

Android 14

### Additional information

See [this](https://developer.android.com/about/versions/14/changes/fgs-types-required#use-cases).

**Comment by Spaceshiprace** [comment]
when it will be fixed ?

**Comment by Malopieds** [comment]
> when it will be fixed ?

I'll try a fix this afternoon, and might send the fix on a pre-release max on Saturday.

**Comment by Malopieds** [comment]
Closing this as it is fixed with [this pre-release](https://github.com/Malopieds/InnerTune/releases/tag/v0.5.5-fix-download)
