### ISSUE TITLE
The mini player when closed, the application crashes

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#20]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When dragging this window downward to close the mini player, the application crashes 'forced stop' 

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

![IMG-20240326-WA0003](https://github.com/Malopieds/InnerTune/assets/80542861/33ea53be-7d42-413f-b218-bcd9534d857a)

### Logs

No

### InnerTune version

0.5.5 debug version

### Android version

10 and 14

**Comment by Malopieds** [comment]
Yep, still because of the swipe on thumbnail x)

**Comment by mostafaalagamy** [comment]
> Yep, still because of the swipe on thumbnail x)

Damn swiping
