### ISSUE TITLE
long content like podcast doesn't get playd

### ISSUE THREAD

**Issue by xlipse7** [Malopieds/InnerTune#207]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

play any podcast with over one hour or longer, i use it to listen to it without screen on

### Expected behavior

should get playd

### Actual behavior

it get played for about  two or three mins and get stopped or even start to reproduce

### Logs

4

### InnerTune version

latest

### Android version

Android 14

**Comment by Malopieds** [comment]
Yes, podcast are (at least for now) not supported

**Comment by xlipse7** [comment]
> Yes, podcast are (at least for now) not supported

it would be good with podcast and also the app suggest you some podcast list, from known podcasters etc etc.
Anyways no hurry it's just for you to keep in mind.

**Comment by Malopieds** [comment]
Moving this to #213 then
