### ISSUE TITLE
suggestions under albums or singles

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#208]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can you add these suggestions they're under albums and singles (just like other versions for albums)

### Why do you want this feature?

it shows more suggestions for the listener so u can explore more music similar to the music that u listening to

**Comment by Malopieds** [comment]
If there is not this information in youtube music (and I don't think there is in the artist page) then no.

Where are you seeing this, In suppose Apple Music on an artist page ?

**Comment by Spaceshiprace** [comment]
> Where are you seeing this, In suppose Apple Music on an artist page ?

yea it is.

**Comment by zettaexa** [comment]
last fm also provides related albums on an album page if there is some way to get using its API that it would be cool
![Screenshot_20240712-025225.png](https://github.com/user-attachments/assets/03775136-b05b-4580-a8b9-ebf699689fea)

**Comment by Malopieds** [comment]
Yes last.fm provides this information but it's either we risk a ban for the app (too much request), or need to use an api key (which I won't provide) so I don't know about this...

**Comment by Spaceshiprace** [comment]
> Yes last.fm provides this information but it's either we risk a ban for the app (too much request), or need to use an api key (which I won't provide) so I don't know about this...

Alright then so I'm closing this.
