### ISSUE TITLE
Select button on YouTube music/other not imported playlist crashes the app due to language translation error🇫🇷

### ISSUE THREAD

**Issue by Richard38907** [Malopieds/InnerTune#211]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

On a YouTube music playlist click the select all button and see crash

### Expected behavior

![344554356-cd93e9db-8799-4119-99dd-064334d00e98](https://github.com/user-attachments/assets/5e6de9e5-0745-4414-a642-43524b1cfe5f)

### Actual behavior

Instead of selecting all songs in playlist

### Logs

[bugreport-CPH2415EEA-UKQ1.230924.001-2024-07-12-07-38-47-dumpstate_log-30106.txt](https://github.com/user-attachments/files/16188662/bugreport-CPH2415EEA-UKQ1.230924.001-2024-07-12-07-38-47-dumpstate_log-30106.txt)
[dumpstate-stats.txt](https://github.com/user-attachments/files/16188663/dumpstate-stats.txt)
[Uploading bugreport-CPH2415EEA-UKQ1.230924.001-2024-07-12-07-38-47.zip…]()

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by Malopieds** [comment]
It doesn't crash. Could you provide some (real) logs, with adb? There is no occurrence of my package in your "logs"

**Comment by Richard38907** [comment]
Thanks
I have never created logs with adb.
Can I use this command to do that?
![IMG_20240724_215845.png](https://github.com/user-attachments/assets/a1694d70-a2ca-4b9e-8a4b-f8e2268b5a2b)

**Comment by Malopieds** [comment]
Yep just use `adb logcat > logcat.txt` should be enough on windows

**Comment by Richard38907** [comment]
I will do that soon

I send you a video of the crash now

https://github.com/user-attachments/assets/153cd2fc-9a3a-4e0e-9fdc-509455303898

![Screenshot_20240724-220441.png](https://github.com/user-attachments/assets/56ecd378-b293-477b-b0f2-ed319d9b5c81)

**Comment by Richard38907** [comment]
My device is OnePlus 10t android 14.
I will test it on my OnePlus nord PixelExperience 13 soon.

**Comment by Malopieds** [comment]
Yep will need logs. Does this happens in the latest debug app ?

**Comment by Richard38907** [comment]
Where can I find the debug version?

**Comment by Richard38907** [comment]
I confirm that it crashes on my OnePlus Nord too

**Comment by Richard38907** [comment]
![logcat.txt](https://github.com/user-attachments/files/16367621/logcat.txt)

**Comment by Richard38907** [comment]
I found debug version  on that link

https://github.com/Malopieds/InnerTune/actions/runs/10080242068#artifacts

The app crashes too sadly🫤

**Comment by Richard38907** [comment]
I found the error🎉. The app doesn't crash in English language. I m in french here and it crashes again.

**Comment by Malopieds** [comment]
Ok, thanks for the investigation. I will look into it whenever I can !
