### ISSUE TITLE
New icon for the app

### ISSUE THREAD

**Issue by darumanzane** [Malopieds/InnerTune#212]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hello!
I think that, since v0.5.7 we have another app, it would be nice to differentiate between the original app and the new one.
I suggest the color from the icon could change. That, and maybe the name too? I really don't know how this works, so maybe that's not possible.

### Why do you want this feature?

It would give the app a new identity, and I think it would be nice to have a similar icon but with a distinction for the ones like me: people that have both the pre v0.5.6 and post v0.5.7 and confuse them when trying to use them.

**Comment by ThatOneUnoriginal** [comment]
Not to be rude but this seems so much of a non-issue to have such be done. Why would you keep an older version of the app when you can just export from the old one and then import to the new one. I don't see any practical reason to keep both so ultimately changing the icon for an issue that isn't really much and something only a handful of people will experience seems unnecessary.

**Comment by darumanzane** [comment]
> Why would you keep an older version of the app when you can just export from the old one and then import to the new one.

Cause the bug with some streams makes difficult to actually get the 4000+ songs I already have in the older app to be redownloaded and tested. But that's besides the point, I only mentioned that to give context to my line of thoughts.

I still think there's value in having a new look to the app: the original developer stopped working in the app almost a year ago. Malopieds, on the other hand, has been updating and upgrading the app consistently since then. This app is derivative from the work of z-huang, of course, but Malopieds has put up enough work that I think it deserves its own recognition. Hence the new icon that differentiate the new app.

Plus, getting the image in any program (Photoshop, Krita or even Paint) and changing the hues used in it is not that difficult of a task. I'm not asking for a new design and radical changes. Changing the colors of the icon could be enough to give the new app identity.

Regardless, that's my opinion and I'm entitled to voice it, the same way you're entitled to express yours. At the end of the day, I'm just happy to put my ideas and knowledge of the app (that I've using consistently for a couple of months) to the service of improving the experience of using it.

Maybe I'm the only one that sees value in the changes that I propose, maybe some people thinks like me.

**Comment by ThatOneUnoriginal** [comment]
> (...)but Malopieds has put up enough work that I think it deserves its own recognition.

Something like a new icon won't really result in that happening (especially a minor adjustment like a simple hue change as you mentioned) because ultimately the app name at the end of the day is still InnerTune. 

Plus they have been getting their own recognition through people downloading and using the forked app alongside suggesting new ideas and reporting bugs. This fork of the app has basically become the de facto version of the app.

**Comment by pdimu** [comment]
> (...) because ultimately the app name at the end of the day is still InnerTune. 

OuterTune?

**Comment by GuiSousa135** [comment]
I believe it would be great if the app adopted its own identity (logo and name) as the project is getting better and better, therefore distancing itself from the original forked project. Maybe a little change for the project becomes unique.

**Comment by darumanzane** [comment]
Yeah, I think the same thing. Hopefully in the future it can be done.

**Comment by Malopieds** [comment]
Yes I want to do it before v0.6.0 I'm still looking for ideas for the name and the new logo.

**Comment by pdimu** [comment]
> Yes I want to do it before v0.6.0 I'm still looking for ideas for the name and the new logo.

i think naming it vinyltune with a vinyl logo with the innertune style would be great

**Comment by Malopieds** [comment]
It's not really fluid to pronounce I think :/

**Comment by GuiSousa135** [comment]
Some options that I thought were cool (from ChatGPT).

OpenTune
FreeBeat
SoundShare
LibraMusic
HarmonyHub
TuneForge
MelodyBox
EchoLibre
TrackWave
SonicOpen

I think choosing the app name is the first step in choosing the new logo and the identity.

**Comment by GuiSousa135** [comment]
Keeping blue as the main color and adopting black as the background color would make the logo very modern.

**Comment by Malopieds** [comment]
I liked OpenTune, but it has been taken recently.

I was thinking about LibreTune but it too similar to [LibreTube](https://github.com/libre-tube/LibreTube) I think (youtube frontend app).

**Comment by mostafaalagamy** [comment]
> I liked OpenTune, but it has been taken recently.
> 
> I was thinking about LibreTune but it too similar to [LibreTube](https://github.com/libre-tube/LibreTube) I think (youtube frontend app).

MaloTune! did anyone suggest it to you?

**Comment by Malopieds** [comment]
> MaloTune! did anyone suggest it to you?

Yes someone did but I find it too selfish of including my name in it for a (real) project. I've done it for mock project that only me or my friends were using but this is another size x).

I was also thinking about OpenChord (that's also a musical term for guitar)

**Comment by mostafaalagamy** [comment]
> OpenChord (that's also a musical term for guitar)

Delicious.

Also, OpenStream

**Comment by GuiSousa135** [comment]
LibreWave?

**Comment by pdimu** [comment]
> > MaloTune! did anyone suggest it to you?
> 
> Yes someone did but I find it too selfish of including my name in it for a (real) project. I've done it for mock project that only me or my friends were using but this is another size x).

That was me! 😄

And I changed the name of the app in my launcher with MaloTune, which helps me differentiate the original from yours
![image](https://github.com/user-attachments/assets/4fd87cf8-bd6b-4ead-86b5-512ab19ae8d9)

**Comment by Malopieds** [comment]
I think I'll go with OpenChord(s). Any idea with the logo?

**Comment by darumanzane** [comment]
Hi. I got some sketches:
![image](https://github.com/user-attachments/assets/477072af-7a31-445f-b3d4-0d1c3efb7f4e)

**Comment by darumanzane** [comment]
Hi, I got some sketches. Let me know if want a logo without letters. I based the designs on this:
https://www.guitarcommand.com/wp-content/uploads/2021/05/Open-Chords-Guitar-Major.png
Here is what I drew:
![image](https://github.com/user-attachments/assets/f58101a3-0877-4468-8fbc-dbe7a8dd2b86)

**Comment by Malopieds** [comment]
Hi, firstly thanks for the input! I think keeping the O is a good idea from open is a good idea. I'm not sure about the C maybe it would be better to have something more distinguishable, like an icon of something (maybe inside the O/continuing its path) what do you think?

**Comment by darumanzane** [comment]
Yeah, is no problem, I'm happy to help with what I can since I can't code.

Could you give me more details about the (1) icon that replaces C and (2) the O continuing it's path? Also, can you give me your input with this: (3) what kind of style do you prefer?

A. •Bolder letters •Thinner letters
B. •Stylized (like, with a lot of curves or arabesques) •Sober (more angular, geometric)
C. •Letters that are just letters •Letters that also can represent something (for example: an O that looks like a gramophone or maybe a vinyl)

I think that this information could help me design something of your liking.

**Comment by GuiSousa135** [comment]
The important thing is to maintain the minimalism and elegance of the logo application's design, I think the current logo reflects this well, but a new identity is important.

**Comment by Malopieds** [comment]
> icon that replaces C 

I thought something, that still has a link with music, maybe a music note or something like this?

> the O continuing it's path?

The O is starting but the icon follow the line of the O, but that's just an idea

For the O I think more bold letter and will render better. The idea of a vinyl with a music note can be good !!

Edit: 
> maintain the minimalism and elegance of the logo application's design

That's very true! It needs to be minimalist too!

**Comment by darumanzane** [comment]
I did this earlier, let me know if you like some concept, style or idea in any of these:
![IMG_20240825_211438](https://github.com/user-attachments/assets/b57103c8-41aa-40e8-b0ba-bfd04a3cd1d5)
![IMG_20240825_214808](https://github.com/user-attachments/assets/9b55abb3-db85-4174-b326-d5dd1e6ecbe7)

**Comment by darumanzane** [comment]
Tried some more:
![IMG_20240828_200547](https://github.com/user-attachments/assets/a0ff3406-0e7f-4b9a-a0d3-74914b6baad9)

**Comment by pdimu** [comment]
@Malopieds you decided what logo to use?

**Comment by ghost** [comment]
I think something based off of the sound hole of a guitar would work great with the name.

![images](https://github.com/user-attachments/assets/1254fd4e-cbcd-4039-ae5f-b579fa1d6674)


The shape of the hole represents the O (as in "Open") and then you have the strings representing the "chords".

If only there are any designers willing to turn this idea into an actual icon :P

**Comment by pdimu** [comment]
> I think something based off of the sound hole of a guitar would work great with the name.
> 
> ![images](https://github.com/user-attachments/assets/1254fd4e-cbcd-4039-ae5f-b579fa1d6674)
> 
> 
> The shape of the hole represents the O (as in "Open") and then you have the strings representing the "chords".
> 
> If only there are any designers willing to turn this idea into an actual icon :P

That is a very good idea. What does @Malopieds say tho?

**Comment by itsmeteddyhere** [comment]
> I was also thinking about OpenChord (that's also a musical term for guitar)
Thank god it's not BarreChord 😂

I also thought of FOSSTune but it sounds a bit weird, also thought about OpenMusic but sounds a bit generic. But just leaving this here just incase you actually like one of these

**Comment by IzzySoft** [comment]
Good to see you're already on it. At IzzyOnDroid, if you see the two apps in the same list they are almost impossible to distinguish as icon and name are identical:

![image](https://github.com/user-attachments/assets/abde6a60-71c9-4499-bba0-02ac307fcbd9)

and it was already [reported as an issue](https://gitlab.com/IzzyOnDroid/repo/-/issues/639). I've missed that when adding the app here or I had waited adding it until this is solved.

Seeing this discussion is already ongoing for 3+ months, is there any ETA of when it might be solved? Not meant as pressure of course.

**Comment by IzzySoft** [comment]
@Malopieds may I renew my question concerning the ETA? Replacing the icon should not be too hard (well, provided you have a replacement – but at least for an interim solution, until a final decision has been made, one of the above should do, no?)

**Comment by Malopieds** [comment]
Yes, the next release will include a new logo. If anyone can provide a simple svg, I will add it asap. I forgot a bit about this to be honest x)
Depending on when I have a logo. One of the many @darumanzane proposed, just not one that looks too much like the current one, so no sixteenth note (I think it's the English term). They all looks good :)

**Comment by IzzySoft** [comment]
Great, thanks! Then we can finally close a bunch of issues :see_no_evil:

**Comment by Malopieds** [comment]
![image](https://github.com/user-attachments/assets/4c35f965-beff-4700-ae88-be8eea6512b7)
What do you think about this? Maybe not keeping the outer circle, I'm in no mean a pro in design and I think we can see this x)
If anyone has better proposition I'm open to suggestion. This was based on number 14

**Comment by IzzySoft** [comment]
Well, it's clearly an _inner_ tune if you keep the outer circle :rofl: I'd say go with it. Should something come up which you like more, you can still switch another time – but until then, at least the confusion would be gone.

**Comment by Malopieds** [comment]
> Well, it's clearly an inner tune if you keep the outer circle 🤣 I'd say go with it. Should something come up which you like more, you can still switch another time – but until then, at least the confusion would be gone.

Yeah, you're right. I've sent a message on another fork where a proposition (now abandoned) of a logo was made, and I liked it more. I'm only waiting for their response. 

https://github.com/Arturo254/OpenTune/issues/79#issuecomment-2480599871

**Comment by IzzySoft** [comment]
Ah, and I see you got 2 "Yays" there already, congrats! :star_struck:

**Comment by Malopieds** [comment]
This is now finally completed ! Yay !

**Comment by IzzySoft** [comment]
Wonderful! Don't forget to update it in your fastlane tree when you're ready please :wink:
