### ISSUE TITLE
Playback controls in a notification

### ISSUE THREAD

**Issue by hewiofhiowa** [Malopieds/InnerTune#216]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want to be able to control audio playback through a notification, as this will be easier than opening the app.

### Why do you want this feature?

My phone has stupid software so I can't use the media controls built in to the skin to control the music, with the controls only working with the company's stupid proprietary spyware music app.

**Comment by Malopieds** [comment]
What do you mean? There already is a notifcation?

**Comment by Malopieds** [comment]
Closing it. Feel free to re-open if you think I missed something.

**Comment by hewiofhiowa** [comment]
I just needed to enable the notification permission. Would be nice if the app asked for the permission at install.
