### ISSUE TITLE
Option to revert Player UI button contrast 

### ISSUE THREAD

**Issue by asherdenno** [Malopieds/InnerTune#218]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The Appearance section of settings should contain an item described as something along the lines of "High-contrast buttons" (for Player UI). Toggling this switches between the more muted button design and more vibrant higher contrast IconButtons.

### Why do you want this feature?

In the most recent 0.5.8 update, a couple of useful tweaks were added to the Player UI screen, notably the redesigned time bar as well as gradient support. One other smaller change was the adjustment from subtle tones for the IconButtons to the much more vibrant primary colour. Although I can see the merit in this change in the way of accessibility (it is undeniably easier to see the buttons + icons), I personally find the design distasteful. The muted icons provided a cleaner look drawing less attention to the controls and letting the album art pop. The colour balance in general just feels a little off to me. As a result of the increased contrast of some buttons, others like the skip button fade into the background even more so. I'm not saying this is everyone's opinion, I have asked some people who have preferred the new design. However, I do feel as though one could have easily added an option to revert back to the older design, in a similar way to have the gradient is toggeable.

**Comment by mostafaalagamy** [comment]
+ I also find it good to remove the bottom queue part because it appears strange during the gradient run and the button colors sometimes differ from the background.

![Screenshot_2024-07-13-02-21-01-999_com.malopieds.innertune-edit.jpg](https://github.com/user-attachments/assets/42e2e590-56f6-4d33-bd73-7fcf8dc9f63c)
