### ISSUE TITLE
option to crop video thumbnails to squares

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#219]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

an option that crops the video thumbnails into squares (center) rather than rectangles

### Why do you want this feature?

most music reuploads on youtube include the cover in the center, a way to crop it into a square would be good and would be consistent with the rest of the ui

**Comment by Username1-a** [comment]
And in addition to that option, current video thumbnail layout needs tweaking – it still cuts a lot of thumbnail image even if both video thumbnail on YouTube and thumbnail shape in InnerTune appears to be same 16x9 rectangular shape layout

Here's an example (you can see the text more cut off in InnerTune thumbnail):
![Screenshot_20240722-041704_Evolution X Launcher](https://github.com/user-attachments/assets/036ebad4-d570-4544-adf0-c9211ede45e6)
![Screenshot_20240722-042704_Evolution X Launcher](https://github.com/user-attachments/assets/f75b3c51-5414-4f97-856a-93b05aca5659)

**Comment by zettaexa** [comment]
bummping that
