### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by filinux13** [Malopieds/InnerTune#22]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Discord RPC using Kizzy Api like SpMp.

### Why do you want this feature?

I was using Kizzy to have discord rpc and it worked, but sometimes kizzy closed and it stoped working. And it would be nice to incorporate it on the app.
![Screenshot_2024-03-26-12-24-18-590_com toasterofbread spmp](https://github.com/Malopieds/InnerTune/assets/131296086/4a3764e2-3ce8-4b7b-b9eb-4592be8d7ff3)

**Comment by Malopieds** [comment]
It can be a cool feature but I don't want this project to be "too much" and keep things simple. We'll see in the future.

**Comment by Malopieds** [comment]
I checked out the kizzy project. I like it but I don't understand why not using their app to link your discord account and innertune? It's totally doable. What are the pros about having it in innertune?
I think it's the same scope as Last.fm scrobbling and we should let the external app deal with it, it's their job after all!

**Comment by fanieko** [comment]
> I checked out the kizzy project. I like it but I don't understand why not using their app to link your discord account and innertune? It's totally doable. What are the pros about having it in innertune?

I actualy do that 😂
I was asking to incorporate in the app bcs kizzy sometimes just stops and closes, if it was incorporated it wouldn't just randomly stop..
