### ISSUE TITLE
Add Musixmatch lyrics provider

### ISSUE THREAD

**Issue by iswac** [Malopieds/InnerTune#221]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [x] The title of this issue accurately describes the feature request.

### Feature description

Musixmatch has a awesome library for lyrics. So adding this can be increase listening quality.

### Why do you want this feature?

Unfortunately KuGou and LrcLib are not good enough for lyrics. Lyrics are not available for most songs.

**Comment by Malopieds** [comment]
Well LrcLib uses data from musixmatch, do you have example where the lyrics is on musixmatch but not lrclib?

**Comment by iswac** [comment]
> Well LrcLib uses data from musixmatch, do you have example where the lyrics is on musixmatch but not lrclib?

For example, [Softcore](https://music.youtube.com/watch?v=NIma5XOxBq0) has lyrics but not synced, just plain text available.
![Screenshot_20240718_230226_InnerTune.png](https://github.com/user-attachments/assets/0c1e9dd7-708b-45fa-b150-461ea2ba2a61)

But on YT Music, it has real-time synchronized lyrics:
![Screenshot_20240718_225921_YouTube Music.png](https://github.com/user-attachments/assets/da133185-b231-4c5d-bae2-a984cbc3e4a0)

**Comment by szaszlyki21** [comment]
The synced lyrics are available for the song, just for some reason it defaults to plain version.(you can choose other versions using the 3 dots while in lyric view) Lrclib has multiple versions of lyrics for each song and there may be diffrences between them as the are also made by individuals, not just scraped from other sources. You can contribute lyrics yourself using the lrcget app.
![Screenshot_20240719-144938_InnerTune](https://github.com/user-attachments/assets/4d54114f-5caa-4db7-bed2-5b47a5afba55)

**Comment by Malopieds** [comment]
Yes, you can always find more with the 3 dots, so closing this.

**Comment by furkansa50** [comment]
Maybe for show translated lyrics (like [SimpMusic](https://github.com/maxrave-dev/SimpMusic?tab=readme-ov-file))
