### ISSUE TITLE
Don't backup downloaded songs on backups using Android's backup API

### ISSUE THREAD

**Issue by lucasmz-dev** [Malopieds/InnerTune#226]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

*This is not about the backup/restore functionality in-app. This is about how the app interacts with backup solutions such as **Seedvault** or even the backup solution included in GApps.*

Ideally, I believe InnerTune should not backup downloaded songs, if possible.

### Why do you want this feature?

Downloads are relatively quick, as well as use a bunch of storage. I don't need to *backup* that, I only need to backup the songs, not their audio files. I'd like for Seedvault to be able to basically get an equivalent of what backup functionality already is in-app, but without containing the downloaded songs.

It'd also mean it'd be possible to use Seedvault here and have it manage things automatically, instead of having to worry about whether the backup file is up to date or not.

**Comment by lucasmz-dev** [comment]
According to a Seedvault dev, Gapps has a 25MB limit backup. So most likely InnerTune backups just wouldn't work with it. Seedvault has a limit of 50, but has the option of allowing unlimited storage. Device-to-device backup transfers might work on GApps, just that probably though.

**Comment by lucasmz-dev** [comment]
This was addressed upstream and it seems like the relevant commits have been migrated here. I'll do a test soon.

**Comment by Malopieds** [comment]
Yes sorry, I wanted to ping you. Please tell me!

**Comment by lucasmz-dev** [comment]
@Malopieds Seems to work! 0.5.9 doesn't include it as it was launched before, but after compiling a debug apk, seems to work fine, and uses 665kB of data to me, after importing a YT Music public playlist and then downloading. App data says 800MB, while Seedvault reports 665kB of data backed up.

Restoring seems to work, playlist is there again, and previously downloaded files are not marked as downloaded. Nice!

**Comment by lucasmz-dev** [comment]
Fixed by 97b80a1972ad39afb21e696217ed833713e0d238, cc3bc038a36ad26eaf93c5d0bb3ab936455e5079, 45884c76a66bd2b08e28e637c64f6f49407a66bf, and d317e198034b3f297396e413562ab33890da5364.
