### ISSUE TITLE
the uncustom custom order

### ISSUE THREAD

**Issue by Nilsu11** [Malopieds/InnerTune#230]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I recently migrated from Zion Huang's innertune and noticed the custom order in liked songs being 1. Not customizable and 2nd the descending order of date added as custom order

### Expected behavior

A customizable custom order in liked songs and downloaded songs (or don't display it)

### Actual behavior

No way to customize the order

### Logs

It isn't a crash so no logs needed I guess

### InnerTune version

0.5.8

### Android version

LineageOS 21 -> android 14

### Additional information

Please ask for more details

**Comment by Malopieds** [comment]
I've removed them since (for now) auto playlists are not playlists, therefore not in the database and thus cannot be sorted to custom. It might change in the future, in this case the custom order will be re implemented.
