### ISSUE TITLE
Gradient theme

### ISSUE THREAD

**Issue by Logan7899** [Malopieds/InnerTune#231]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Kudos to the dev for adding gradient but gradient is inconsistent as it is light gradient in dsrk mode and the queue just separates out

### Why do you want this feature?

Because in low light conditions at night the light gradient just feels like a slap on the face so please add dark gradient for dark mode

**Comment by d4f5409d** [comment]
Would be even better if the whole app had a gradient! Home screen, nav bar, song bar

**Comment by Logan7899** [comment]
> Would be even better if the whole app had a gradient! Home screen, nav bar, song bar

Sound good ngl

**Comment by ghost** [comment]
Gradient using accent color. Do not use thumbnail color if thumbnail color extraction is off 😄 . The different colors are burning my eyes.
