### ISSUE TITLE
Swipe  left/right gesture sensibility too high in queue

### ISSUE THREAD

**Issue by Richard38907** [Malopieds/InnerTune#240]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When I wanna go to the bottom of the songs queue, it sometimes swipes right or left to clear a song in queue instead of going down. This wrong action can easily be caused by mistake.

### Why do you want this feature?

Easier to navigate in queue section.

Suggestion

Disable the right/left gesture and replace it by an option in a menu (like Spotify)
Or reduce right/left sensibility on this page

https://github.com/user-attachments/assets/cc0de985-3a8c-4804-9bbd-01cc12a15843

**Comment by Richard38907** [comment]
Spotify uses this method:

![Screenshot_20240718-141958.png](https://github.com/user-attachments/assets/fe864600-6a15-414a-8df4-f98da04a6a6c)

**Comment by Richard38907** [comment]
You can just keep this existing option for that:

![Screenshot_20240718-142850.png](https://github.com/user-attachments/assets/e7e769f9-7690-4da1-94fd-d0ce522ab17a)

**Comment by Malopieds** [comment]
What about just a lock to prevent this?

**Comment by Richard38907** [comment]
It sounds good🤔, can you give me an example or an an example of an app that has already implemented your idea?

**Comment by Malopieds** [comment]
Exact same behavior from the playlist page.

**Comment by Richard38907** [comment]
Perfect👌.
