### ISSUE TITLE
Russian language mistake

### ISSUE THREAD

**Issue by Derpachi** [Malopieds/InnerTune#242]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to album
2. look at the play button

### Expected behavior

It should be "Воспроизвести"

### Actual behavior

Now it "Воспоизвести"

### Screenshots/Screen recordings

![Screenshot_20240719-210359](https://github.com/user-attachments/assets/636e1bbf-b6de-4a95-95f3-a452e806788d)

### Logs

None

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by Malopieds** [comment]
You can do a PR to fix that if you want!
