### ISSUE TITLE
Create playlist in Downloaded

### ISSUE THREAD

**Issue by Sunilr001** [Malopieds/InnerTune#243]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Create playlist in Downloaded, because we Download multiple songs with different genres and moods, so it is  good to listen one type of genres in one time, right now its Hotchpotch.

### Why do you want this feature?

good to listen one type of genres in one time.

**Comment by Malopieds** [comment]
Then just create a playlist a download it?
