### ISSUE TITLE
custom playlist images 

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#247]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

playlists in innertune to have a custom image as its thumbnail rather than an automatically generated one

### Why do you want this feature?

every other music streamer has it why not innertune

**Comment by Malopieds** [comment]
Won't do.

> every other music streamer has it why not innertune

Don't want to deal with infernal stuff that can easily breaks and ask a lot of time for implementing it.
