### ISSUE TITLE
Mistouch prevention features

### ISSUE THREAD

**Issue by futureisfoss** [Malopieds/InnerTune#248]
1. I have accidentally swiped off songs from the queue many times before, would be nice if there was a confirmation popup, or an undo button to reverse the change like you get when swiping off songs from a local playlist. (related issue: #240)

2. Accidentally touching on the lines of a synchronised lyric will skip the song to that position, would be nice to have a simple confirmation dialog before skipping the song, or an option in the settings to disable this feature entirely.

**Comment by Malopieds** [comment]
> an undo button

Will be an undo button rather than a confirmation dialog.

2 is the whole point of sync lyrics, there won't be any confirmation dialog and I don't see why one would want that? Maybe an option but we'll see

**Comment by futureisfoss** [comment]
1. An undo button is fine by me 🙂

2. I mainly use the synced lyrics to sing along to songs, not for skipping to specific parts of a song. Having an option in the settings to disable skipping would be nice.
