### ISSUE TITLE
Show song thumbnails in "My Top 50"

### ISSUE THREAD

**Issue by futureisfoss** [Malopieds/InnerTune#250]
There are numbers now where there used to be song thumbnails in "My Top 50". Would it be possible to move the numbers to the left and show thumbnails beside it?

**Comment by Malopieds** [comment]
They were never thumbnail (or at least wasn't intentional. It will stay as is since it's an ordered list

**Comment by futureisfoss** [comment]
Okay maybe I was misremembering things, but having thumbnails beside the song would allow me to spot it easily, we don't have to remove the numbers we can have both.

But if that's too much work I understand, this isn't a deal breaker. Thank you for keeping the project alive 🙂👍
