### ISSUE TITLE
Sync local history with YouTube Music

### ISSUE THREAD

**Issue by Covkie** [Malopieds/InnerTune#253]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Display history from your YouTube Music account in the history menu and sync history entries to YouTube Music

### Why do you want this feature?

Makes tracking desktop and mobile history seamless.

### Additional information

issue on old repo https://github.com/z-huang/InnerTune/issues/1259

**Comment by pdimu** [comment]
need this. in this way i can listen to all i have on innertune while on desktop with yt music and it would be cross-platform

**Comment by Malopieds** [comment]
I don't think I will do this. That is too much of work in my opinion. If someone implement it I will gladly look at their pull request !

**Comment by pdimu** [comment]
> I don't think I will do this. That is too much of work in my opinion. If someone implement it I will gladly look at their pull request !

i'll look up on google on how to make a widget. is this style good? 
![image](https://github.com/user-attachments/assets/94fdd41f-8e7a-40ef-a7dc-42a484bb1991)
or do i need to make it as a miniplayer?

**Comment by Malopieds** [comment]
Wrong issue I think? This is not related to this issue. But yeah the widget also would be cool to have a PR. For what people are waiting post it in the right issue to have more feedback!

**Comment by pdimu** [comment]
ah fk. i thought i'm on the widget issue. sorry, i can't make the innertune history to sync, but i'll try my best on the widget. also, the widget issue was #179

**Comment by Malopieds** [comment]
Following everything on #15
