### ISSUE TITLE
Add a search bar for each playlist

### ISSUE THREAD

**Issue by Richard38907** [Malopieds/InnerTune#259]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add a search bar on each playlist like Spotify to quickly find a song and filter results.

### Why do you want this feature?

Finding a song in each playlist instead of all playlists on my library.

**Comment by Richard38907** [comment]
Already implemented in this fork: https://github.com/Arturo254/InnerTune/releases
![Screenshot_20240725-132641_InnerTune.png](https://github.com/user-attachments/assets/8b2db9bf-94cb-4b30-806e-a57bd6ce9af7)

It will be nice.

**Comment by AlessandroGalvan** [comment]
@Malopieds i created the searchbar in the fork so i give you the authorization to copy the code 😊
