### ISSUE TITLE
Backup/Restore compatibility with original Innertune

### ISSUE THREAD

**Issue by BlastboomStrice** [Malopieds/InnerTune#269]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like an option to create backups that are compatible with the original Innertune (or somehow the backups created to be compatible with the other app).
If I create a backup from the forked Innertune and restore it on the original Innertune, the original Innertune crashes. (The reverse is possible, I can import backups on this app from the original Innertune.)

### Why do you want this feature?

It would give some peace of mind if it would be possible to restore backups from this app on the original app, in case I want to go back. It held me previously from using this fork.

### Additional information

Running Android 13, HyperOS 1, Xiaomi Mi 10
I don't consider this a bug, as I don't think it was ever intended for this to work. So I'm suggesting it as a feature.
Thank you for maintaining this fork, it looks better than the original app :)

**Comment by Malopieds** [comment]
Please see [this](https://github.com/z-huang/InnerTune/discussions/1310#discussioncomment-10268662).
