### ISSUE TITLE
Additional/Better Lyrics Source

### ISSUE THREAD

**Issue by SiddhantRakh** [Malopieds/InnerTune#27]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

 Support for 'Irclib.net' as the lyrics provider. 

### Why do you want this feature?

Kuguo's lyrics are great for English songs, but lack foreign language support like Hindi. Lrclib.net provides lyrics for a wider range of languages in apps like ViTune. This would improve the lyrics experience in InnerTune's excellent lyrics UI.

**Comment by Malopieds** [comment]
I didn't knew about [Lrclib.net](lrclib.net). I'll definitely look closer to it !

**Comment by SiddhantRakh** [comment]
> I didn't knew about [Lrclib.net](lrclib.net). I'll definitely look closer to it !

Thanks! I hope it's implemented soon, as it would fix a major issue where I have to import synced lyrics for about half of my library songs.

**Comment by SiddhantRakh** [comment]
Hey I heard you are going to release a stable build soon. Is that stable build going to include lrclib.net as the lyrics source?

**Comment by Malopieds** [comment]
No, this release will be focusing on the new UI. I haven't really looked at how I could implement the lrclib's lyrics as of now.
I'm thinking about doing weekly pseudo-stable release since this project is stable on its root but a lot of new features are coming every day.

**Comment by SiddhantRakh** [comment]
Ok. No problem. I just got a little bit excited.

**Comment by SiddhantRakh** [comment]
Is there any update on this because the lyrics experience has gotten really worse and I'm not able to see synced lyrics of any song now.

**Comment by Malopieds** [comment]
No, I know what caused it, but we need to have that line of code for android 14 and more given permissions. In addition it works pretty well in debug mode but not in release, I just have no idea right now. I'll try a complete rewrite of the Kugou but not sure that will change a lot...

**Comment by SiddhantRakh** [comment]
I don't know whether it's helpful but ViTune has the best working lyrics database I have tested and it is a very similar app to Innertune. Maybe you can take a look at how ViTune has done it. Also ViTune uses lrclib.net so it the same might be implemented in InnerTune.

**Comment by Malopieds** [comment]
Yep, that's what I did in the end. Should be implemented now. I'll push it before EOD. I think I will do a pre release tomorrow.

**Comment by SiddhantRakh** [comment]
There's a small UI glitch as there appears to be a space inserted at the start of each line of the lyrics sourced from Lrclib.net. Here's a screenshot to demonstrate:

![Screenshot_20240411-180349_InnerTune Debug](https://github.com/Malopieds/InnerTune/assets/42494931/0d5d6bca-5772-427e-9b76-cd265ef50ac3)

The lyrics work great and better than I expected.
Thanks for addressing my main issue with this app. It would be even great if this small UI glitch is fixed before tomorrow's pre-release. Thanks again 👍

Also we can remove or rename the options which says use Kuguo lyrics provider form settings. This is just my opinion btw.

**Comment by Malopieds** [comment]
> There's a small UI glitch as there appears to be a space inserted at the start of each line of the lyrics sourced from Lrclib.net. Here's a screenshot to demonstrate:

Should be now fixed. I'll push later.

> Also we can remove or rename the options which says use Kuguo lyrics provider form settings. This is just my opinion btw.

I mean it's still nice to let the user decide whether he wants to use a service or not. But maybe I can add an option for lrclib.

**Comment by SiddhantRakh** [comment]
>I mean it's still nice to let the user decide whether he wants to use a service or not. But maybe I can add an option for lrclib.

Yes. I was preferring for an option too. 👍
I am really excited to try out the new pre-release. Thanks for this well needed update.
