### ISSUE TITLE
Equalizer Not Working 

### ISSUE THREAD

**Issue by primelemma** [Malopieds/InnerTune#273]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

On playing now panel open 3dot button the we select Equalizer and it doesn't respond anything 

### Expected behavior

Open a Equalizer 

### Actual behavior

Equalizer doesn't open

### Logs

It's nothing 

### InnerTune version

0.5.3

### Android version

Android 14

**Comment by Richard38907** [comment]
Are you really on 0.5.3? You can update your app to 0.5.8 first and test it.

**Comment by Malopieds** [comment]
I haven't changed anything on that side so it should work. Does it works for other music apps?
But yeah try it on latest version, it's always better !

**Comment by primelemma** [comment]
Yes it work for other music apps

**Comment by primelemma** [comment]
Its 0.5.8

**Comment by Malopieds** [comment]
Could you get logs? It works fine for me.

**Comment by Richard38907** [comment]
Which equalizer do you use?
I installed Wavelet (for example) and it works perfectly for me.

**Comment by Malopieds** [comment]
Closing for no answers. Feel free to reopen with more information if it's still happening.
