### ISSUE TITLE
Error in YT Music playlists "similar"

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#28]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Some songs sometimes appear in this way, where they open as if they're an artist and keep loading endlessly, often showing up in the "Similar Songs" section.

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/f2f2991a-a420-4c62-8b6f-0be1d0483232

### Logs

No

### InnerTune version

0.5.5 debug version

### Android version

11 and 15

**Comment by Malopieds** [comment]
Ok, I see what's the issue here. The artist doesn't have any "Featured on" playlists from YouTube Music. Therefore it takes the videos from this artist... I might have a fix for that but I'm not sure that it won't break things up.

**Comment by mostafaalagamy** [comment]
> Ok, I see what's the issue here. The artist doesn't have any "Featured on" playlists from YouTube Music. Therefore it takes the videos from this artist... I might have a fix for that but I'm not sure that it won't break things up.

We can test that, and if a problem occurs, we will cancel the idea.

**Comment by Malopieds** [comment]
Hi, it *should* be fixed now, basically it shouldn't show any artists that doesn't have the "Featured on"

**Comment by mostafaalagamy** [comment]
The issue has recurred again.

![Screenshot_2024-04-19-03-18-03-15_83e681264c35b676874c1b7737da0359.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/eddcdf54-3eae-4a59-a5f6-08261cf3d753)

**Comment by Malopieds** [comment]
Which one is the problem here? Please send the name of album/artists so that I can copy it

**Comment by mostafaalagamy** [comment]
> Which one is the problem here? Please send the name of album/artists so that I can copy it

https://music.youtube.com/watch?v=-K0UIbx5W5Q 

" Amir Eid ft. Sedky Sakhr  - أنا نجم (Sahibet Al-Saada Session) "

**Comment by mostafaalagamy** [comment]
Reminder

**Comment by mostafaalagamy** [comment]
Did you find a solution to this issue?
