### ISSUE TITLE
release - topic

### ISSUE THREAD

**Issue by yant0** [Malopieds/InnerTune#283]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. search "Kekal 1000 Thoughts of Violence"
2. see album

### Expected behavior

should show artist's name

### Actual behavior

shows "Release - Topic"

### Screenshots/Screen recordings

![Screenshot_20240803-123802340](https://github.com/user-attachments/assets/c4ef68b3-91e3-428e-a47a-46fbfb9df2ff)

### Logs

-

### InnerTune version

4th latest debug

### Android version

android 11

**Comment by Malopieds** [comment]
This is the actual behavior of youtube music, this is out of my scope.
