### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [Malopieds/InnerTune#284]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)), but while I was able to successfully generate the APK using `./gradlew assembleRelease`, the resulting APKs have not been identical but showed several differences

### Expected behavior

APK Diff:

```diff
-------------------------------
--- /dev/fd/63  2024-07-16 18:57:14.538028309 +0200
+++ /dev/fd/62  2024-07-16 18:57:14.538028309 +0200
@@ -1,13 +1,13 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         bd71e113
   META-INF/version-control-info.textproto
-  32-bit CRC value (hex):                         bdcd45a0
+  32-bit CRC value (hex):                         636980de
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         4d85e9a4
+  32-bit CRC value (hex):                         783d548a
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         e7511fc2
   classes.dex
-  32-bit CRC value (hex):                         b72fb12e
+  32-bit CRC value (hex):                         1b91c653
   classes2.dex
   32-bit CRC value (hex):                         c2dd72b2
   lib/arm64-v8a/libdatastore_shared_counter.so
@@ -585,4 +585,4 @@
   res/zz.xml
   32-bit CRC value (hex):                         b8a463e9
   resources.arsc
-  32-bit CRC value (hex):                         0cb8c1ed
+  32-bit CRC value (hex):                         1c6939c8
```

### Actual behavior

Quite obviously, the APK was not built from the APK the tag points to. There's an embedded commit hash in `META-INF/version-control-info.textproto` which points to a commit that's not even found in the repo here, so you probably forgot to push the branch you built from:

```
fatal: reference is not a tree: 98eb7b0179870291326b2421cd09383e525ca145
```

### Logs

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

### InnerTune version

0.5.8

### Android version

n/a

### Additional information

Looking forward to your reply!

(PS: would be nice if you could also enable the "simple issue template" for cases like this, which do not fit well with either of the two templates enabled currently :wink:)

**Comment by IzzySoft** [comment]
I see there's a new release (v0.5.9) meanwhile. But it's still not RB:

```diff
-------------------------------
--- /dev/fd/63  2024-08-14 14:45:06.241424685 +0200
+++ /dev/fd/62  2024-08-14 14:45:06.245424658 +0200
@@ -3,11 +3,11 @@
   META-INF/version-control-info.textproto
   32-bit CRC value (hex):                         8ed1f81d
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         4e1d1c89
+  32-bit CRC value (hex):                         98b00c9e
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         fb59449a
   classes.dex
-  32-bit CRC value (hex):                         845e6f36
+  32-bit CRC value (hex):                         02c63fe1
   classes2.dex
   32-bit CRC value (hex):                         c2dd72b2
   lib/arm64-v8a/libandroidx.graphics.path.so
```

Dex diff is huge. As there's no response from your side, @Malopieds: are you interested in achieving RB at all, or shall we just give up on it for your app?

**Comment by Malopieds** [comment]
Yes, sorry I wanted to ping you when I did this. I added the commit from z-huang repo to disable crunch pngs and built from the same commit the tag points to so I don't understand :/

**Comment by IzzySoft** [comment]
Strange indeed then. But z-huang shows 0.5.6 here as latest release, yours is at 0.5.9, so it might well be something else you've changed. You sure the APK was built from a clean tree at the commit the tag points to? What are you building with (Android Studio, commandline, …)? If Studio: Do you run "clean" before building?

**Comment by Malopieds** [comment]
> You sure the APK was built from a clean tree at the commit the tag points to

Yeah I mean I commit tag then push and finally build.

> Do you run "clean" before building?

No, would it change something?

**Comment by IzzySoft** [comment]
> No, would it change something?

Oh yeah, definitely! If you don't run "clean", Studio re-uses old "artifacts" (from previous builds) – which are not present in a "virgin container" as it's used for the RB builds. That's fine for your test builds (as those builds complete faster) – but for the "release builds" you should always "clean project" first.

I've linked to our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) above, see the section on "Clean Builds" there for details (and follow up the link to the example there).

**Comment by IzzySoft** [comment]
Congrats :partying_face: v0.5.10 was just confirmed to be reproducible – so we can close this issue here. Hope the icon issue (#212) will be solved soon as well :wink: Until then, a [welcome toot for you](https://floss.social/@IzzyOnDroid/113421921863240276):

![image](https://github.com/user-attachments/assets/d507358e-d0d6-4faf-8e4a-f6f2e0b42801)

**Comment by IzzySoft** [comment]
@Malopieds 0.5.11 failed again. Looks like it was not built from a clean tree, as your APK contains files not in our build (and other files differ):

```diff
  -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 2209f481 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     5897 b-     5897 stor 1981-01-01 01:01:02 55a5e041 assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx     5897 b-     5897 stor 1981-01-01 01:01:02 e506d36a assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      805 b-      805 stor 1981-01-01 01:01:02 5e7ac18b assets/dexopt/baseline.profm
- -rw-r--r--  0.0 unx  6756416 b-  3165254 defN 1981-01-01 01:01:02 06aa859d classes.dex
+ -rw-r--r--  0.0 unx  6756416 b-  3165242 defN 1981-01-01 01:01:02 4b26cb79 classes.dex
  -rw-r--r--  0.0 unx   195984 b-    81900 defN 1981-01-01 01:01:02 21316a36 classes2.dex
  -rw-r--r--  0.0 unx    10096 b-    10096 stor 1981-01-01 01:01:02 9734baa0 lib/arm64-v8a/libandroidx.graphics.path.so
  -rw-r--r--  0.0 unx     7112 b-     7112 stor 1981-01-01 01:01:02 4f56ac38 lib/arm64-v8a/libdatastore_shared_counter.so
@@ -231,7 +231,7 @@
  -rw----     0.0 fat     1315 b-     1315 stor 1981-01-01 01:01:02 11edb2a6 res/9P.png
  -rw----     0.0 fat      652 b-      342 defN 1981-01-01 01:01:02 53064050 res/9Y.xml
  -rw----     0.0 fat      323 b-      323 stor 1981-01-01 01:01:02 d7cbec47 res/9a.png
- -rw----     0.0 fat      304 b-      174 defN 1981-01-01 01:01:02 e70015ca res/9m.xml
+ -rw----     0.0 fat      304 b-      174 defN 1981-01-01 01:01:02 490b465e res/9m.xml
  -rw----     0.0 fat      167 b-      167 stor 1981-01-01 01:01:02 4f446c94 res/9v.png
  -rw----     0.0 fat     1213 b-     1213 stor 1981-01-01 01:01:02 a38377f0 res/A5.png
  -rw----     0.0 fat      295 b-      295 stor 1981-01-01 01:01:02 b2e56c94 res/A6.png
@@ -340,7 +340,7 @@
  -rw----     0.0 fat      554 b-      554 stor 1981-01-01 01:01:02 127323cf res/Jx.png
  -rw----     0.0 fat      652 b-      326 defN 1981-01-01 01:01:02 1b424139 res/K1.xml
  -rw----     0.0 fat      153 b-      153 stor 1981-01-01 01:01:02 2b6a9c2e res/K7.png
- -rw----     0.0 fat     1436 b-      527 defN 1981-01-01 01:01:02 dd12a972 res/K7.xml
+ -rw----     0.0 fat     1436 b-      527 defN 1981-01-01 01:01:02 471d6d54 res/K7.xml
  -rw----     0.0 fat     1292 b-     1292 stor 1981-01-01 01:01:02 de15d6da res/K71.png
  -rw----     0.0 fat      889 b-      889 stor 1981-01-01 01:01:02 18df361d res/K8.png
  -rw----     0.0 fat      757 b-      757 stor 1981-01-01 01:01:02 2b8cf672 res/KE.png
@@ -554,7 +554,7 @@
  -rw----     0.0 fat      876 b-      461 defN 1981-01-01 01:01:02 512a8fde res/dY.xml
  -rw----     0.0 fat      281 b-      281 stor 1981-01-01 01:01:02 ab3835af res/db.png
  -rw----     0.0 fat      178 b-      178 stor 1981-01-01 01:01:02 68b215e7 res/db1.png
- -rw----     0.0 fat      532 b-      253 defN 1981-01-01 01:01:02 5c19f48a res/df.xml
+ -rw----     0.0 fat      532 b-      253 defN 1981-01-01 01:01:02 4fb491d4 res/df.xml
  -rw----     0.0 fat      482 b-      482 stor 1981-01-01 01:01:02 fa09c238 res/eA.png
  -rw----     0.0 fat     1250 b-     1250 stor 1981-01-01 01:01:02 7c3203d8 res/eB.png
  -rw----     0.0 fat      744 b-      384 defN 1981-01-01 01:01:02 eb7d88a9 res/eO.xml
@@ -674,7 +674,7 @@
  -rw----     0.0 fat     1216 b-      548 defN 1981-01-01 01:01:02 589b4a46 res/nb.xml
  -rw----     0.0 fat      192 b-      192 stor 1981-01-01 01:01:02 a8bae740 res/ni.png
  -rw----     0.0 fat      144 b-      144 stor 1981-01-01 01:01:02 b556a73a res/nr.png
- -rw----     0.0 fat      532 b-      253 defN 1981-01-01 01:01:02 6de50ca6 res/nz.xml
+ -rw----     0.0 fat      532 b-      253 defN 1981-01-01 01:01:02 c3a97e03 res/nz.xml
  -rw----     0.0 fat      884 b-      469 defN 1981-01-01 01:01:02 95ccd82f res/oH.xml
  -rw----     0.0 fat      491 b-      491 stor 1981-01-01 01:01:02 f2216ffe res/oS.png
  -rw----     0.0 fat      169 b-      169 stor 1981-01-01 01:01:02 37c51a62 res/oZ.png
@@ -805,7 +805,6 @@
  -rw----     0.0 fat     1144 b-      567 defN 1981-01-01 01:01:02 a1a8743e res/yG.xml
  -rw----     0.0 fat      458 b-      458 stor 1981-01-01 01:01:02 811d3cb9 res/yK.png
  -rw----     0.0 fat      129 b-      129 stor 1981-01-01 01:01:02 2d74ba26 res/yM.png
- -rw----     0.0 fat    41088 b-    12909 defN 1981-01-01 01:01:02 fb11e0d6 res/y_.xml
  -rw----     0.0 fat      552 b-      552 stor 1981-01-01 01:01:02 2f71af9f res/yt.png
  -rw----     0.0 fat     1580 b-     1580 stor 1981-01-01 01:01:02 9f1268d5 res/yw.webp
  -rw----     0.0 fat      327 b-      327 stor 1981-01-01 01:01:02 4b247dc5 res/yy.png
@@ -825,5 +824,5 @@
  -rw----     0.0 fat      249 b-      249 stor 1981-01-01 01:01:02 72a34e93 res/zv.png
  -rw----     0.0 fat      435 b-      435 stor 1981-01-01 01:01:02 cc705e7f res/zz.png
  -rw----     0.0 fat      564 b-      211 defN 1981-01-01 01:01:02 b8a463e9 res/zz.xml
- -rw----     0.0 fat   714516 b-   714516 stor 1981-01-01 01:01:02 a3f08faf resources.arsc
+ -rw----     0.0 fat   714440 b-   714440 stor 1981-01-01 01:01:02 d3ab9e8d resources.arsc
```

`res/y_.xml` is only contained in your build, so it's not available in the repo at the tagged commit.

How did you build? Was it a clean tree (no local changes, no left-over artifacts) at the tagged commit?

**Comment by Malopieds** [comment]
Erf... This is weird, I used clean button in android studio before building... There maybe was some artefact but maybe just a python script that was never added to to the repo, but no xml files. Could that have been something altering?

**Comment by Malopieds** [comment]
Also, would a ci build and release on tags push would be a workaround?

**Comment by IzzySoft** [comment]
The CI build would guarantee a "clean tree" AFAIK, so it's definitely worth a try. You could also try building from CLI manually, your build recipe is pretty easy:

    ./gradlew clean assembleRelease --no-build-cache --no-configuration-cache --no-daemon

should give you a pretty clean build. If you sign that with the same key, you could run `sha256sum *apk` and the hashes shown should be identical – or in case of the current APK rather not :see_no_evil: For the current release the hash should then be `57e2134316a295504020252c4fe6b00ce663c999a720a81a100eefc5e0b7a3c7` (that was what I ended up with here, while yours has `aea3e5e1058da3c244a4c2c1d392f77d58029935aeca5320ccec8d0c1ec63a4d`). Or run that on the unsigned APK: `aecb0274af2945a9f1fcd913c72d6a5ef605b20385d1168d297bbc1c5d9420e9` for 0.5.11 here.

I bet the XMLs are generated at build time from something. They are present in your build and in mine, they just differ (and I have no idea why). Those are Android bitmaps. And they were present in the previous release APK as well.

**Comment by Malopieds** [comment]
Ok f... That's my bad on this, forgot to push one xml file that was not there previously though I don't know why the CI didn't failed for this one... I don't really use intellij's product, AS is the only one and I often use the cli and neovim for other projects, I should stick with the cli, that's the only thing that won't fail me x)
Anyway, I will surely setup a CI build and release for this when I have the time, that would be less error-prone. Once again sorry for the inconvenience x)

**Comment by IzzySoft** [comment]
> I should stick with the cli, that's the only thing that won't fail me x)

Hehe, not the worst choice. Works for me as well :see_no_evil:

And yeah, happens. Just ring my bell if you need me to make a test run e.g. before the next release.
