### ISSUE TITLE
Publish as new app

### ISSUE THREAD

**Issue by W1zardK1ng** [Malopieds/InnerTune#29]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

We are still not sure whether the [InnerTune](https://github.com/z-huang/InnerTune) is dead, the dev may comeback at anytime. So its ideal to publish this fork with new app and package name.

### Why do you want this feature?

Its nice to have the app has its own and and package name instead using the same as original and making changes.

**Comment by Malopieds** [comment]
Yep it can be a good idea, I currently don't have any name idea but that's something we can think of !

**Comment by mostafaalagamy** [comment]
> Yep it can be a good idea, I currently don't have any name idea but that's something we can think of !

If you need help with the name and logo, I can assist with that.

**Comment by fanieko** [comment]
Yes i would like it, i want to try this app without uninstalling the main one.

I think maybe zhuang will come back on summer vacation as it was in august that he was more active on github.

**Comment by W1zardK1ng** [comment]
Will be nice to get everyone's ideas in the [discussion (Suggestions for the new app name)](https://github.com/Malopieds/InnerTune/discussions/34) section.

**Comment by Malopieds** [comment]
Hi all, that would be great to have a new name and a new icon for v0.6.0. I haven't really found a name app that suits well. Also a new icon would be cool. If anyone has propositions!

**Comment by shuvashish76** [comment]
@Malopieds For icon you can take a look at svg files at https://openclipart.org/ , modify them according to your choice and make your own icon :)
All the files are [CC0 1.0 license](https://creativecommons.org/publicdomain/zero/1.0/) :)

Or simply just use one of them, for example : https://openclipart.org/detail/5484/music-from-egg

**Comment by Malopieds** [comment]
From now on there is a new logo and a new package name so this a new app !
