### ISSUE TITLE
Bug radio queue not working

### ISSUE THREAD

**Issue by Richard38907** [Malopieds/InnerTune#291]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Probably due to a YouTube API change, "start radio" is not working. It only plays the first song and provides an empty queue.

### Expected behavior

The queue should show next songs from the radio

### Actual behavior

Empty queue after selected title 

### Screenshots/Screen recordings

![Screenshot_20240809-130735_InnerTune](https://github.com/user-attachments/assets/4b4d21a9-61c3-41c9-851f-28127233de29)
![Screenshot_20240809-130740_InnerTune](https://github.com/user-attachments/assets/5cfaae06-29d0-4e9a-9d29-839c9005f3a5)

### Logs

[logcat.txt](https://github.com/user-attachments/files/16560446/logcat.txt)

### InnerTune version

0.5.8, z-Huang and other forks

### Android version

Android 9, 13 and 14

**Comment by Malopieds** [comment]
Yep, I noticed it this morning, must be youtube changes...

**Comment by BluePixel4k** [comment]
@Malopieds could you please push a new release with this fix? Thank you! :)

**Comment by Malopieds** [comment]
Yep, beginning of next week.
