### ISSUE TITLE
Produce orignal InnerTune compatible backups

### ISSUE THREAD

**Issue by gechoto** [Malopieds/InnerTune#293]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Backups made by this fork cannot be recovered in the original version. It crashes.
See: https://github.com/z-huang/InnerTune/issues/1340

I'm not sure which side is causing this and where is the best place to solve this but if it can't be fixed in the original version maybe this fork could provide a way to create compatible backups?

### Why do you want this feature?

I want to go back to the original version now that it is maintained again

**Comment by Malopieds** [comment]
[Duplicate](https://github.com/Malopieds/InnerTune/issues/269#issuecomment-2277399366)

**Comment by gechoto** [comment]
Of course I only searched open issues, damn. Sorry for the duplicate.
