### ISSUE TITLE
Quiks picks not working

### ISSUE THREAD

**Issue by Sunilr001** [Malopieds/InnerTune#295]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

.

### Expected behavior

It should randomly change the songs.

### Actual behavior

Quick picks not working,

### Screenshots/Screen recordings

![Screenshot_20240811_164524_InnerTune](https://github.com/user-attachments/assets/27a71a5c-0bfd-45ff-8a00-a3e44bc8add2)

### Logs

When we tap on quick picks icon, its play only one song l, auto play not working. I uninstall and install again but now nothing show in quick picks panel

### InnerTune version

O.5.8

### Android version

Android 13

**Comment by Malopieds** [comment]
Weird, it works for me, in addition you have other things based on what you listened. Could you send me your backup file?

**Comment by Sunilr001** [comment]
[InnerTune_20240811195726.zip](https://github.com/user-attachments/files/16574030/InnerTune_20240811195726.zip)

**Comment by Malopieds** [comment]
In the backup you provided, you listened to only one song, in addition the radio was broken. It would therefore be fix in the next release.
