### ISSUE TITLE
Add Widget

### ISSUE THREAD

**Issue by ZTechDev06** [Malopieds/InnerTune#297]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add widget play skip  ( YouTube music)

### Why do you want this feature?

Skip musicale play 

### Additional information

Add widget play pause ( YouTube music)

**Comment by Malopieds** [comment]
Duplicate of #179
