### ISSUE TITLE
Incorrect artist in youtube playlists with collaborators

### ISSUE THREAD

**Issue by Lambada10** [Malopieds/InnerTune#298]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- create a playlist on YouTube Music and add songs to it
- go to edit > collaborate and enable collaboration
- Log in to YouTube Music in the app
- go to account playlists

### Expected behavior

Songs should have their proper artists

### Actual behavior

The playlist collaborator is reported to be the artist of a song

### Screenshots/Screen recordings

![image](https://github.com/user-attachments/assets/9a30fbca-12af-4f33-b8b8-5e8b810eacfa)
![image](https://github.com/user-attachments/assets/20281eab-965d-41d8-8ab2-5c5e0a4d4806)
![image](https://github.com/user-attachments/assets/a8a242d4-ee84-4518-8afc-cba243b1b7f4)
![image](https://github.com/user-attachments/assets/6c866fa4-9009-43fd-b792-96695d440645)

### Logs

N/A

### InnerTune version

0.5.7 / 0.5.8 / debug (action 0e004c6)

### Android version

Android 14

**Comment by Malopieds** [comment]
It's actually because youtube music deals it the "same" way. Previously their wasn't the artists but there will always be collaborator, I cannot get rid of if.
