### ISSUE TITLE
Issues with material 3 colors 

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#299]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

There is a difference in colors when playing some songs on the original innertune and Malopieds innertune.

### Expected behavior

Original innertune 

![Screenshot_2024-08-13-13-53-54-948_com zionhuang music](https://github.com/user-attachments/assets/1503b8b8-7cb0-45d1-a4b1-69fb2024781c)

### Actual behavior

Malopieds innertune 

![Screenshot_2024-08-13-13-53-41-564_com malopieds innertune debug](https://github.com/user-attachments/assets/a9c030d8-96e9-4739-a5cc-1934ece63421)

### Screenshots/Screen recordings

![Screenshot_2024-08-13-13-45-24-588_com miui home](https://github.com/user-attachments/assets/cdfd2e31-30fd-4172-ab5a-b01cd7d48aa7)

### Logs

> 

### InnerTune version

debug version

### Android version

13

**Comment by Malopieds** [comment]
Yes it's from the art that is black and white, so it can't take the . Idk why it does that but we can take it as feature not a bug x)

It may be from the library that takes the color, I didn't update it exactly like original.

**Comment by mostafaalagamy** [comment]
> Yes it's from the art that is black and white, so it can't take the . Idk why it does that but we can take it as feature not a bug x)
> 
> It may be from the library that takes the color, I didn't update it exactly like original.

If it only happened with black and white, it would be a feature, but it happens randomly and strangely, like this.

![Screenshot_2024-08-13-14-12-14-658_com.miui.home.jpg](https://github.com/user-attachments/assets/b1f2f91e-a7d8-4ad6-b43f-016168696989)

**Comment by Malopieds** [comment]
Yeah that's indeed weird... I'll take a look.

**Comment by mostafaalagamy** [comment]
> Yeah that's indeed weird... I'll take a look.

Take your time
