### ISSUE TITLE
Quick picks based on last song played

### ISSUE THREAD

**Issue by siggi1984** [Malopieds/InnerTune#3]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Most of the time, the quick picks are not based on the last song played. It would be better if the quick picks were based on the last song played.

Even better would be a selection option like Harmony Music, see screenshot.
I think the quick picks are very successful.

### Why do you want this feature?

![295985709-ee4eeb19-1a2b-4062-95b6-4b0a41918073](https://github.com/Malopieds/InnerTune/assets/103368536/66b1da08-beeb-481a-8c6a-eff6a3f1fd18)

**Comment by Malopieds** [comment]
Hi, thank you for the idea, right now I will more focus on fixing bugs/improving UI, but if this gather a lot of reaction I'll implement it sooner !

**Comment by Malopieds** [comment]
Just to clarify, when you say "based on the last song played", you mean that you want the quick picks to be the last 20 songs you played, or a youtube music mix based on the last song you played ?

**Comment by siggi1984** [comment]
> Just to clarify, when you say "based on the last song played", you mean that you want the quick picks to be the last 20 songs you played, or a youtube music mix based on the last song you played ?

Youtube music mix based on the last song you played

**Comment by Malopieds** [comment]
After all this time, this is implemented ! We're almost ready to have the next stable release :)
Tell me if this is what you were expecting, you can change it in the settings => content
