### ISSUE TITLE
The artist's photo doesn't appear in library

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#300]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

The artist's photo doesn't appear in library , you need to open the artist section first for the photo to load, and then it will appear normally in library.

### Expected behavior

__

### Actual behavior

__

### Screenshots/Screen recordings

![Screenshot_2024-08-13-15-07-23-382_com malopieds innertune debug](https://github.com/user-attachments/assets/bcafd7a7-9b72-49f7-acd2-3ba0c5822664)

### Logs

__

### InnerTune version

debug version

### Android version

13

**Comment by Malopieds** [comment]
> you need to open the artist section

You mean the artist section in the library or the artist page ?

**Comment by mostafaalagamy** [comment]
> > you need to open the artist section
> 
> You mean the artist section in the library or the artist page ?

 I mean artist filter in library

**Comment by Malopieds** [comment]
Should be good like this

**Comment by mostafaalagamy** [comment]
> Should be good like this

Yep, thanks.
