### ISSUE TITLE
Bug with the dynamic theme

### ISSUE THREAD

**Issue by Ikari115** [Malopieds/InnerTune#305]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Activating the dynamic theme option changes the screen completely to dark, but it's not even because of the night mode 

### Expected behavior

Normal light and dark mode with dynamic mode

### Actual behavior

It goes to black completely and there is no legibility

### Screenshots/Screen recordings

![Screenshot_2024-08-13-14-00-25-286_com malopieds innertune](https://github.com/user-attachments/assets/86babd3d-ab13-41e7-b459-ac01f0ae6432)
![Screenshot_2024-08-13-14-00-42-623_com malopieds innertune](https://github.com/user-attachments/assets/1c56929f-00e2-414d-95d3-313d2379ff0a)
![Screenshot_2024-08-13-14-01-04-504_com malopieds innertune](https://github.com/user-attachments/assets/9b92b1b2-edf3-4aad-8000-72877cd2a21f)

### Logs

-

### InnerTune version

0.5.9

### Android version

Android 14

**Comment by Ikari115** [comment]
https://github.com/user-attachments/assets/ba524eaa-9c54-4a78-920f-e998278f84c4

**Comment by Malopieds** [comment]
Weird, you are using the pure black so the background is normal but it shouldn't be like that with the font. Does it happens with the original app? In addition you are using xiaomi phone? Isn't there a switch that forces dark theme in those? Is it on?

**Comment by Ikari115** [comment]
> Weird, you are using the pure black so the background is normal but it shouldn't be like that with the font. Does it happens with the original app? In addition you are using xiaomi phone? Isn't there a switch that forces dark theme in those? Is it on?

Apparently it has to do with the new pure dark mode, in the original app It also happens, but I don't have any option to force dark mode in apps, so... I suppose it has to do with something in the way the code activates it? Because it shouldn't change the font color

So... I guess there's no dynamic mode for me

**Comment by Malopieds** [comment]
What happens if you disable the pure black?

**Comment by Ikari115** [comment]
> What happens if you disable the pure black?

I just tried on a Samsung device (Android 13), and this doesn't happen, so it must have something to do with the Hyper OS system (Xiaomi), when activating pure black the font color goes completely dark and can't be read, it takes on dynamic colors

**Comment by Richard38907** [comment]
I have the glitch too on OnePlus nord (PE13 Rom) and OnePlus 10t (OxygenOS 14)
![Screenshot_20240813-223855_InnerTune.png](https://github.com/user-attachments/assets/eb4e102d-d009-4983-ad97-9d9fe4f6e0e3)

**Comment by Ikari115** [comment]
@Malopieds I discovered something, when activating the gradient style in the player is that this problem is generated, the same thing just happened to me on the Samsung, I don't know that it has to do with the gradient background with the pure dark but there is the problem, And it doesn't matter if you return to the normal style since the problem remains

Another thing, I don't know if it's normal for pure black to remove the gradient effect on the player when it's in dark mode

**Comment by Malopieds** [comment]
Nope my guess is that you're using pure black with white theme (which for me seems odd). I'll see if I change this later or force the white theme even if pure black or the other way around.

**Comment by Username1-a** [comment]
Looks like a bug introduced in version 0.5.9

To replicate this,
1. Enable Dynamic theme toggle
2. Disable Dark theme (app should be in Light theme)
3. Enable Black theme toggle
4. Play some song

Here's some screenshots comparing 0.5.8 and 0.5.9:
![Screenshot_20240814-235222_Evolution X Launcher](https://github.com/user-attachments/assets/7f68a16b-573e-40e7-b356-23390fabeee0)
![Screenshot_20240814-235609_Evolution X Launcher](https://github.com/user-attachments/assets/b2da38b9-11fb-4a22-b2bd-c2629d82cc46)

P.S. Same bug with latest version 0.5.6 of the regular InnerTune (previous InnerTune 0.5.5 also doesn't have that bug)
