### ISSUE TITLE
Lyrics color issue, not visible with dark theme

### ISSUE THREAD

**Issue by MLZ94** [Malopieds/InnerTune#306]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play a musique with a dark cover 
Set the payer background to gradient
Show the lyrics

### Expected behavior

The lyrics to be bright on dark mode and dark in light mode

### Actual behavior

Seems to be the reverse, dark text on dark mode and bright text on light mode, which makes the text hard to read

### Screenshots/Screen recordings

![Screenshot_20240813-233903](https://github.com/user-attachments/assets/1920d7d9-8d9f-4dcd-bb72-2954ccbf83ff)
![Screenshot_20240813-233913](https://github.com/user-attachments/assets/c54125f3-e337-41db-ad62-5ee145c791f7)
![Screenshot_20240813-233845](https://github.com/user-attachments/assets/97bc3f0a-3413-4333-a09b-9f554f646c40)
![Screenshot_20240813-233840](https://github.com/user-attachments/assets/6f19a0ad-5302-44d8-a318-c77f460d45cd)

### Logs

Nothing to show in the logs

### InnerTune version

0.5.9

### Android version

Android 14 pixel 6 latest official update

### Additional information

First i want to thank you for your incrdible work on this app, this is the best looking music app by farrr
I attached two musics for exemple, in bright and dark mode. You can see the text color is hatd to read, especialy in dark mode.

**Comment by Ikari115** [comment]
Another thing, Lyrics are not clickable, they don't let you fast forward or slow down when you press on a specific line

**Comment by mostafaalagamy** [comment]
> Another thing, Lyrics are not clickable, they don't let you fast forward or slow down when you press on a specific line

Go to settings > Appearance > turn off and turn on again on 'change lyrics on click' button.
