### ISSUE TITLE
Library items need total count of items inside each folder

### ISSUE THREAD

**Issue by tomxposed** [Malopieds/InnerTune#309]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Display total count on each item in Library tab

### Why do you want this feature?

User can gef an overal idea of how much songs are inside

**Comment by Malopieds** [comment]
![image](https://github.com/user-attachments/assets/9c49581f-3df2-4f7e-bfdd-0e571e6e4016)
There is already this indication, could you be more precise or give me a screenshot for an example?
