### ISSUE TITLE
Inconsistent Liked Songs Sorting: Added Songs Appear Mid-List, Not Newest First 

### ISSUE THREAD

**Issue by Ahamed07** [Malopieds/InnerTune#310]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.Open the music streaming app.
2.Locate a song you want to like.
3.Tap the heart icon to like the song.
4.Navigate to the "Liked Songs" section in the library.
5.Observe that the liked song is added in the middle of the list, not at the top.

### Expected behavior

this should add to the top of the liked song in the library

### Actual behavior

Instead of adding it to the top it adds to the middle or the lower part of the list

### Logs

-

### InnerTune version

5.9

### Android version

Android 14

### Additional information

this was an issue in version 5.7 but fixed in 5.8 it happens again in version 5.9

**Comment by ThatOneCalculator** [comment]
Can reproduce. This is frankly unacceptable, a music app should be able to play music and save my songs in a list.

**Comment by Malopieds** [comment]
> This is frankly unacceptable

Who do you think you are? Not happy? The door isn't closed. Fix things yourself then.

**Comment by ThatOneCalculator** [comment]
You are the one who decided to hard-fork innertune.

**Comment by Malopieds** [comment]
And you are then one who decided to use it. I'm not making it for pleasing you and yes there will be bugs that how it is. I'll try my best to fix them but I need some time and this is ridiculous of you to think otherwise. I would have though better from someone who is as present in the open source community as you. Stop being toxic, you're the reason why some dev stop working on open source project. I don't owe you anything but the least you can do is owe me some respect.

**Comment by ThatOneCalculator** [comment]
If you think calling a basic mistake unacceptable (especially for an issue you introduced, didn't test, and packaged!) is "being toxic", you need to grow some thicker skin.

**Comment by Malopieds** [comment]
Yes error happens, but there is no point of behaving like you (which IS toxic, you, not calling whatever this mistake was). I agree with you on the fact that it is a rookie mistake and it flew under my radar but see, that's how you learn. But I don't see the point of acting like you are, that's childish and pitiful. I don't care about what you may think/say. As far as I'm concerned I'm doing this for me and you can use my app or not my life will go on.
Please stop wasting my time and stop polluting this comment section.
