### ISSUE TITLE
Logging in doesn't seem to do anything within the app aside from log me into YouTube on the in app browser that pops up when tapping "login"

### ISSUE THREAD

**Issue by theRealTrabo** [Malopieds/InnerTune#317]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When I go to settings, click content, click login, it opens an in app browser tab where I login to my Google account. The in app browser then takes me to the YouTube website where I am logged in. When I close the browser, nothing in the app itself seems to have changed. 

### Expected behavior

I believe there should be an account tab that appears where I can see my YT Music likes and saves, etc.

### Actual behavior

No account section shows anywhere, no playlists or liked music shows up or anything. I've tried this after reinstalling the latest version of the app and restarting the app several times. 

### Screenshots/Screen recordings

![Screenshot_20240815_012945_InnerTune](https://github.com/user-attachments/assets/0409ad79-fa76-49ac-ab61-6d38e3dc1e5c)
![Screenshot_20240815_012954_InnerTune](https://github.com/user-attachments/assets/b43ff6ce-0146-40a3-aaeb-29b264da5c34)
![Screenshot_20240815_013006_InnerTune](https://github.com/user-attachments/assets/9583074f-573a-4e46-8106-627dd41ba90a)

### Logs

I'm sorry, I'm not sure how to do this. I apologize if this report is not thorough enough as I am not a developer and I understand if I cannot have my issue remedied as a result.

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by Malopieds** [comment]
Show me the content settings, to see if you're a connected or not

**Comment by theRealTrabo** [comment]
![Screenshot_20240815_014346_InnerTune](https://github.com/user-attachments/assets/f186439e-7c48-4aa2-899d-9945bf144d37)

**Comment by Malopieds** [comment]
You're not logged in with the screenshot you provided. What happens after you logs in?

**Comment by theRealTrabo** [comment]
Nothing. That screenshot is after backing out of the login page. When I tap login again it just goes to the YouTube website on the in app browser with my account logged in there, like the screenshot in my original comment. The content screen doesn't change. I can log out from the website, close the browser tab and then login again and it just does the same thing each time. It's as if the app doesn't register the fact that I've logged in through the login page. Just to check, I cleared cache and tried the process with my VPN and private DNS turned off and it didn't react differently.

**Comment by BRBsoup** [comment]
This is a Google/YouTube change that is affecting many youtube apps. Either log-in or Switch User is not working as expected.

**Comment by theRealTrabo** [comment]
> This is a Google/YouTube change that is affecting many youtube apps. Either log-in or Switch User is not working as expected.

Is this a bug that devs will be able to address or is it a way for Google to crack down on these types of open source apps?

**Comment by theRealTrabo** [comment]
This may or may not be useful information, but I installed the original innertune app from which this one is forked to see if I had the same issue with that app and after trying all the same steps over there the issue persisted.

**Comment by Richard38907** [comment]
I tested now and it works fine for me. Weird...

**Comment by itsmeteddyhere** [comment]
I'm having the same issue

**Comment by Malopieds** [comment]
Just noticed it takes you to YouTube and not YouTube Music.

Same for [this](https://github.com/z-huang/InnerTune/issues/1391#issuecomment-2293750558)

> I'm having the same issue

Is it also the case for you, taking you to YouTube?

**Comment by itsmeteddyhere** [comment]
yup it opens the YouTube Homepage (which I'm pretty sure it did before too) but it doesn't actually log me into the app, but I stay logged in the login interface within the app so perhaps maybe the app just isn't detecting it or something?

**Comment by Malopieds** [comment]
Have you tried what the comment on the link said to do?

**Comment by itsmeteddyhere** [comment]
yup that works, so perhaps it is a redirection issue or something

**Comment by theRealTrabo** [comment]
I am just now seeing this, but on the most recent version of the app the login page goes directly to YouTube Music now and it seems like everything in the app itself is working as it should. I presume you already fixed whatever issue was taking place.

**Comment by fuzi0nz** [comment]
If its not working for you now it could be because your YouTube channel is a brand account.

**Comment by kstorbakken** [comment]
I just ran into this yesterday and it took me a good while to find a way around this. The navigation path to get to YT Music was tricky, but here's what worked:
1. Select correct google account (I have 2, the other is a brand account)
2. Click your profile picture in the bottom right.
3. Select Get YouTube Premium (I already have YT Music subscription, but click it anyway)
4. Scroll down to the "Your questions, answered" section
5. Expand the "What's the difference between YouTube Premium and YouTube Music Premium?" question
6. Select "Learn more about YouTube Music"
7. Done. You'll be moved over to YT Music and your profile should now be detected in the app.

**Comment by BRBsoup** [comment]
Leaving this here for anyone searching for a workaround if "Switch Account" ever stops working:

Set Default Channel For YouTube/Google Account
https://support.google.com/youtube/answer/6019090?hl=en
