### ISSUE TITLE
Bug swipe to next track 

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#320]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Swiping to next track in the player

### Expected behavior

To move to the next track

### Actual behavior

Nothing happens. I tried to disable and reenable try setting but it makes no difference 

### Logs

.

### InnerTune version

0.5.9

### Android version

14

### Additional information

I tried the latest debug but no difference

**Comment by Malopieds** [comment]
Would you have a screenrecord of your settings and you swiping? It works fine for me.

**Comment by Lorestan00** [comment]
https://github.com/user-attachments/assets/f885d7a0-4341-437a-909a-6b7da2d29b12

Here you go

**Comment by Malopieds** [comment]
You're on the lyrics part. Disable lyrics and you will be able to swipe. It's on the thumbnails not lyrics.

**Comment by Lorestan00** [comment]
https://github.com/user-attachments/assets/157e5cf3-83f5-4b85-896c-7626b403312c

Okay so I've turned off any setting related to lyrics. See video. I've tried to swipe in multiple areas but doesn't work for me. What am I doing wrong?

**Comment by Malopieds** [comment]
It's written Lyrics not found, because the song you're listening to doesn't have lyrics. You disabled everything related to music except... the one thing that display the lyrics. Click on the lyric icon on the bottom right.

**Comment by Lorestan00** [comment]
That was it. Sorry didn't think of that. In the debug version pretty sure I didn't turn off lyrics. 

> It's written Lyrics not found, because the song you're listening to doesn't have lyrics. You disabled everything related to music except... the one thing that display the lyrics. Click on the lyric icon on the bottom right.

**Comment by Malopieds** [comment]
> That was it. Sorry didn't think of that. In the debug version pretty sure I didn't turn off lyrics.

Don't worry! I'm closing this issue then !
