### ISSUE TITLE
"&" and "," Appearing as Credited Artists on Certain Albums 

### ISSUE THREAD

**Issue by ThatOneUnoriginal** [Malopieds/InnerTune#321]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Simply navigate to any album which has two or more artists credited on it. Examples include Bad Cameo (2), You & I (2), Vultures 1 (3), and others.

### Expected behavior

It should lists all the credited artists of the album as shown on YouTube Music. For example for Vultures 1 it should only show Kanye West, Ty Dollar Sign, and ¥$.

### Actual behavior

When viewing albums that have 2 credited artists on it, a magical third artist will appear called "&" and when viewing albums that have 3 credited artists or more an additional artist called "," will appear. Going to their artist pages results in it showing a blank music list with 0 songs.

So for Vultures 1 for example alongside the expected ¥$, Kanye West and Ty Dollar $ign there is "&" and "," credited on the album as well. Though I should note its just albums no individual song experiences this weird crediting issue.

### Screenshots/Screen recordings

![Screenshot_20240815-234746](https://github.com/user-attachments/assets/4fd744a9-c4d2-4995-a1bb-376be1d6470b)

### Logs

N/A

### InnerTune version

0.5.9

### Android version

Android 15

**Comment by Richard38907** [comment]
Same problem here. When I tap 3 dots on album page.

**Comment by zettaexa** [comment]
i think the same bug is happening but for compilation albums for some reason(?), just the name of the compilation on the song's attributed artists
![Screenshot_20240818-122221.png](https://github.com/user-attachments/assets/44109ab0-dc35-49b5-9b5c-56fa08708a4e)
