### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by pdimu** [Malopieds/InnerTune#322]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

We got drp before 0.6.0 🗣️🗣️🗣️
https://github.com/z-huang/InnerTune/releases/tag/v0.5.7

### Why do you want this feature?

Discord told me to feel less private about my music

**Comment by Malopieds** [comment]
It's already implemented!
