### ISSUE TITLE
Lag and also a glitch ( idk if it's client side or server side )

### ISSUE THREAD

**Issue by ReallyYug** [Malopieds/InnerTune#325]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

N/A

### Expected behavior

N/A

### Actual behavior

1. The app generally was smooth but after update it's like laggy and like the "frame rates" or whatever you call it has became like lesser if you know what I mean, and 2. The app randomly adds random songs in the queue whenever I try to play a single song or try to make a queue with my selected songs

### Logs

Idk how to get them

### InnerTune version

GitHub says 0.5.9 but the app says 0.5.8

### Android version

Android 13

**Comment by Richard38907** [comment]
Point 1 related to #304

**Comment by ReallyYug** [comment]
> Point 1 related to #304

Ye just saw it but the 2nd one is new I think and is really annoying

**Comment by Malopieds** [comment]
Yes but if you don't provide examples/reproducible steps I won't be able to you

**Comment by ReallyYug** [comment]
> Yes but if you don't provide examples/reproducible steps I won't be able to you

@Malopieds does this work? I tried to play my ordinary life but it added random songs in queue as you can see 

Uploading Record-2024-08-18-09-41-01 (1).MP4…

**Comment by ReallyYug** [comment]
https://github.com/user-attachments/assets/c4afe1f5-4188-492e-8f0f-86e2e358de46

**Comment by ReallyYug** [comment]
It didn't upload it in the @ msg so sent it in another msg

**Comment by Malopieds** [comment]
Ok and what's wrong with those songs?

**Comment by ReallyYug** [comment]
Its not the songs it's the queue as you saw I only clicked on one song and it added other ones in the queue and it also does that randomly when I click "play next" or "add to queue" on other songs

**Comment by ReallyYug** [comment]
In previous version(s) it didn't use to do it so ye

**Comment by Malopieds** [comment]
Yeah when you play a song from a search it's a radio from this song so everything is right from there. What do you mean about the play next? It changes the queue?

**Comment by ReallyYug** [comment]
Is there a way I can turn off the "radio" thingy? Because it's like really annoying and also the previous version didn't use to do it so I got used to it 🙃, and yes the play next/add to queue button for songs adds the song and stuff but it adds random songs in the queue too at the end of the queue just like the video but with the buttons, also it does it randomly and not everytime for the buttons

**Comment by Malopieds** [comment]
I never changed that so it was (and always we be) the way it acts, what you may remember was an issue from youtube that changed something for max a week. If you want to only play the current song with no song after you need to play next with no queue before. Other than that this is not an issue and if you have nothing more I'll close this issue.
