### ISSUE TITLE
Incorrect version number in "About" section

### ISSUE THREAD

**Issue by mikedizhur** [Malopieds/InnerTune#329]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open Innertune
2. Open settings
3. Click "About"
4. Version displayed as 0.5.8 instead of 0.5.9

### Expected behavior

The latest version is 0.5.9 so the about section should display the correct version

### Actual behavior

The displayed version is 0.5.8

### Screenshots/Screen recordings

![Screenshot_20240818-212646_InnerTune](https://github.com/user-attachments/assets/edbd8154-1c0e-4dd3-a9bb-4fd12a0caa79)

### Logs

N/A

### InnerTune version

0.5.9

### Android version

Android 14

**Comment by Malopieds** [comment]
> I am able to reproduce the bug with the latest debug version.

Are you? Because I don't think it is still the case in the latest debug versions.

**Comment by mikedizhur** [comment]
Oh, I just checked again and you're right. My bad : /

**Comment by Malopieds** [comment]
> Oh, I just checked again and you're right. My bad : /

Don't worry it's my bad I don't know why it was showing incorrectly on the build!
