### ISSUE TITLE
Request to bring back option to save songs in SD card ( View in SAF))

### ISSUE THREAD

**Issue by Chickenshrimps** [Malopieds/InnerTune#331]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Bring back the option for saving downloaded songs in SD card, the cache option takes up all the storage of the phone and lags in between playing the Songs 

### Why do you want this feature?

Less data usage And smooth use of the app

### Additional information

![Screenshot_2024_0819_085646](https://github.com/user-attachments/assets/eea84d11-456b-443d-a7df-948ed8972014)

**Comment by Malopieds** [comment]
You've open the same issue in #266.

**Comment by Chickenshrimps** [comment]
Yes because you didn't replied there that's why I reopened it pls have the feature added by the next update

**Comment by Malopieds** [comment]
I read all the issues even though I don't respond. I don't think it will be part of the app any soon, it's a feature I don't feel to add, seems like a lot to implement right now, I will accept contribution on this. I might look at it later on, but I prefer focusing on other things.
