### ISSUE TITLE
Crash on hitting  "go to artist" of certain songs

### ISSUE THREAD

**Issue by Richard38907** [Malopieds/InnerTune#332]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search a song (example in my screenshot below), try to go to the artist of this song
See the crash.
Idem with the "go to album" button, it opens a blank page.
I tested on yt music and it works perfectly.

### Expected behavior

Showing artist page or album page

### Actual behavior

Crash or blank page

### Screenshots/Screen recordings

![Screenshot_20240819-145542_InnerTune](https://github.com/user-attachments/assets/dbe3a4cd-d51e-45d2-9bb9-0e3f305af3da)
![Screenshot_20240819-145548_InnerTune.png](https://github.com/user-attachments/assets/d0ff39e3-8fbd-4586-bbde-f6d1968ad9e8)

![Screenshot_20240819-145522_Lawnchair (Debug)](https://github.com/user-attachments/assets/2c5be268-fae5-48ab-b1b4-5f32a4e6974c)

### Logs

[logcat.txt](https://github.com/user-attachments/files/16660502/logcat.txt)

### InnerTune version

0.5.9, Z-Huang and other forks

### Android version

Tested on Android 13

**Comment by Malopieds** [comment]
This looks really specific to this album, their artists seems weird, some of them exists for YTM others not. For instance Giuseppe Tuccillo doesn't (it's YTM behavior). Plus no artist is specified from this album, do you have any other albums/songs that have the same behavior?

**Comment by Richard38907** [comment]
I haven't experienced this for other songs yet.
