### ISSUE TITLE
Settings sliding animation and Version display

### ISSUE THREAD

**Issue by MizxGaming** [Malopieds/InnerTune#333]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to settings
2. Open any seb-menu and go back once
3. Now open any other submenu and go back once
4. Sliding animations are not consistent

1. Go to settings
2. Go to about section
3. Version shows 0.5.8 even on version 0.5.9

### Expected behavior

One-way slide for opening submenu and other-way slide for closing submenu

### Actual behavior

Sliding animations are random

### Screenshots/Screen recordings

N/A

### Logs

N/A

### InnerTune version

0.5.9

### Android version

Android 13

**Comment by Malopieds** [comment]
Is it better now ?

**Comment by mostafaalagamy** [comment]
> > Is it better now ?
> 
> 
> https://github.com/user-attachments/assets/38084833-cda7-4d0b-9d09-1fafc3b87ed8
> 
> The animations are stille random, coming from the top or the bottom, and in diagonal... I suggest the behavior to be the same as settings pages in the Android system settings app 
> Plus the animation when opening mood and genre has two phase, not sure if it's only this page or others too
> 
> https://github.com/user-attachments/assets/e3177c6a-476c-43cb-9ca8-395106f8e59b
> 
> 

upgrade navigation version to 2.8.0-beta07

**Comment by mostafaalagamy** [comment]
> The animations are stille random

Missing upgrade navigation version to 2.8.0-beta07

**Comment by Malopieds** [comment]
All good now
