### ISSUE TITLE
app crashs after deleting songs from the queue 

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#335]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

So sometimes i delete all the songs from the queue except one song or more the app crashs and gets me out
- I need to note that this issue doesn't happen every time but only sometimes

### Expected behavior

No crash during this basic process 

### Actual behavior

gets me out the app

### Screenshots/Screen recordings

non

### Logs

non

### InnerTune version

0.5.9

### Android version

Android 12

**Comment by Richard38907** [comment]
I experience the same bug here

**Comment by Malopieds** [comment]
Can anyone provide me logs/ or a way to reproduce it?

**Comment by Richard38907** [comment]
Yep will do it soon :)

**Comment by Richard38907** [comment]
![logcat.txt](https://github.com/user-attachments/files/16695615/logcat.txt)

**Comment by Malopieds** [comment]
How do you reproduce it? It seems to be random.

**Comment by Richard38907** [comment]
Yep I tested more than ten times and it finished in a crash. Sometimes when checking all the songs or almost all songs.

**Comment by Malopieds** [comment]
Ok, I tried something I couldn't get the bug after testing like 20+ times. If you have this bug again with the debug version, ping me.
