### ISSUE TITLE
removing the little play buttom on albums and singles in library

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#336]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

can you remove this little play button that appears on albums (singles also i think)

### Why do you want this feature?

I mean there's no reason for it also if you just click on the album there's already a play button if u know what I'm talking about..

### Additional information

so this is just a simple request its not that important but i think it would be great at least for me

**Comment by Malopieds** [comment]
I don't see the point of removing this, it can be useful for some people but doesn't disturb your activity on the app. I also don't want to add a setting for this so no it won't be removed.
