### ISSUE TITLE
Issue with the queue button color on gradient theme since the recent change

### ISSUE THREAD

**Issue by MLZ94** [Malopieds/InnerTune#337]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Enable gradient theme
Play a music
Touche the queue button

### Expected behavior

The button keeps the gradient color until the queue menu is expended

### Actual behavior

The button becomes white (color of the queue menu when expended)

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/e448cdc4-3261-478f-b394-8e90c3018078

### Logs

N/A

### InnerTune version

Latest debug version at the time i post this

### Android version

Android 14 pixel 6 latest official update

**Comment by Malopieds** [comment]
> The button keeps the gradient color until the queue menu is expended

I won't do fully but I'll see what I can do.

**Comment by MLZ94** [comment]
Thank you so much for your work

**Comment by mostafaalagamy** [comment]
> > The button keeps the gradient color until the queue menu is expended
> 
> I won't do fully but I'll see what I can do.

Box(
            modifier = Modifier
                .fillMaxSize()
                .background(backgroundColor)
        ) {
        LazyColumn(
            state = reorderableState.listState,
            contentPadding =
                WindowInsets.systemBars
                    .add(
                        WindowInsets(
                            top = ListItemHeight + 12.dp + 8.dp,
                            bottom = ListItemHeight + 8.dp,
                        ),
                    ).asPaddingValues(),
            modifier =
                Modifier
                    .fillMaxSize()
                    .reorderable(reorderableState)
                    .nestedScroll(state.preUpPostDownNestedScrollConnection),


Look at this... This solves the issue.

**Comment by mostafaalagamy** [comment]
But before this, everything should be reverted to how it was before the last queue commit.

**Comment by MLZ94** [comment]
Well then that wouldnt be necessary since the issue was introduced with that last commit

**Comment by Malopieds** [comment]
> But before this, everything should be reverted to how it was before the last queue commit.

No need for that but I took your version, how does it look?

**Comment by mostafaalagamy** [comment]
> > But before this, everything should be reverted to how it was before the last queue commit.
> 
> No need for that but I took your version, how does it look?

 This is better now , thanks.

**Comment by Malopieds** [comment]
Perfect, closing it then !

**Comment by MLZ94** [comment]
I dont understand what's going on, but it still not fixed for me... I did install the latest debug from the last commit atm... But i still end up with the issue[
![Screenshot_20240820-234707](https://github.com/user-attachments/assets/9c16a01c-48bf-4cf3-a75a-a426bbd842ce)
](url)

**Comment by MLZ94** [comment]
Okay, nevermind i guesse it's a bug with my phone after uninstalling and reinstlling the same apk it worked. Thanks a lot!
