### ISSUE TITLE
Changing keyboard language does not work properly (GBoard)

### ISSUE THREAD

**Issue by Irobrine** [Malopieds/InnerTune#341]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to the search bar or lyrics search. 
2. Try changing languages on GBoard using the "Change Keyboard" popup that appears by long pressing the globe icon. 

### Expected behavior

popup appears

### Actual behavior

popup appears but closes immediately after. 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/b1634cb6-6ac7-442d-8d73-1bc20c5d85e4

### Logs

unable to provide logs currently due to being abroad. would provide if needed. 

### InnerTune version

0.5.9

### Android version

Android 14

### Additional information

Other methods of changing languages work such as pressing the globe once.

**Comment by Malopieds** [comment]
That's weird, it doesn't happen on other keyboards, and not on the upstream repo. I'll look into it.

**Comment by Malopieds** [comment]
Hey, can you check on the latest release, seems to have fixed it.

**Comment by Irobrine** [comment]
Yep, fixed the issue. Thank you.
