### ISSUE TITLE
automatically playing radio once an album is done

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#348]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

an optional feature where once you finish an album or ep, it will automatically start playing the last song's radio

### Why do you want this feature?

it was a spotify feature i really liked until they got rid of it which made me wanna go to innertune in the first place, +  it makes you discover new music you haven't listened before , Would be good to have!!

**Comment by Malopieds** [comment]
It's already implemented. Can you check on the latest debug build and tell me if everything works?

**Comment by zettaexa** [comment]
oh sorry i've been using the released builds, i didn't know
