### ISSUE TITLE
Save Queue as Playlist Button

### ISSUE THREAD

**Issue by heschy2** [Malopieds/InnerTune#349]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add a button at the Queue Header (Where the Lock-Button, Select-Toggle and Song Count etc. are), that functions like the "Add to playlist" button on the Song Page, but for the whole queue, to allow the user to add all songs in the queue to a playlist.

### Why do you want this feature?

The queue is basically a temporary playlist, and sometimes I decide that I want to keep this playlist, but I need to go through the "Add to playlist" Process for every single song, which is annoying.

### Additional information

My explanation is not good, I am sorry for that, but I hope you understand what I mean.

**Comment by Malopieds** [comment]
What about the multiselect button? Just click it then select all and add all to a playlist?

**Comment by heschy2** [comment]
Oh yes, I didn't realize that was possible, thank you!
