### ISSUE TITLE
Empty section in some artist's pages

### ISSUE THREAD

**Issue by MLZ94** [Malopieds/InnerTune#351]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to certains artist pages. Ex. Jason Derulo

### Expected behavior

No empty section 

### Actual behavior

Some sections such as recents and podcasts are shown but empty

### Screenshots/Screen recordings

![Screenshot_20240901-124358](https://github.com/user-attachments/assets/5b09bfff-b570-47dd-b4c2-676def2b4190)

### Logs

Can't get right row

### InnerTune version

Latest debug version at the time i post this

### Android version

Android 14 pixel 6 latest official update

### Additional information

This happen to certain aritists, i can't say which ones exactly

**Comment by Malopieds** [comment]
Could you try [this](https://github.com/Malopieds/InnerTune/actions/runs/11862963267/artifacts/2194961214) debug version and tell me if it fixes it for you?

**Comment by MLZ94** [comment]
Indeed this seems to be fixed! Thank you very much for making this app better and better! <3
