### ISSUE TITLE
Malopieds as second developer for original InnerTune.

### ISSUE THREAD

**Issue by ghost** [Malopieds/InnerTune#352]
**EDIT: I'll contribute in an already open discussion instead of having an issue open. Relevant discussions: https://github.com/Malopieds/InnerTune/discussions/350, https://github.com/Malopieds/InnerTune/discussions/294.**

### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hello,

I had a suggestion for the future of this fork. Obviously I respect the work Malopieds has done on this fork and stepping up to fix critical issues when the original developer was not active. With that said, assuming Malopieds does not have a completely different vision on how the fork should be (which is totally valid), why not have both developers work on a single app and improve it together. Sorry if I am overstepping here but just wanted to hear if there are any plans like this in the making.

### Why do you want this feature?

As the original app is more recognised and has more github stars, it will be good to have both developers work on the original app and improve it together.

**Comment by ThatOneUnoriginal** [comment]
Malopieds could correct me if things have changed throughout the past couple of days but from my knowledge the plan currently is to separate this from the original InnerTune application by giving it a new name/branding. Plus something like this would also depend on if the original developer of InnerTune is willing to have such happen as well (since its ultimately still their application at the end of the day.)

**Comment by ghost** [comment]
> Malopieds could correct me if things have changed throughout the past couple of days but from my knowledge the plan currently is to separate this from the original InnerTune application by giving it a new name/branding.

Yes, I saw the open issue about this. A change of branding does not necessarily mean a change in developmental direction, they're just trying to cut down on confusion. I can see that both z-huang and Malopieds are submitting pull requests bringing over functionality or fixes from the other app. For example, this [commit](https://github.com/Malopieds/InnerTune/commit/75f9006fc1714a8d031b37237da6c6fbca5b4617). If both apps (currently) have (almost) the same feature set and are porting over patches from each other then why continue having two separate apps?

> Plus something like this would also depend on if the original developer of InnerTune is willing to have such happen as well (since its ultimately still their application at the end of the day.)

Yes of course. I doubt something like this was not already discussed between both developers hence my question if anything stopped them from doing this.

**Comment by ghost** [comment]
I'll contribute in an already open discussion instead of having an issue open. Relevant discussions: https://github.com/Malopieds/InnerTune/discussions/350, https://github.com/Malopieds/InnerTune/discussions/294.
