### ISSUE TITLE
Changing order in playlist is broken

### ISSUE THREAD

**Issue by a-eldar** [Malopieds/InnerTune#361]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Attemp to change the position of a song within a custom playlist

### Expected behavior

The song should "move along" with the finger

### Actual behavior

The song is stuck in place, and after releasing the hold, the song beneath it is affected instead.

### Logs

Don't have

### InnerTune version

0.5.9

### Android version

Android 12

**Comment by S3nsh1r0** [comment]
Im having a similar issue on android 13 with CrDroid. it espacially doesnt work in the "downloaded"  section, also the "liked section doesnt really sort the things in the right order when sorted as " date added" or else

**Comment by Malopieds** [comment]
Is it still happening in the latest version?

**Comment by a-eldar** [comment]
Yes

**Comment by Malopieds** [comment]
Could you send a reproducible backup?

**Comment by a-eldar** [comment]
Pardon? You mean from the "backup and restore" menu?
[InnerTune_20241029102218.zip](https://github.com/user-attachments/files/17553923/InnerTune_20241029102218.zip)

**Comment by S3nsh1r0** [comment]
> Is it still happening in the latest version?

Yeah

**Comment by Malopieds** [comment]
> Pardon? You mean from the "backup and restore" menu?

The zip is empty

**Comment by a-eldar** [comment]
Um the backup is there for me. Do you want me to send it in a different way?

**Comment by Jesterof84** [comment]
had this start happening to me as well after updating to the newest version, it seems the the button assignment is merged. https://github.com/user-attachments/assets/df516bdf-c90a-414b-a376-bf0462da8b93

**Comment by S3nsh1r0** [comment]
Its for still after the recent update, so. well tbf there wasnt really a fix for that mentioned so ig thats fair to tell that didnt fixed it xP

**Comment by Laur401** [comment]
Can confirm the bug is still in place for 0.5.11-rc1. In addition, doesn't seem like it's been noticed, but trying to move the last song in the playlist crashes the app.

**Comment by S3nsh1r0** [comment]
where do you even do that?  I want to try if it crashed on my phone as well

**Comment by Laur401** [comment]
> where do you even do that? I want to try if it crashed on my phone as well

Just open (or create) a custom playlist in your Library and try moving the last song.

**Comment by S3nsh1r0** [comment]
If its the one button with the three lines and the note, then I cant even use it, like nothing happens at all.

**Comment by Laur401** [comment]
> If its the one button with the three lines and the note, then I cant even use it, like nothing happens at all.

I think that's adding to queue, you should use the three lines and plus symbol and then create the playlist from there. Then afterwards you can enter the playlist through the Library section, press on the square with dots surrounding it to activate selection, then hold the two horizontal lines and move a track up or down.

**Comment by S3nsh1r0** [comment]
Well, after the square part, nothing is same. I dont even have the two lines for moving. Even after making a new Playlist for test purposes

**Comment by Laur401** [comment]
Have you selected Custom order in playlist ordering dropdown?

**Comment by S3nsh1r0** [comment]
> Have you selected Custom order in playlist ordering dropdown?

ahhh, now its working as "expected", thanks xd
Yap, it crashes

**Comment by Malopieds** [comment]
Could you try [this](https://github.com/Malopieds/InnerTune/actions/runs/11862963267/artifacts/2194961214) debug version and tell me if it fixes it for you?

**Comment by Laur401** [comment]
Just tested it out, works fine on my end, app doesn't crash, changes still there after restarting the app.
