### ISSUE TITLE
Lyrics hard to see

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#363]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

An option to change the colour or contrast / brightness of lyrics. Also change the size of the font

### Why do you want this feature?

At the moment it can be hard to see lyrics as the colour merges in with the background for lyrics not yet live but sometimes even the lyrics being sung can be hard to see. The size of the lyrics can be a bit small 

![Screenshot_2024-10-14-10-29-07-91_56635af9b6ad4512d4187a5a49185a25](https://github.com/user-attachments/assets/3d83e85e-48f1-451b-9f4f-784a07fa0c18)

**Comment by Malopieds** [comment]
Fixed in the latest version!
