### ISSUE TITLE
Songs can't be played without logging in.

### ISSUE THREAD

**Issue by Nandkishor01** [Malopieds/InnerTune#366]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to Innertune app
2. Click on any song that's not Cached
3. An error "Please sign in" Will show up.

### Expected behavior

Songs should be played without logging in.

### Actual behavior

Now it's asks for login before playing any song that's not cached.
![Screenshot_20241024-102221_InnerTune](https://github.com/user-attachments/assets/3e3b4b85-507d-4375-a93a-a945539ca74a)

### Logs

Don't have.

### InnerTune version

0.5.8

### Android version

Android 13

### Additional information

From what I know I think it's something ytmusic is trying to do every app that used to play songs without login are affected.

**Comment by orl0pl** [comment]
I also have this issue

**Comment by mikwee** [comment]
Same for me

**Comment by cgnicow** [comment]
Google being fucking google.

**Comment by Malopieds** [comment]
Yep, google trying to block as much as they can. I'll see if I can do something about it.

I know it's been a long time since I updated this app, but I've got a lot of other project going through lately.

**Comment by Nandkishor01** [comment]
For anyone wondering it's still possible to run Innertune normally you just have to login using your Google account.

**Comment by Nandkishor01** [comment]
> Yep, google trying to block as much as they can. I'll see if I can do something about it.
> 
> I know it's been a long time since I updated this app, but I've got a lot of other project going through lately.

It's alright we can still use it by signing in, but yeah please look it whenever you get time to do so.

And thanks for the awesome work.

**Comment by cgnicow** [comment]
It's not alright I absolutely don't wanna create a google account

**Comment by mikwee** [comment]
Then you’ll have to wait like the rest of us for a fix.

**Comment by cgnicow** [comment]
I'll try to help if I have the time babes

**Comment by Nandkishor01** [comment]
I found two Possible solution

Please have a look and see if they helps.

1. NewPipeExtractor (v0.24.2) still works
2. Or I liked what this dude did using an IOS context [here](https://github.com/toasterofbread/ytm-kt/commit/ce99c539af10f299a635fbc073b273245119730e).

**Comment by Malopieds** [comment]
Actually just setting to WEB_REMIX should do the trick, but I don't have anything to test until this weekend...

**Comment by Moyomvuyo** [comment]
So when is this issue gettimg fixed

**Comment by heschy2** [comment]
The weird thing is, I just had this with a downloaded song and it could be reseolved by redownloading it.

**Comment by Der-Flip** [comment]
I don't wanna be the bearer of bad news but I _am_ signed in and it doesn't work, prompting me to sign in.

**Comment by heschy2** [comment]
I think they are working on a Fix Upstream:

https://github.com/z-huang/InnerTune/issues/1653#issuecomment-2439644739

**Comment by Malopieds** [comment]
Hi, I just pushed a fix, should be working, could anyone test it and tell me?
Here is the [debug version](https://github.com/Malopieds/InnerTune/actions/runs/11561682983/artifacts/2114351149).

**Comment by mikwee** [comment]
Seems to work okay for me. No more login issues. @Malopieds

**Comment by Malopieds** [comment]
> Seems to work okay for me. No more login issues. [@Malopieds](https://github.com/Malopieds)

Good to know, I'll try to make a release today or tomorrow. Waiting for others' inputs.

**Comment by BluePixel4k** [comment]
> Hi, I just pushed a fix, should be working, could anyone test it and tell me? Here is the [debug version](https://github.com/Malopieds/InnerTune/actions/runs/11561682983/artifacts/2114351149).

Thanks a lot! No issues so far 👍

**Comment by SalvaZaraes** [comment]
Works incredibly fine! Thanks @Malopieds

**Comment by Malopieds** [comment]
Closing it. If it happens again, please open a new issue!
