### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by ReallyYug** [Malopieds/InnerTune#367]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Well discord rpc is discord rpc, its useful ig also https://github.com/Malopieds/InnerTune/issues/322 says its already implemented but i cant find a way to turn it on or anything

### Why do you want this feature?

Discord RPC is cool 🗣️

**Comment by Malopieds** [comment]
Yep it is. You can use latest debug, or maybe I will try to make a fix for login issue this weekend.

**Comment by Malopieds** [comment]
This is now in the new version!
