### ISSUE TITLE
Spotify playlists

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#37]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Would be great to be able to login into Spotify and download playlists (using the same backend of course downloading from YouTube). 

### Why do you want this feature?

Personally I have 100s of Spotify playlists and would love to be able to download and access them

**Comment by Malopieds** [comment]
It will take some time but try migrating all your spotify playlists to youtube playlist. There are plenty of library that allows you to do that. I won't integrate Spotify login, first because there is already google login (that I don't like) and also because that's not the point of this app. You can still use Spotube if you want to use your Spotify account !

**Comment by Lorestan00** [comment]
Fair point on not wanting to add another login. I was using Spotube but it's really slow to stream tracks, searching for playlists doesn't always find playlists and when you do download a playlist...it doesn't create a playlist with those tracks just downloads the tracks. 

Innertune is great just a way to get my Spotify playlists on there. Waaay too many to recreate each one

Any chance of a way to upload playlists though importing in .m3u playlist format?

**Comment by Malopieds** [comment]
Well, why not using [that](https://github.com/sigma67/spotify_to_ytmusic?tab=readme-ov-file#transfer-all-playlists-of-a-spotify-user). You can export all your spotify playlist in one click to youtube music. Therefore you will connect in innertune to youtube music and you can import the playlist you want !

> Any chance of a way to upload playlists though importing in .m3u playlist format?

No there is not :/

**Comment by Lorestan00** [comment]
Thanks for the suggestion. I did actually come across it. It looked abit complicated not using command lines.

**Comment by Lorestan00** [comment]
I've imported in a couple of playlists to youtube music but they aren't showing up in playlists or the home tab. I've logged into my account under 'content' in settings.

**Comment by Malopieds** [comment]
In the home screen, you have an "Account" button at the top. If you click there, you have all the playlist you have on YouTube music. Now if you click on one you will have two icons under the number of tracks, click on the one with the arrow and it'll show up in your playlists !

**Comment by Lorestan00** [comment]
Thanks! Awesome that's worked

**Comment by Malopieds** [comment]
Closing it then !
