### ISSUE TITLE
Discord RPC not working 😔

### ISSUE THREAD

**Issue by ReallyYug** [Malopieds/InnerTune#370]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Connect discord account, turn on the rpc, go to discord, nothing shows up for rpc

### Expected behavior

.

### Actual behavior

.

### Logs

Idk how to

### InnerTune version

0.5.10

### Android version

14

**Comment by Malopieds** [comment]
Does it work for you on the original branch?

**Comment by ReallyYug** [comment]
@Malopieds I am using the latest release, idk which branch it's on

**Comment by ReallyYug** [comment]
https://github.com/Malopieds/InnerTune/releases/download/v0.5.10/app.apk this one

**Comment by Malopieds** [comment]
My bad, I meant repo. I didn't changed anything from this implementation.

**Comment by ReallyYug** [comment]
> My bad, I meant repo. I didn't changed anything from this implementation.

Is it working fine for you?

**Comment by ReallyYug** [comment]
Also it shows update available even tho I am on latest version 
![Screenshot_20241030_072446_InnerTune](https://github.com/user-attachments/assets/0926e5b6-cbcc-4412-8821-e2cf9c61d755)
![Screenshot_20241030_072449_InnerTune](https://github.com/user-attachments/assets/22d091dc-a866-48d6-923a-4b0711cc2441)

**Comment by Malopieds** [comment]
> Is it working fine for you?

Nope, I updated something, could you tell me if the latest debug version fixes this?

> Also it shows update available even tho I am on latest version

Weird I don't have it...

**Comment by ReallyYug** [comment]
> Nope, I updated something, could you tell me if the latest debug version fixes this?

Where do I download that version?

**Comment by ReallyYug** [comment]
> Weird I don't have it...

Uhhhhh 💀

**Comment by mikedizhur** [comment]
> > Nope, I updated something, could you tell me if the latest debug version fixes this?
> 
> Where do I download that version?

Instructions to build it are in the hyperlink next to the first point you checked off, lol. (In simple terms, install android studio, clone the repo, build the apk)

In any case, I checked, and release version indeed does not show the status on discord. c74253438268c45ce90c52e31d8dc0332161ea57 does fix the issue.

**Comment by ReallyYug** [comment]
> Instructions to build it are in the hyperlink next to the first point you checked off, lol. (In simple terms, install android studio, clone the repo, build the apk)

I checked it and just saw updates to code so I was like probably just commit stuff I didn't knew that existed, but anyway I tested it to, and atleast for me the images don't work like it shows blank instead of image in rpc, another thing is that it takes time to update and isn't instant and time like not 1-3 secs but 10-15 secs which is kizzy issue i think because I used kizzy before for InnerTune so ye, but ye, also a suggestion, add time bar for rpc 🙌

**Comment by Malopieds** [comment]
> add time bar for rpc

Does kizzy support this?

**Comment by ReallyYug** [comment]
Yes, it does

**Comment by Malopieds** [comment]
Closing this then, please open a feature request for the time bar.
