### ISSUE TITLE
unknown error when playing YouTube videos

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#371]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. search any song that isn't distributed by YouTube (aka a regular YouTube video, or videos in community playlists)
2. it will give you an unknown error

### Expected behavior

it's supposed to play the video like before

### Actual behavior

gives you an error
![Screenshot_20241029-201350](https://github.com/user-attachments/assets/deef2e92-252c-4c10-a995-98c35d1b8baf)

### Logs

how do i??

### InnerTune version

0.5.10

### Android version

Android 15

### Additional information

i noticed this happened when i search for a video rather than going through an artist page and clicking on one of the music videos

(copy from comment i made)
After trial and error, I found that the faulty commit was 6b2318a, aka fixing listening to music without logging in.

Will provide logs soon

**Comment by zettaexa** [comment]
Same thing with the debug version, maybe after 0.5.10 it started to have this bug

**Comment by zettaexa** [comment]
0.5.9 isn't affected by this, tried logging in again in 0.5.10 but doesn't seem to work, need to find the faulty commit

**Comment by zettaexa** [comment]
After trial and error, I found that the faulty commit was 6b2318a, aka fixing listening to music without logging in, Please fix this!

![Screenshot_20241031-001113](https://github.com/user-attachments/assets/878d93f4-9acd-4faf-a7e3-abba513712e7)

**Comment by Malopieds** [comment]
Yeah, I will prioritize the android music player if the user is logged in but it's not a way to fix this bug. I can play any videos that are not too long (and I think the issue here is the length of the video you're trying to play, so that's not a priority for now). Do you have other videos that doesn't play?

**Comment by zettaexa** [comment]
> Yeah, I will prioritize the android music player if the user is logged in but it's not a way to fix this bug. I can play any videos that are not too long (and I think the issue here is the length of the video you're trying to play, so that's not a priority for now). Do you have other videos that doesn't play?

https://music.youtube.com/watch?v=QbGbq-kEQH4
This 1 and a half minute video doesn't play (AFX in the maze park), it's definitely **not** about track length

**Comment by Malopieds** [comment]
Now fixed.

**Comment by zettaexa** [comment]
Thank you so much! Im going to test the debug version once its available

**Comment by Malopieds** [comment]
> Thank you so much! Im going to test the debug version once its available

You can have it [there](https://github.com/Malopieds/InnerTune/actions/runs/11627085056/artifacts/2132365280)
