### ISSUE TITLE
Unable to download songs on 0.5.10

### ISSUE THREAD

**Issue by mikedizhur** [Malopieds/InnerTune#372]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Click any song
2. Click the download button in player
3. Download fails

### Expected behavior

Song is downloaded

### Actual behavior

1. Loading animation plays
2. Loading animation stops after some time, song not downloaded.

### Logs

1730349175.766 10312 26660 26699 E DownloadManager: Task failed: null:zlJ0Aj9y67c, false
1730349175.766 10312 26660 26699 E DownloadManager:   androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:369)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:262)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.cache.CacheWriter.readBlockToCache(CacheWriter.java:174)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.datasource.cache.CacheWriter.cache(CacheWriter.java:136)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.exoplayer.offline.ProgressiveDownloader$1.doWork(ProgressiveDownloader.java:106)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.exoplayer.offline.ProgressiveDownloader$1.doWork(ProgressiveDownloader.java:103)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.common.util.RunnableFutureTask.run(RunnableFutureTask.java:126)
1730349175.766 10312 26660 26699 E DownloadManager:       at com.malopieds.innertune.playback.DownloadUtil$$ExternalSyntheticLambda2.execute(D8$$SyntheticClass:0)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.exoplayer.offline.ProgressiveDownloader.download(ProgressiveDownloader.java:118)
1730349175.766 10312 26660 26699 E DownloadManager:       at androidx.media3.exoplayer.offline.DownloadManager$Task.run(DownloadManager.java:1343)

### InnerTune version

0.5.10

### Android version

Android 14

### Additional information

Log from debug version, song "lose yourself" by Eminem used for log

**Comment by Malopieds** [comment]
Thanks for reporting !
