### ISSUE TITLE
Add option for donation

### ISSUE THREAD

**Issue by 9glenda** [Malopieds/InnerTune#374]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I'd like to do a small one time donation. 

### Why do you want this feature?

.

**Comment by Malopieds** [comment]
It's really kind of you, but I'm not willing to take other's money. I do this project for me at first and if people want the same things as me so good for them. Keep your money, if you can/still want to give money, please find a cause to support, there are a lot of action/organizations that could need this money more than me!
