### ISSUE TITLE
UI minimized song

### ISSUE THREAD

**Issue by 9glenda** [Malopieds/InnerTune#375]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play a song. 

### Expected behavior

. 

### Actual behavior

You may be able to see, that in the right bottom corner a small yellow dot is visible. This should not be the case. 
I'm on a Google Pixel 6. I do not have access to any other devices to check rather it's a device specific issue. 

### Screenshots/Screen recordings

![1000037556](https://github.com/user-attachments/assets/6678c70b-7281-47c2-80b2-58a61239b430)

### Logs

I don't need to provide logs in this case. 

### InnerTune version

Latest debug version

### Android version

Graphene OS Android 15

**Comment by zettaexa** [comment]
That little dot in the corner is just a part of Material 3's progress bar, Im not sure if there is a way to get rid of it really but it's more of a tiny annoyance that you would forget about it in a day or so

**Comment by Malopieds** [comment]
> That little dot in the corner is just a part of Material 3's progress bar, Im not sure if there is a way to get rid of it really

Yes exactly, I can't do anything about it, sorry.
It was Aldo bothering me at first but in the end it doesn't really matter
