### ISSUE TITLE
bump to v0.5.10.1?

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#377]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

maybe for the fixes you made for playing/downloading, it should be put as a release in Github 

### Why do you want this feature?

for the fixes to be available as an app update

**Comment by Malopieds** [comment]
I can do a release candidate, maybe.
