### ISSUE TITLE
Add option to select songs in queue

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#38]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I think it would be useful if there's option to select songs in the queue

### Why do you want this feature?

sometimes i want to clear all the songs in queue so if there's the option to select the songs by clicking on "select all" it will be so useful

### Additional information

Thanks for keep making this amazing app more better ❤️

**Comment by Malopieds** [comment]
Well if you want to clear the queue you can swipe down on the miniplayer, it will stop the song playing and clear all the queue.

**Comment by Spaceshiprace** [comment]
nah, cuz sometimes I want to remove a certain song only from the queue

**Comment by SiddhantRakh** [comment]
You can swipe right to clear a specific song in the queue.

**Comment by Spaceshiprace** [comment]
yeah i know but selecting songs is better to me.
and I also didn't get what @Malopied means by swiping down on the miniplayer like why it should stop playing the song and then clear the queue like I just want to clear it without stopping the song, u know what I mean ?

**Comment by Malopieds** [comment]
> yeah i know but selecting songs is better to me.

It's not possible for now, in addition the long press to select songs is already taken, and adding a button to select all is:
- not intuitive, because if you want to select only two songs, it requires to deselect manually all except two, and can be long for the user
- and the logic behind it requires too much work for now. It might get implemented in future release but not anytime soon.

**Comment by Malopieds** [comment]
> why it should stop playing the song and then clear the queue

Because it the current behaviour, and logic one.

**Comment by Spaceshiprace** [comment]
its just not making any sense to me but okey its not a problem, i just opened this issue to see if its possible not because a problem that needs to be fixed.
Appreciate u for trying to make this app better anyway ❤️

**Comment by Malopieds** [comment]
I was thinking about adding this kind of behaviour to the long press. When you long press there is the menu and from the menu you would be able to select this songs, it will after allow multi select. It's the more effective way imo. What do you think ?

**Comment by SiddhantRakh** [comment]
Well how about implementing a check mark(tick) to select songs like Spotify:
![Screenshot_20240402-185849_InnerTune~2](https://github.com/Malopieds/InnerTune/assets/42494931/3cfdab6b-5214-4703-a079-9e06ac350d05)
![Screenshot_20240402-190344_Spotify](https://github.com/Malopieds/InnerTune/assets/42494931/00d0246c-2d3d-48c4-94c0-1033d9a85c6f)

**Comment by Malopieds** [comment]
Yep the spotify approach is definitely more usable. I'll look into it.

**Comment by Spaceshiprace** [comment]
> Well how about implementing a check mark(tick) to select songs like Spotify:

really good idea, This is what I meant from the beginning cuz I saw it there on spotify and I wanted that option to be on innertune too

**Comment by Malopieds** [comment]
It is now implemented. Tell me if you find some bugs.

**Comment by mostafaalagamy** [comment]
> It is now implemented. Tell me if you find some bugs.

After selecting the songs and changing my mind, if I want to deselect them, I must deselect them one by one. Adding a 'Deselect All' option is necessary.

**Comment by Spaceshiprace** [comment]
> > It is now implemented. Tell me if you find some bugs.
> 
> After selecting the songs and changing my mind, if I want to deselect them, I must deselect them one by one. Adding a 'Deselect All' option is necessary.

Strongly agree.

**Comment by Spaceshiprace** [comment]
but wait.. how i can select now ? is it available on that 0.5.7 version cuz i can't select the songs yet

**Comment by Malopieds** [comment]
> After selecting the songs and changing my mind, if I want to deselect them, I must deselect them one by one. Adding a 'Deselect All' option is necessary.

Yes I agree with you.

> but wait.. how i can select now ? is it available on that 0.5.7 version cuz i can't select the songs yet

No releases have been made yet, but you can try the [latest debug version](https://github.com/Malopieds/InnerTune/actions/runs/8719835592/artifacts/1421442786)

**Comment by Spaceshiprace** [comment]
> No releases have been made yet, but you can try the [latest debug version](https://github.com/Malopieds/InnerTune/actions/runs/8719835592/artifacts/1421442786)

so yes I tried the debug version, and I got say its amazing, that feature works well from my experience the only issue is that it needs the "Deselect option" that was already mentioned, so yea it works without any bugs (for me)

**Comment by Malopieds** [comment]
Now implemented.

**Comment by Spaceshiprace** [comment]
also I noticed a thing, so now there's a deselect option so why isn't there an option to select all songs in the first place ?

**Comment by SiddhantRakh** [comment]
> is that funny ?

Sorry bro it was by accident. I am using GitHub on Chrome as the app is trash so it might have been the reason for the emoji. I forgot I pressed it by accident as it takes 5 second for it to appear on Chrome.

**Comment by Spaceshiprace** [comment]
no prblm, matter fact I'm using it on a browser too 😅
