### ISSUE TITLE
The "Search" launcher shortcut doesn't work

### ISSUE THREAD

**Issue by ghost** [Malopieds/InnerTune#392]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open the "Search" launcher shortcut.

### Expected behavior

It should open search.

### Actual behavior

It opens the app normally.

### Logs

Not relevant.

### InnerTune version

0.5.11-rc1

### Android version

Android 13

**Comment by Malopieds** [comment]
Hi, could you tell me if the [latest debug version](https://github.com/Malopieds/InnerTune/actions/runs/11869476064/artifacts/2196427027) fix this for you?
