### ISSUE TITLE
tracks get unliked when you go to its album page

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#393]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Listen to a track
2. Go to its album page
3. Liked tracks become unliked or added tracks become unadded

### Expected behavior

Shouldn't happen, tracks should stay liked

### Actual behavior

Happened, liked tracks become unliked

### Logs

Don't know how

### InnerTune version

0.5.11-rc1

### Android version

Android 15

**Comment by Malopieds** [comment]
I actually don't understand what you mean. Could you take a video please?

**Comment by zettaexa** [comment]
> I actually don't understand what you mean. Could you take a video please?

@Malopieds 

https://github.com/user-attachments/assets/bcc86dcb-306b-4fed-b6a6-0d24a6ce2545

**Comment by Malopieds** [comment]
Seems like 386deb4759db796fde4cac2d23bc69e5bcb3435b is the culprit... I'll try this week to have a look at it

**Comment by zettaexa** [comment]
> Seems like [386deb4](https://github.com/Malopieds/InnerTune/commit/386deb4759db796fde4cac2d23bc69e5bcb3435b) is the culprit... I'll try this week to have a look at it

Any advances? Did you find what was causing it?

**Comment by Malopieds** [comment]
Could you try [this](https://github.com/Malopieds/InnerTune/actions/runs/11862963267/artifacts/2194961214) debug version and tell me if it fixes it for you?

**Comment by zettaexa** [comment]
> Could you try [this](https://github.com/Malopieds/InnerTune/actions/runs/11862963267/artifacts/2194961214) debug version and tell me if it fixes it for you?

Ok I will right now!

**Comment by zettaexa** [comment]
> Could you try [this](https://github.com/Malopieds/InnerTune/actions/runs/11862963267/artifacts/2194961214) debug version and tell me if it fixes it for you?

It works perfectly in about every instance!! Thank you!
