### ISSUE TITLE
songs not playing if signed in

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#397]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

after I signed in songs stop playing 

### Expected behavior

working

### Actual behavior

"Unknown error"

### Logs

idk

### InnerTune version

0.5.11-rc-1

### Android version

android 12

**Comment by Vikingtons** [comment]
Also able to reproduce this on 5.10

**Comment by OnyxJet** [comment]
This is an issue even when not signed in as well.

**Comment by Malopieds** [comment]
Works fine for for both signed and non signed in, please make sure you tried with the [latest debug version](https://github.com/Malopieds/InnerTune/actions/runs/11869476064/artifacts/2196427027). On what (if not all) songs is it happening for you? Do you have a vpn?

**Comment by Frer1** [comment]
Hola.

Creo que de alguna manera "dañé la app.

No puedo reproducir ninguna canción, la actualicé, borré datos "caché", incluso eliminé la aplicación que instalé versiones anteriores y nada ha funcionado.

Hasta he creado un usuario, creyendo que quizás así funcione, pero no, no ha funcionado.

Sinceramente creo que por alguna razón he roto la App.

**Comment by ThatOneUnoriginal** [comment]
@Malopieds I am using the latest available version of the debug apk and I am encountering this issue as well. When I attempt to play music I get an error and it also proceeds to fail to download any of the songs. It appears to happen to all songs that I have. Tried clearing the cache, deleting the apps storage (essentially clearing the app), updating the debug version, but so far no solution.

**Comment by Vikingtons** [comment]
Able to reproduce this on 5.11

**Comment by Malopieds** [comment]
Could you tell me if [this](https://github.com/Malopieds/InnerTune/actions/runs/12097107486/artifacts/2256651585) fixes it?

**Comment by Vikingtons** [comment]
Sure, I can give that a try on another device
E: the debug app appears to be working fine for now - will use it as my player for today and keep an eye on it. Thank you!

**Comment by Malopieds** [comment]
You can use the release version if you want.

**Comment by Vikingtons** [comment]
5.12 working fine here - thanks!

**Comment by Frer1** [comment]
> Puedes utilizar la versión de lanzamiento si lo 

> Puedes utilizar la versión de lanzamiento si lo deseas.

Acabo de bajar la versión 5.12 y parece que por ahora funciona bien, la probaré en profundidad más tarde.

Gracias.

**Comment by vmmandalorian** [comment]
Working now on 0.5.12![Screenshot_20241202-153255.jpg](https://github.com/user-attachments/assets/a279f85a-5d3d-493b-a247-a182d01edfb3)
