### ISSUE TITLE
Song not playing even after login.

### ISSUE THREAD

**Issue by H3T-Shah** [Malopieds/InnerTune#398]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Just play some song which is not cached or downloaded.

### Expected behavior

Song should play.

### Actual behavior

It doesn't play.

### Screenshots/Screen recordings

![Screenshot_2024-11-14-20-18-54-00_56635af9b6ad4512d4187a5a49185a25](https://github.com/user-attachments/assets/528fd8f3-e598-481f-b91f-00fb4bebaeb9)
As you can see in the s.s. I am not able to play song even after I'm logged in.
Has YTM struck again?

I did try to find duplicate of this issues but as of now it doesn't seem to. That's why I'm making this issue.

### Logs

...

### InnerTune version

0.5.10

### Android version

Android 14, Realme UI 5

**Comment by H3T-Shah** [comment]
#397 seems a similar one but it's on a release candidate version. If this issue is not necessary feel free to close it.

**Comment by mikedizhur** [comment]
Can't reproduce on latest debug version. Did you really try the debug version?

**Comment by MedwardR** [comment]
I can confirm this issue on 0.5.11-rc1

try this song
![Screenshot_20241114-182210_InnerTune.png](https://github.com/user-attachments/assets/f441c770-1a5f-4431-bde4-9533c5fa9aad)

**Comment by Malopieds** [comment]
Works fine for for both signed and non signed in, please make sure you tried with the [latest debug version](https://github.com/Malopieds/InnerTune/actions/runs/11869476064/artifacts/2196427027). On what (if not all) songs is it happening for you? Do you have a vpn?

**Comment by goelvatsal** [comment]
Happens to me as well, with any songs that I play that haven't been downloaded or cached.

**Comment by H3T-Shah** [comment]
Well I don't really no myself what caused that erroe

**Comment by H3T-Shah** [comment]
Well I don't really no myself what caused that error, but it resolved itself.

**Comment by Frer1** [comment]
Hola.

Creo que de alguna manera "dañé la app.

No puedo reproducir ninguna canción, he actualizado, he borrado datos "caché", incluso eliminé la app he instalé versiones anteriores y nada ha funcionado.

Hasta he creado un usuario, creyendo que quizás así funcione, pero no, no ha funcionado.

Sinceramente creo que por alguna razón he roto la App.

**Comment by H3T-Shah** [comment]
> Hola.
> 
> Creo que de alguna manera "dañé la app.
> 
> No puedo reproducir ninguna canción, he actualizado, he borrado datos "caché", incluso eliminé la app he instalé versiones anteriores y nada ha funcionado.
> 
> Hasta he creado un usuario, creyendo que quizás así funcione, pero no, no ha funcionado.
> 
> Sinceramente creo que por alguna razón he roto la App.

¿Iniciaste sesión con tu cuenta de Google? La opción está disponible en Configuración -> Contenido. Si cree que ha dañado la instalación, le aconsejo que desinstale la aplicación y reinstale la última versión. (Traducido con Google)

**Comment by H3T-Shah** [comment]
> Works fine for for both signed and non signed in, please make sure you tried with the [latest debug version](https://github.com/Malopieds/InnerTune/actions/runs/11869476064/artifacts/2196427027). On what (if not all) songs is it happening for you? Do you have a vpn?

I will try this. Untill now it's not for any specific song, literally every song that I haven't cached or downloaded is bringing up this issue.

**Comment by Frer1** [comment]
> > Hola.
> > Creo que de alguna manera "dañé la app.
> > No puedo reproducir ninguna canción, he actualizado, he borrado datos "caché", incluso eliminé la app he instalé versiones anteriores y nada ha funcionado.
> > Hasta he creado un usuario, creyendo que quizás así funcione, pero no, no ha funcionado.
> > Sinceramente creo que por alguna razón he roto la App.
> 
> ¿Iniciaste sesión con tu cuenta de Google? La opción está disponible en Configuración -> Contenido. Si cree que ha dañado la instalación, le aconsejo que desinstale la aplicación y reinstale la última versión. (Traducido con Google)

Hola, gracias por responder.

Si, hice todo lo que comentas.

Eso de eliminar la App y reinstalar una nueva versión lo hice no menos de dos veces y no funcionó.

Intentaré de nuevo

*Actualizo*

Descargué nuevamente la App (versión más reciente) y nada de nada.

Quizás eliminé algún *archivo importante* que hacía que la App funcionara, es lo único que se me ocurre.

Porque es raro que no funcione ninguna versión, quizás de tanto eliminar y reinstalar  metí la pata.

**Comment by H3T-Shah** [comment]
La única solución que se me ocurre es utilizar VPN.

**Comment by H3T-Shah** [comment]
> Works fine for for both signed and non signed in, please make sure you tried with the [latest debug version](https://github.com/Malopieds/InnerTune/actions/runs/11869476064/artifacts/2196427027). On what (if not all) songs is it happening for you? Do you have a vpn?

I tried debug version. For both signed in and not signed in the music doesn't plays. And it's not for any specific type of music.

**Comment by Frer1** [comment]
Acabo de descargar la versión 5.12 y por ahora funciona bien.

No la he probado en profundidad, pero por lo menos reproduce las canciones, las otras versiones no reproducían ninguna.

Gracias.
