### ISSUE TITLE
Downloads error

### ISSUE THREAD

**Issue by Maarruuu** [Malopieds/InnerTune#400]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. I download a song
2. It fails to download(download failed error)
3. This is happening on Mobile data. I do not know about normal internet since iam cut off from it
4. Some already downloaded songs don't work if i don't remove them and listen to them on data

### Expected behavior

It should download and work offline

### Actual behavior

It doesn't 

### Logs

Iam really not that professed in this stuff. 

### InnerTune version

0.5.10

### Android version

Android 11

**Comment by Malopieds** [comment]
Use the latest release candidate
