### ISSUE TITLE
Getting An "Unknown error" Approximately Between 27-30 sec into The songs.

### ISSUE THREAD

**Issue by Nandkishor01** [Malopieds/InnerTune#401]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open app 
2. Play any song for nearly 30s 
3. And you will get an Unknown error

### Expected behavior

Songs should continue as usual.

### Actual behavior

Songs Throws an unknown error after approx 30s into any song.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/e61edebe-8872-47c7-aab8-909ca6dd688d

![Screenshot_20241119-021339_InnerTune](https://github.com/user-attachments/assets/9777923a-f078-4ed8-9776-2e02ac51d8a4)
![Screenshot_20241119-021319_InnerTune](https://github.com/user-attachments/assets/b18adfa5-7220-4fea-a92f-0f5167031f37)

### Logs

Not avaliable.

### InnerTune version

0.5.10

### Android version

Android 13

### Additional information

I guess it is something related to login Bug a while ago.

Youtube Testing new ways to Force login ?

**Comment by Nandkishor01** [comment]
Yep Can confirm it's ytm trying to force login again.

**Comment by Malopieds** [comment]
I can play every song (including this one) fine. Are you signed in? Can you reproduce this on the [latest debug build](https://github.com/Malopieds/InnerTune/actions/runs/11869476064/artifacts/2196427027) ?

Edit if not, please provide logs.

**Comment by Nandkishor01** [comment]
When I logged in and logged out the problem went away.

Sorry for inconvenience 
And thank you.
