### ISSUE TITLE
Icon changes

### ISSUE THREAD

**Issue by zettaexa** [Malopieds/InnerTune#404]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I like the new icon however I think the logo is too close to the icon edges + an option to change to original to maintain consistency with the Media player

![Screenshot_20241119-152920](https://github.com/user-attachments/assets/40d945a3-db2e-46e5-a087-14ab1f145f1c)

### Why do you want this feature?

![Screenshot_20241119-152959](https://github.com/user-attachments/assets/6953d0a7-f938-416c-b987-3e9d0d24665f)
Maybe try spacing it a bit back + I know that there would be some people that would rather prefer the old icon than the new one so an option to change between that would be good (kind of how like Discord/Twitter does it)

**Comment by MillionsToOne** [comment]
No, instead the media player icon should be changed to the new one. I think this app is more than a fork of InnerTune

**Comment by MillionsToOne** [comment]
So it deserves its own identity.

**Comment by zettaexa** [comment]
> No, instead the media player icon should be changed to the new one. I think this app is more than a fork of InnerTune

Yes, as I said I like the new icon, but can you please fix the quick access media player to have it so it stays consistent?  or an option to switch between that if you don't really want to fix it
