### ISSUE TITLE
Offline mode is not responding

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#41]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When I open an online song while offline and the connection error appears, then I go to the liked songs or offline music list to play any downloaded song, it does not respond.

### Expected behavior

The downloaded songs should be played

### Actual behavior

Downloaded songs not responding

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/cfa00271-fe27-4c13-85c7-0e5bec7f47c9

### Logs

.

### InnerTune version

0.5.5 debug version

### Android version

11 and 15

**Comment by Malopieds** [comment]
Yep, I can reproduce this one but I have no clue where it's coming from...

**Comment by mostafaalagamy** [comment]
App crash 

Check this 


https://github.com/Malopieds/InnerTune/assets/80542861/582bc8a8-548a-4f23-8c16-ab7a6dac0f1d

**Comment by mostafaalagamy** [comment]
> App crash 
> 
> Check this 
> 
> 
> https://github.com/Malopieds/InnerTune/assets/80542861/582bc8a8-548a-4f23-8c16-ab7a6dac0f1d
> 
> 

@Malopieds
