### ISSUE TITLE
Add automatic adding suggested songs to queue at the end of playlist.

### ISSUE THREAD

**Issue by Dzheremi2** [Malopieds/InnerTune#413]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add ability to automatically add suggested tracks to end of the queue at the end of playlist playing, like it is in official YTM client.

### Why do you want this feature?

As user of official YTM, I have accustomed that playing queue never ends, and new tracks adds to it automatically.

### Additional information

![Screenshot_20241126-201817](https://github.com/user-attachments/assets/cd7a3278-f0b7-4665-8e8f-2e810159b6c1)

**Comment by zettaexa** [comment]
You can already do that?

**Comment by Dzheremi2** [comment]
> You can already do that?

No I can't. In the original InnerTune app there is an option to enable it. But it's not presented in this app

**Comment by Malopieds** [comment]
Yes it does, go to the settings => content => scroll to the bottom.
