### ISSUE TITLE
Songs are not playing anymore.

### ISSUE THREAD

**Issue by vedantanna** [Malopieds/InnerTune#419]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play any song

### Expected behavior

Song should play

### Actual behavior

Song is not playing 

### Screenshots/Screen recordings

![Screenshot_2024-11-30-22-21-22-935_com malopieds innertune](https://github.com/user-attachments/assets/2281021a-ebbe-4136-9015-464bb253e632)

### Logs

adb logcat

### InnerTune version

0.5.11

### Android version

Android 14

**Comment by Malopieds** [comment]
#410
