### ISSUE TITLE
Issue no #9 is back again

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#42]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When listening to a song from the search, the image of the artist specific to the song appears blank inside the Keep Listening "[issue #9](https://github.com/Malopieds/InnerTune/issues/9)", and this is due to issue [#19](https://github.com/Malopieds/InnerTune/issues/19).

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_2024-04-03-12-32-00-496_com zionhuang music debug](https://github.com/Malopieds/InnerTune/assets/80542861/4f552ca5-8507-49d8-9336-a6b4914c0b6e)

### Logs

No

### InnerTune version

0.5.5 debug version

### Android version

11 and 15

**Comment by Malopieds** [comment]
I don't see how it's related to #19. I cannot reproduce it with any artist, could you send the profile of this artists? Do you see this artist in the stats screen / is there a profile picture there?

**Comment by mostafaalagamy** [comment]
> I don't see how it's related to #19. I cannot reproduce it with any artist, could you send the profile of this artists? Do you see this artist in the stats screen / is there a profile picture there?

It's not actually an artist's name but the name of the album. However, the app has switched them, so I'm telling you it's related to issue "#19". 
The problem occurs when playing a song from search results where the album name appears as the artist. Do you understand me?

**Comment by Malopieds** [comment]
> It's not actually an artist's name but the name of the album

Please send the link so I can try to reproduce it

**Comment by mostafaalagamy** [comment]
> > It's not actually an artist's name but the name of the album
> 
> Please send the link so I can try to reproduce it

Search for the name ' أصحاب الأرض ' then play the first song in the songs section as shown in the screenshot.

![IMG-20240403-WA0006.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/dc1cf132-26c9-436e-a354-4eafef3503b0)

**Comment by mostafaalagamy** [comment]
> > It's not actually an artist's name but the name of the album
> 
> Please send the link so I can try to reproduce it

Search for the name ' أصحاب الأرض ' then play the first song in the songs section as shown in the screenshot.

![IMG-20240403-WA0006.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/dc1cf132-26c9-436e-a354-4eafef3503b0)

**Comment by Malopieds** [comment]
So would that be good?
![Screenshot_20240403-174328_1.png](https://github.com/Malopieds/InnerTune/assets/74783202/0b165c96-fcfe-44b7-8546-4ef34608da5e)

**Comment by mostafaalagamy** [comment]
> So would that be good?
> ![Screenshot_20240403-174328_1.png](https://github.com/Malopieds/InnerTune/assets/74783202/0b165c96-fcfe-44b7-8546-4ef34608da5e)

Yes , but YouTube changes the API a lot ! , Are there no other solutions or ideas to solve the API issue?

**Comment by Malopieds** [comment]
> Yes , but YouTube changes the API a lot ! , Are there no other solutions or ideas to solve the API issue?

I'm not sure it was really a Youtube API change but rather an edge case. I tried a more solid solution but we'll have to test it out. I'd like to produce a stable release before the end of the week. What do you think about the lasts version? Is it stable enough to be used ?

**Comment by mostafaalagamy** [comment]
> > Yes , but YouTube changes the API a lot ! , Are there no other solutions or ideas to solve the API issue?
> 
> I'm not sure it was really a Youtube API change but rather an edge case. I tried a more solid solution but we'll have to test it out. I'd like to produce a stable release before the end of the week. What do you think about the lasts version? Is it stable enough to be used ?

All day long, I've been testing it , and I believe the version is good for launch, If I encounter any other issues today, I will inform you ,thank you very much for this great work.

**Comment by mostafaalagamy** [comment]
When listening to a song and the artist is future 'more than one artist', it appears in the keep listening without an image.

![Screenshot_2024-04-05-03-03-33-39_5399807b941effa97489f80037469fbd.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/7a3340a7-1f65-4c33-9a2a-4e3c90f5f458)

Like this song!

https://music.youtube.com/watch?v=Rr1Cdli5nE8

**Comment by Malopieds** [comment]
Oh yes, because those artists doesn't really exists, therefore it's impossible to have an image for them. I don't know how I can resolve this...

**Comment by mostafaalagamy** [comment]
> Oh yes, because those artists doesn't really exists, therefore it's impossible to have an image for them. I don't know how I can resolve this...

Yes, the solution could be to remove the display of artists in the Keep Listening list and only retain the display of albums and songs.

**Comment by Malopieds** [comment]
> Yes, the solution could be to remove the display of artists in the Keep Listening list and only retain the display of albums and songs. 

No, I think it's too much for a minority of songs.
I'll try to think at something better.

**Comment by mostafaalagamy** [comment]
> > Yes, the solution could be to remove the display of artists in the Keep Listening list and only retain the display of albums and songs. 
> 
> No, I think it's too much for a minority of songs.
> I'll try to think at something better.

It has been removed , I think that's enough, thanks .
