### ISSUE TITLE
App crash on lyrics load

### ISSUE THREAD

**Issue by watashinosoulsociety** [Malopieds/InnerTune#427]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Any song 
Lyrics section 
Click search lyrics 
App crashes 

### Expected behavior

App don't crash :/ 

### Actual behavior

App crashes 

### Screenshots/Screen recordings

Imp video 

https://github.com/user-attachments/assets/385dea54-1523-44dc-aa61-d5ecc7bef268

### Logs

I don't have logs 

### InnerTune version

0.5.12

### Android version

Android 13

### Additional information

None

**Comment by Malopieds** [comment]
I can't reproduce, so I will need logs :/

**Comment by watashinosoulsociety** [comment]
> I can't reproduce, so I will need logs :/

I'd give you those but how do I obtain em ??

**Comment by watashinosoulsociety** [comment]
Know what ? I think I'm not having the issue anymore gang
