### ISSUE TITLE
The playlists don't work with Google account.

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#43]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When I log in to my Google account, the Playlists stop working completely in the app.

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/c082a75e-7b62-41a1-a05c-58ee9fc528f4

### Logs

No

### InnerTune version

0.5.5 debug version

### Android version

11

**Comment by Malopieds** [comment]
All Youtube Music's playlists are working fine on all my devices, whether it's connected to a google account or not.

**Comment by mostafaalagamy** [comment]
> All Youtube Music's playlists are working fine on all my devices, whether it's connected to a google account or not.

"Strange indeed, but I'll close it until I fully investigate."
