### ISSUE TITLE
Songs not playing 

### ISSUE THREAD

**Issue by vedantanna** [Malopieds/InnerTune#435]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play any song.

### Expected behavior

Song should play 

### Actual behavior

This action is not supported 

### Logs

Don't know 

### InnerTune version

0.5.12

### Android version

Android 14

**Comment by Malopieds** [comment]
Duplicate of #433

**Comment by Hikari2w2** [comment]
Same problem, cant play any song, no fork is working rn

**Comment by MizxGaming** [comment]
Many invidious instances also stopped working over the course of the last 4-5 months. 

Is this some coincidence or is YouTube just being an arsehole? Also if possible to solve this somehow, is it being worked on currently (InnerTune)?
