### ISSUE TITLE
Rearrange some components of the player UI

### ISSUE THREAD

**Issue by SiddhantRakh** [Malopieds/InnerTune#44]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

 * Move lyrics button to the loop button position.
 * Combine loop and shuffle buttons in bottom bar.
 * Access queue by swiping up (removes bottom bar).
This simplifies the interface and keeps frequently used controls (lyrics, playback) easily accessible.
![Screenshot_20240403-183723_InnerTune~5](https://github.com/Malopieds/InnerTune/assets/42494931/1d00dffe-864b-412d-921a-762dac3dfd63)
![Screenshot_20240403-183729_InnerTune~2](https://github.com/Malopieds/InnerTune/assets/42494931/56ba49c3-18ce-4a78-b5df-8ac634917e16)

### Why do you want this feature?

This simplifies the UI and removes the need of two bars. 

### Additional information

Thanks

**Comment by Malopieds** [comment]
First of all, imo removing the button for accessing the queue is not something we should do. How a new user would know how to access it. It's not something intuitive that you can guess. I don't see why removing the bottom bar is essential ? The three dots should not be placed here, if they would be moved it would be at the top corner.

**Comment by SiddhantRakh** [comment]
> First of all, imo removing the button for accessing the queue is not something we should do. How a new user would know how to access it. It's not something intuitive that you can guess. I don't see why removing the bottom bar is essential ? The three dots should not be placed here, if they would be moved it would be at the top corner.

The new UI has all icons, but only three I use frequently are at the bottom, making it look unbalanced. Ideally, only the queue button would be there, possibly with an arrow icon, for a clean look. I just want the new player UI to once again look minimal as it looks kinda cluttered now.

**Comment by SiddhantRakh** [comment]
I think I should move this to discussions so that we can take multiple opinions before finalising a design.

**Comment by Malopieds** [comment]
Yep that's a good idea since it won't be in the next release !
