### ISSUE TITLE
Sowing only 100 songs after importing a playist with more than 100 songs

### ISSUE THREAD

**Issue by dainvincible1** [Malopieds/InnerTune#449]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Import a playlist with more than 100 songs

### Expected behavior

it should import all the songs from the playlist

### Actual behavior

it imports only 100 songs from the playlist

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/a8138f2f-7994-4a0c-a4fe-41ee974d96c4

### Logs

dont know how to get logs

### InnerTune version

0.5.13

### Android version

14

**Comment by zettaexa** [comment]
Press the circle with 2 arrows, that is the playlist sync button, Wait for a moment (it would take about a minute at worst) and it would give you all of the songs in the playlist

**Comment by dainvincible1** [comment]
> Press the circle with 2 arrows, that is the playlist sync button, Wait for a moment (it would take about a minute at worst) and it would give you all of the songs in the playlist

Thanks, it worked
