### ISSUE TITLE
Open links in InnerTune

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#45]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When the app is in idle mode and I click on a song link to open it in InnerTune, it doesn't play. But when I click on the link again and the app is active, it plays normally.

### Expected behavior

It should work normally the first time 

### Actual behavior

It only works the second time 

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/db43f53f-e745-4431-9f93-b6d971db5e90

### Logs

No

### InnerTune version

0.5.5 debug version

### Android version

11 and 15

**Comment by mostafaalagamy** [comment]
I think it should be like this.


https://github.com/Malopieds/InnerTune/assets/80542861/cc7cd98b-4062-4999-8298-3d021300b6a8

**Comment by Malopieds** [comment]
It's only because you're using the debug version. Otherwise it works flawlessly.

**Comment by mostafaalagamy** [comment]
> It's only because you're using the debug version. Otherwise it works flawlessly.

The issue still exists!
