### ISSUE TITLE
Mood and genres not working properly

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#47]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When choosing one of the mode and genres options, the playlists doesn't open

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/80542861/03e9f706-1e4e-4565-8c18-d0a0c3f917dd

### Logs

No

### InnerTune version

0.5.5 debug version

### Android version

12

**Comment by mostafaalagamy** [comment]
The issue still exists!

**Comment by Malopieds** [comment]
Yes, I need to parse the json once and for all for this... I'll try when I have some time !
