### ISSUE TITLE
There are no dynamic lyrics 

### ISSUE THREAD

**Issue by houyan0111** [Malopieds/InnerTune#49]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There are no dynamic lyrics (English songs have them), version 0.5.3 does not have this problem

### Why do you want this feature?

I like to listen to music with dynamic lyrics
I like to listen to music with dynamic lyrics

### Additional information

I think Kugou didn’t work

**Comment by Malopieds** [comment]
Yep. The lyrics are bad, I will implement another source and try to fix this one. I'll close this issue in favor to #27
