### ISSUE TITLE
When selecting song, song is being skipping and other song starts playing

### ISSUE THREAD

**Issue by PsychoAsylum** [Malopieds/InnerTune#5]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

It happens randomly but
1. Go to Artists
2. Select one and go to song section
3. Select song

### Expected behavior

Selected song should play

### Actual behavior

Selected song is being skipped and other song starts playing

### Screenshots/Screen recordings

![Media_240322_200530](https://github.com/Malopieds/InnerTune/assets/72300906/561923ff-4ee6-4056-802f-7ce9f46e6f05)

### Logs

I have no logs

### InnerTune version

0.5.5

### Android version

Android 10

**Comment by Malopieds** [comment]
Hi, I think your two issues (this one and #4 ) are related and it comes from the MiniPlayer swipe implementation. I thought the fix I added was enough but it's not ready. I can provide you with a fix that remove the swipe action on the mini player only, so that you will be able to test and tell me if it works better.

**Comment by PsychoAsylum** [comment]
Hi, you might be right because before it was implemented i haven' noticed this issue. If its po

**Comment by PsychoAsylum** [comment]
Hi, You might be right because before it was implemented I haven't noticed those issues. If it is possible i will gladly test that.

**Comment by siggi1984** [comment]
> ### Checklist
> 
>     * [x]  I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
> 
>     * [x]  I've checked that there is no open or closed issue about this bug.
> 
>     * [x]  This issue contains only one bug.
> 
>     * [x]  The title of this issue accurately describes the bug.
> 
> 
> ### Steps to reproduce the bug
> 
> It happens randomly but
> 
>     1. Go to Artists
> 
>     2. Select one and go to song section
> 
>     3. Select song
> 
> 
> ### Expected behavior
> 
> Selected song should play
> ### Actual behavior
> 
> Selected song is being skipped and other song starts playing
> ### Screenshots/Screen recordings
> 
> ![Media_240322_200530](https://private-user-images.githubusercontent.com/72300906/316141699-561923ff-4ee6-4056-802f-7ce9f46e6f05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzY3MjcsIm5iZiI6MTcxMTEzNjQyNywicGF0aCI6Ii83MjMwMDkwNi8zMTYxNDE2OTktNTYxOTIzZmYtNGVlNi00MDU2LTgwMmYtN2NlOWY0NmU2ZjA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE5NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTBlMjRjMGU0NmQ3MGQwZjUzNmZjZTZmYjZlZTIzZTM3NTVlNGU4YmE3ODM1YTA5YzNlNTkxNmNiZjg4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVASsQGK37a66avYvZsriEQh7pmi6vhT1ZNSxU51lYg) [ ![Media_240322_200530](https://private-user-images.githubusercontent.com/72300906/316141699-561923ff-4ee6-4056-802f-7ce9f46e6f05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzY3MjcsIm5iZiI6MTcxMTEzNjQyNywicGF0aCI6Ii83MjMwMDkwNi8zMTYxNDE2OTktNTYxOTIzZmYtNGVlNi00MDU2LTgwMmYtN2NlOWY0NmU2ZjA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE5NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTBlMjRjMGU0NmQ3MGQwZjUzNmZjZTZmYjZlZTIzZTM3NTVlNGU4YmE3ODM1YTA5YzNlNTkxNmNiZjg4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVASsQGK37a66avYvZsriEQh7pmi6vhT1ZNSxU51lYg) ](https://private-user-images.githubusercontent.com/72300906/316141699-561923ff-4ee6-4056-802f-7ce9f46e6f05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzY3MjcsIm5iZiI6MTcxMTEzNjQyNywicGF0aCI6Ii83MjMwMDkwNi8zMTYxNDE2OTktNTYxOTIzZmYtNGVlNi00MDU2LTgwMmYtN2NlOWY0NmU2ZjA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE5NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTBlMjRjMGU0NmQ3MGQwZjUzNmZjZTZmYjZlZTIzZTM3NTVlNGU4YmE3ODM1YTA5YzNlNTkxNmNiZjg4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVASsQGK37a66avYvZsriEQh7pmi6vhT1ZNSxU51lYg) [ ](https://private-user-images.githubusercontent.com/72300906/316141699-561923ff-4ee6-4056-802f-7ce9f46e6f05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMzY3MjcsIm5iZiI6MTcxMTEzNjQyNywicGF0aCI6Ii83MjMwMDkwNi8zMTYxNDE2OTktNTYxOTIzZmYtNGVlNi00MDU2LTgwMmYtN2NlOWY0NmU2ZjA1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE5NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTBlMjRjMGU0NmQ3MGQwZjUzNmZjZTZmYjZlZTIzZTM3NTVlNGU4YmE3ODM1YTA5YzNlNTkxNmNiZjg4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVASsQGK37a66avYvZsriEQh7pmi6vhT1ZNSxU51lYg)
> ### Logs
> 
> I have no logs
> ### InnerTune version
> 
> 0.5.5
> ### Android version
> 
> Android 10
> ### Additional information
> 
> _No response_

I have the same problem
Android 12
Samsung Galaxy a21s

**Comment by mostafaalagamy** [comment]
This problem is related to swiping in the media player. I actually tried to fix this and did not succeed. If swiping is stopped, the problem will be solved.

**Comment by PsychoAsylum** [comment]
Strange thing is that while #4 this issue occours this problem goes away but also swiping functionality on mini player stops working.

**Comment by Malopieds** [comment]
Could you try and see if [this](https://github.com/Malopieds/InnerTune/releases/tag/v0.5.5-fix-miniplayer) solves both issues ?
I started to redesign a bit the player itself, could be nice to have some feedback too ! I will soon open a discussion on github to see what could be nice to have in term of UI.

**Comment by mostafaalagamy** [comment]
The problem was actually solved after deleting the swipe, and there is a suggestion to add the same new icons But below the media player

**Comment by Malopieds** [comment]
> there is a suggestion to add the same new icons But below the media player

Do you mean you think the new icons should be somewhere else ?

**Comment by PsychoAsylum** [comment]
Now without swipe on mini player i am unable to recreate both of those issues.
Thank you for solving this.

**Comment by mostafaalagamy** [comment]
Exactly! This approach helps maintain a cleaner and more organized layout.

**Comment by mostafaalagamy** [comment]
> > there is a suggestion to add the same new icons But below the media player
> 
> Do you mean you think the new icons should be somewhere else ?

Exactly! This approach helps maintain a cleaner and more organized layout.

**Comment by Malopieds** [comment]
> > > there is a suggestion to add the same new icons But below the media player
> > 
> > 
> > Do you mean you think the new icons should be somewhere else ?
> 
> Exactly! This approach helps maintain a cleaner and more organized layout.

Could you open a new issue maybe, with an image showing what you would like to see ?

**Comment by Malopieds** [comment]
Closing this one then
