### ISSUE TITLE
Searching for lyrics manually crashes the app

### ISSUE THREAD

**Issue by SiddhantRakh** [Malopieds/InnerTune#50]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song
2. Go to lyrics options menu
3. Tap Search and click ok
4. App crashes. 

### Expected behavior

The app should search the lyrics library for more lyric files. 

### Actual behavior

The app crashes instead. 

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/42494931/d7a04901-1996-4e10-85ba-f49a0d487162

### Logs

Sorry cant figure out how to get logs. 

### InnerTune version

0.5.6

### Android version

Android 12 

### Additional information

Bug found in pre-releases after 0.5.5 and still in 0.5.6. Not urgent, FYI.

**Comment by Malopieds** [comment]
Yes, I think the issue comes from the implementation of Kugou in this app. I need to rewrite everything. This also means it will be the same for #27 .

**Comment by SiddhantRakh** [comment]
> This also means it will be the same for #27 .

What do you mean by that?

**Comment by SiddhantRakh** [comment]
Btw I don't care to search lyrics manually if the automatically chosen file is time synced and accurate. Some songs which showed synced lyrics before (version 0.5.4 maybe) now don't which was not the case earlier. I really enjoy seeing synced lyrics on Innertune because of the gorgeous Lyrics UI but it's a hassle to find and paste lyrics each time while many other apps (especially RiMusic and ViTune - fork of ViMusic) handle it pretty well.
