### ISSUE TITLE
Hold to open song option menu

### ISSUE THREAD

**Issue by SiddhantRakh** [Malopieds/InnerTune#51]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In addition to tapping the three dots at the corner of each song I think it would be more intuitive to press and hold to open the song options menu.

### Why do you want this feature?

It seems to be pretty easy to implement and more intuitive. Also many similar apps like ViMusic, ViTune and almost all the major music streaming apps like Spotify, Apple Music and Tidal have this option and I am pretty used to holding rather than tapping the little three dots.

**Comment by Malopieds** [comment]
Yep I agree but still we have the multiselect (#12 ) that could also need the long press ability. I need to find a better way to implement everything...

**Comment by SiddhantRakh** [comment]
No problem. Also I have a minor grievance about the new ui. It's so small I thought it would be better to share here instead of a new issue: 
The layout button can be moved up as to remove the empty space which looks weird. 
![Screenshot_20240407-015657_InnerTune~2](https://github.com/Malopieds/InnerTune/assets/42494931/512fcba8-a928-4033-bcca-264433508de7)

**Comment by SiddhantRakh** [comment]
No problem. You can take your time and implement a stable way.

**Comment by Malopieds** [comment]
Closing it since it is now implemented.

**Comment by SiddhantRakh** [comment]
Thanks for implementing it. I have two issues with the current implementation:

1. it does not work on the songs of the artist page:
![Screenshot_20240410-190852_InnerTune Debug](https://github.com/Malopieds/InnerTune/assets/42494931/991ede5a-1650-41e1-b517-3b933b6c9c20)
2. Haptic feedback on holding to open the menu (like in Spotify for example)

**Comment by Malopieds** [comment]
> it does not work on the songs of the artist page

I'll check it out

> Haptic feedback on holding to open the menu (like in Spotify for example)

Can be a cool feature indeed.

Edit:
Fixed artists and implemented haptic feedback

**Comment by SiddhantRakh** [comment]
> Edit: Fixed artists and implemented haptic feedback

Thanks. It's working great.

**Comment by SiddhantRakh** [comment]
Hey, I just found out that the hold to open menu does not work in Search preview suggestions. It would be great if this gets fixed so to maintain uniformity of this behaviour. 

Here's a screenshot of the menu where it doesn't work:

![Screenshot_20240417-025836_InnerTune](https://github.com/Malopieds/InnerTune/assets/42494931/5503edfa-9d8f-497f-92a1-dd3ec34a7d46)

**Comment by SiddhantRakh** [comment]
Hey I just found out that the hold to open the menu is not implement or doesn't work at many more places:

1. In Library for Playlists, Albums and Artists.
![Screenshot_20240417-030927_InnerTune](https://github.com/Malopieds/InnerTune/assets/42494931/614d37b9-98a9-4d29-bf58-4870cf99ca8d)

2. In Search Results.
![Screenshot_20240417-031111_InnerTune](https://github.com/Malopieds/InnerTune/assets/42494931/adf196f9-a808-4e43-87af-a05a85bd2458)
 
3. In Search Suggestions. 
![Screenshot_20240417-025836_InnerTune](https://github.com/Malopieds/InnerTune/assets/42494931/4176ed67-cf64-4d85-a70a-2bee6ac3e965)

4. Also, there is no haptic feedback when accessing the menu in the queue. 
![Screenshot_20240417-031209_InnerTune](https://github.com/Malopieds/InnerTune/assets/42494931/62b8d0ed-63bc-432e-9355-d021c5c5e8bf)

Hope this gets fixed to maintain the uniformity of this enhancement.
