### ISSUE TITLE
Issue regarding Library tab chips UX

### ISSUE THREAD

**Issue by Username1-a** [Malopieds/InnerTune#52]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Those chips:
![Screenshot_20240406-150557_InnerTune Fork](https://github.com/Malopieds/InnerTune/assets/47947180/cbc7e499-90f4-4997-ba51-ad3210b96eeb)

1. Preferably, there should be an option for a user to specify which one of those chips (Playlists/Songs/Albums/Artists) to mark as default (so that the app would open with that chip enabled by default) and/or to have an option to remember the last viewed chip on the app startup;

2. Ideally, those chips should just be a swipeable tabs. Since you moved them away from bottom toolbar where they originally were, them being a swipeable tabs even if on top of the screen would be much better for reachability than those clickable chips (so you don't need to press the needed chip on top of the screen when you can just swipe left and right between them). it would just make sense UX-wise;

3. As of now, the app launches without any of those chips pressed for some reason, which shows some weird long list showing mix of albums and artist that weren't even put manually to the library or weren't liked by the user. In those albums, for example, there's usually just a 1 liked and listened track – I don't think that whole album should be put into a Library tab automatically. It makes no sense (seems like a bug, but idk).

### Why do you want this feature?

Better UX

### Additional information

Screenshot showing number 3. – none of the chips (Playlists/Songs/Albums/Artists) are pressed after the app launch, the list contains a weird mishmash of randomly added stuff (albums and artists) to the library based on 1-2 songs.

![Screenshot_20240406-153107_Lawnchair](https://github.com/Malopieds/InnerTune/assets/47947180/bd3ea981-53ad-47dc-bfae-4a13079ee50d)

**Comment by Malopieds** [comment]
> Preferably, there should be an option for a user to specify which one of those chips (Playlists/Songs/Albums/Artists) to mark as default (so that the app would open with that chip enabled by default) and/or to have an option to remember the last viewed chip on the app startup;

Yes I could do this.

> Ideally, those chips should just be a swipeable tabs. Since you moved them away from bottom toolbar where they originally were, them being a swipeable tabs even if on top of the screen would be much better for reachability than those clickable chips (so you don't need to press the needed chip on top of the screen when you can just swipe left and right between them). it would just make sense UX-wise;

I'll think about it. This might be over productive, costly in time and too much animations.

> As of now, the app launches without any of those chips pressed for some reason, which shows some weird long list showing mix of albums and artist that weren't even put manually to the library or weren't liked by the user. In those albums, for example, there's usually just a 1 liked and listened track – I don't think that whole album should be put into a Library tab automatically. It makes no sense (seems like a bug, but idk).

This is actually a mix of all your library. Consider it as a "All" chips. In addition, I agree about the library tab. I think only the artists added should be there automatically, and not just as it's currently done (it's from the songs you liked). It's destined to be changed in the future releases. There will also be a sorting possibility.
