### ISSUE TITLE
a Dark icon for the app

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#53]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

just a simple request : So, what about changing that app icon to a dark version as in the screenshot (I saw it at "About" in the app settings itself)
![Screenshot_2024-04-06-16-37-40-211_com zionhuang music_1](https://github.com/Malopieds/InnerTune/assets/156727749/ac19ce90-b2d3-42e9-a1c2-a04ab81a1f33)

### Why do you want this feature?

it just looks cool for me

### Additional information

Its not that important, I just Thought that it would look cool, what u think !?

**Comment by W1zardK1ng** [comment]
Future plan is to change the app name and icon, See [Suggestions for the new app name](https://github.com/Malopieds/InnerTune/discussions/34)

**Comment by Spaceshiprace** [comment]
yeah, but they're talking about changing the name of the app not the icon ?

**Comment by Malopieds** [comment]
> yeah, but they're talking about changing the name of the app not the icon ?

It will be both. Following in #34
