### ISSUE TITLE
Add playlists from yt music to the homescreen

### ISSUE THREAD

**Issue by amisukarei** [Malopieds/InnerTune#55]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

World be cool if the yt music playlists could be moved to the homescreen. 

![Screenshot_20240407_133435_InnerTune](https://github.com/Malopieds/InnerTune/assets/83230845/ccf41ebd-318c-4e79-9df7-7e01ed5d5414)
Instead of being here

![Screenshot_20240407_133446_InnerTune](https://github.com/Malopieds/InnerTune/assets/83230845/713438b8-15c7-436e-b500-dadbc61f3ef4)
Moved here somewhere 

### Why do you want this feature?

I have a lot of playlists and it would be nice to  be able to access them from home screen without having to tap on account first.

**Comment by Malopieds** [comment]
Yes I will look into it!
