### ISSUE TITLE
New Releases for Liked Artists

### ISSUE THREAD

**Issue by SiddhantRakh** [Malopieds/InnerTune#59]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

New releases page for artists that are liked by the user. It does not have to look really what's new for the user but just sort the songs, albums and singles of liked artists by date in a descending order. User can have option fo filter between songs, artists and albums releases like the library tab. 

### Why do you want this feature?

I would love if there was a way to check new releases from my liked artists in the app. Also it can be a good addition to the newly added explore tab. 

### Additional information

Spotify has the same thing implemented in a basic way but I don't like Spotify implementation as it does not distinguish between songs, albums and singles. Instead of the Music and Podcasts tab there should be 3 tabs: Songs, Singles and Albums so we can filter the new releases.
Here's a simple screenshot which describes my request:
![Screenshot_20240409-190946_Spotify](https://github.com/Malopieds/InnerTune/assets/42494931/42b74e40-0172-492b-9f30-76f7d3b4ea60)

**Comment by Malopieds** [comment]
2 options there:
- sort the new releases in the explore tab by artists liked (i.e. there will be no extra row in the explore tabs)
- do an extra row, specially for the artists you liked
I personally think that having too many rows that have the same purpose is counter intuitive. What do you think?

**Comment by SiddhantRakh** [comment]
The current implementation just shows random artists based on country so I think we can replace it with this new idea. 
Also the current implementation only shows albums can we rename the carousel to New Releases and show a scrolling preview and when user expands it we get a new UI in which the releases are sorted by date in a layout similar to the one in the library tab. I think the current grid layout is not that much effective. 
Here's a visual representation:
![Screenshot_20240410-013140_InnerTune](https://github.com/Malopieds/InnerTune/assets/42494931/66202fa0-993a-4821-84f9-df4dc1d3efa1)

**Comment by Malopieds** [comment]
> The current implementation just shows random artists based on country so I think we can replace it with this new idea.

It's not random. Those are albums and singles that were released the previous week. Also they're not artists, so I quite doesn't understand what you're saying.

> Also the current implementation only shows albums

No, it's both albums and singles.

> can we rename the carousel to New Releases and show a scrolling preview

What so you mean by that? The name has already new release in it. A scrolling preview of what?

> new UI in which the releases are sorted by date in a layout similar to the one in the library tab

There would be only one (or two...) tabs albums (and singles). Also  AFAIK, releases are (almost) all on the same day, i.e. Friday (internationally I think). So it does not make sense to sort it by date. In addition I don't know if YouTube give this data.

**Comment by SiddhantRakh** [comment]
Ok then we can just add a basic filter which shows only the releases of the liked artists and since you said there can be only 2 tabs (Albums and Singles) it's ok to keep them combined in a single scrolling list. 
If YouTube does not provide data for such implementation then you are free to close this issue as i think most people use other third party apps for this purpose. I just thought it would be a great simple addition (enhancement )to the explore tab.

**Comment by Malopieds** [comment]
> Ok then we can just add a basic filter which shows only the releases of the liked artists and since you said there can be only 2 tabs (Albums and Singles) it's ok to keep them combined in a single scrolling list.

But if we do that there is no difference with just showing always the liked artists first in the scrolling list.

**Comment by Malopieds** [comment]
Hi, I checked (and implemented something). Youtube only send the first 24 new releases in the explore page. I'm now sorting those based on:
- if they are from artists liked, they are sorted based on the time you listened to them.
- if you have ever listened to those artists it will be ordered by time.
If you want to see the reality of this (i.e. with all youtube music data, you have to click on the arrow of New Release albums.

I cannot do better right now since youtube music doesn't send more data.

**Comment by Malopieds** [comment]
Ok I found an alternative, it takes more time to load but that's still ok. It now should work flawlessly. Try it out and tell me !

**Comment by SiddhantRakh** [comment]
I tried if out and yes it's working great. It is loading fast for me maybe due to the fact that I only have around 10 liked artists. I think it's good enough for me. But I have a two small final suggestions before closing this issue. 

1. Can we add a way to show only the liked artist releases after the full list has loaded. Maybe two tabs at the top called All and Liked will do the job. (I know it might not be possible because of less metadata but can we do it after the list has loaded?)

2. Also we can rename the 'New release albums' to 'New Releases' as it includes both albums and singles (about which i was confused too initially).

**Comment by Malopieds** [comment]
> Can we add a way to show only the liked artist releases after the full list has loaded. Maybe two tabs at the top called All and Liked will do the job. (I know it might not be possible because of less metadata but can we do it after the list has loaded?)

I don't understand the point of this actually. Because they are in first it is the exact same thing if they are alone or not

> Also we can rename the 'New release albums' to 'New Releases' as it includes both albums and singles (about which i was confused too initially).

Yep I can do that

**Comment by SiddhantRakh** [comment]
Ok i got it while using the debug version i had liked only 4 artists which made me believe there was a need for more classification. You are right the current implementation serves the purpose very well.
