### ISSUE TITLE
Spotify canvas media screen.

### ISSUE THREAD

**Issue by owenconnorz** [Malopieds/InnerTune#60]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I'd like to see the canvas video look to the media player also found on SimpMusic but the development is slow.

### Why do you want this feature?

I like the look maybe others don't but this can be a option in the settings to disable and enable 

### Additional information

![Screenshot_20240410_203959_SimpMusic](https://github.com/Malopieds/InnerTune/assets/96526481/1fd345ef-c280-484a-9cc0-f259c47dbe14)

**Comment by Malopieds** [comment]
The thing with simpMusic is that it is based on Spotify (that provides the video on this format). Youtube music doesn't have this kind of video so it's not possible.

**Comment by owenconnorz** [comment]
I think it's actually based on yt music with this feature and is possible as I'm sure it's just an api integration 

The home screen is YouTube and syncs with it to

![Screenshot_20240410_214252_SimpMusic.jpg](https://github.com/Malopieds/InnerTune/assets/96526481/c9044139-08b4-41fc-86ae-8a74e3eb67ad)

**Comment by Malopieds** [comment]
For now at least, I have no plan to bring videos to InnerTune. Maybe later I will implement it but I want to keep things simple.
