### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by kaneryu** [Malopieds/InnerTune#61]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Multiselect allows you to select multiple songs at a time, then preform actions on that selection. Such as selecting 10 songs at once, then liking them all. Please make sure to add "select all" check boxes to albums and playlists, and add swipe select.

### Why do you want this feature?

I'm not sure if this is in the app already, but arguably the most important missing feature is *obviosuly* multi-select.

All jokes aside, multi-select being missing is really detrimental to the usefulness of the app

**Comment by Malopieds** [comment]
This has been implemented, please see #12
