### ISSUE TITLE
more detailed date for the releases

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#62]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

can u add the month that the releases was out in next to the year of the releases (just like in Spotify for example)

### Why do you want this feature?

sometimes i want to know what month an album or single was released in

### Additional information

I hope its a clear description

**Comment by Malopieds** [comment]
I don't think youtube send back those informations. I could check but basically, if it's not in the youtube music website it ca't be on InnerTune. I checked and it's not either on spotify. Maybe I didn't understand what you were asking for. Could you provide any pictures ?

**Comment by Spaceshiprace** [comment]
spotify the month of the release next to the year as you see :
![yjyoj24d6ba81_1](https://github.com/Malopieds/InnerTune/assets/156727749/e57a4100-b523-47d5-8552-618b9b2bf727)

**Comment by Malopieds** [comment]
Yep I checked spotify does provide it but not youtube music so it's not possible.

**Comment by Spaceshiprace** [comment]
ok then.
