### ISSUE TITLE
Sort date liked

### ISSUE THREAD

**Issue by siggi1984** [Malopieds/InnerTune#63]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can we have another sorting option for the songs and playlists?

Sort date liked

### Why do you want this feature?

I think the sorting is cool, so you could have your favorite songs by liked date, i.e. the last liked song is always at the top or vice versa.

**Comment by Malopieds** [comment]
In which screen do you want that ? If it's in the "Song" Library screen, it's already there under the name "date added" (same for the playlist)

**Comment by siggi1984** [comment]
> In which screen do you want that ? If it's in the "Song" Library screen, it's already there under the name "date added" (same for the playlist)

Yes the sorting by added date is available but if I like a song in this sorting it is sorted by date added to the library.

I would like to see when I like a song that it is at the top regardless of when it was added to the library. This is the case with YTM and spotify.

**Comment by siggi1984** [comment]
RiMusic has this sorting, see screenshot if that helps.

![Screenshot_20240412-210233](https://github.com/Malopieds/InnerTune/assets/103368536/ae7f56ba-5285-461b-9bd1-3a400c32b6a1)

**Comment by Malopieds** [comment]
Yeah but RiMusic stores all music that you listened right? So for pour case "Date Added" and "Date Favorited" are the same things so I don't get want you're asking for.

> I would like to see when I like a song that it is at the top regardless of when it was added to the library. This is the case with YTM and spotify.

It seems here that you want a pin feature

**Comment by siggi1984** [comment]
> Yeah but RiMusic stores all music that you listened right? So for pour case "Date Added" and "Date Favorited" are the same things so I don't get want you're asking for.
> 
> > I would like to see when I like a song that it is at the top regardless of when it was added to the library. This is the case with YTM and spotify.
> 
> It seems here that you want a pin feature

So if it works, it doesn't matter what the function is called, but if it's too complicated then please don't waste time or disfigure the UI, then please don't implement it.

**Comment by Malopieds** [comment]
It's not that I don't want/too complicated but rather I don't understand what do you want. From what I understand, you're asking for a feature that is already in the app.

**Comment by siggi1984** [comment]
All good, thank you for your time and hard work you put into the app. I don't want to waste your precious time.
