### ISSUE TITLE
Small change to the lock screen player

### ISSUE THREAD

**Issue by siggi1984** [Malopieds/InnerTune#64]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Pull the operating keys apart a little.

![Screenshot_20240412-212128_InnerTune_1](https://github.com/Malopieds/InnerTune/assets/103368536/6ee52f34-aefe-462a-b2f5-655255437d09)

### Why do you want this feature?

It would make operation easier because you wouldn't accidentally hit another button.

**Comment by mostafaalagamy** [comment]
> Pull the operating keys apart a little.\n\n

This is the Samsung music panel, not InnerTune, so it changes with every operating system. For example, on Oppo, it will look like this.

![Screenshot_2024-04-12-23-30-27-37_96b26121e545231a3c569311a54cda96.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/9ccff3d5-8d1c-496b-9b3a-b6fe46b8a555)

![Screenshot_2024-04-12-23-30-06-29.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/bdd313d8-c68f-4bf7-937c-dc2298014274)

**Comment by Malopieds** [comment]
Yes, AFAIK I cannot change this. It's only the manufacturer, are other applications able to do a different layout ?

**Comment by SiddhantRakh** [comment]
Maybe it's the five buttons that are causing this behaviour. I am also using One UI and this weird spacing issue is only present in the InnerTune's media player. I don't know exactly what might be causing it. Also the notification shade buttons look cramped too.
