### ISSUE TITLE
Version 0.5.7 only liked songs, artists, albums visible

### ISSUE THREAD

**Issue by siggi1984** [Malopieds/InnerTune#65]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

After installing the pre-release version 0.5.7, only liked songs, artists and albums are visible, all others in the library are no longer visible.
In my case. For example: I had over 2000 songs in the library of which 216 were liked, only the 216 songs are visible under the songs, what about the rest, the same with artists and albums.

### Expected behavior

I would like to see the old behavior that all songs, artists and albums are visible not only the liked ones.

### Actual behavior

X

### Logs

X

### InnerTune version

0.5.7

### Android version

Android 12

**Comment by Malopieds** [comment]
Yes, you are right. I didn't merged the previous "Add to library" to the "Liked" yet. I need to do this and everything will be "Liked" as of now.

**Comment by siggi1984** [comment]
> Yes, you are right. I didn't merged the previous "Add to library" to the "Liked" yet. I need to do this and everything will be "Liked" as of now.

Oh, okay, then I was a bit too hasty.

**Comment by Malopieds** [comment]
Hi, I think it's good practice to keep it open until I really fix it. It helps me with organization and not forgetting things!

**Comment by Malopieds** [comment]
> example: I had over 2000 songs in the library of which 216 were liked, only the 216 songs are visible under the songs

I have the fix for this.
> what about the rest, the same with artists and albums

The albums and artists will NOT be seen anymore. If you want to see an artist on there you have to like it, otherwise it's too messy.

Edit:
Feel free to reopen it/ask questions here if you think this is something that we can workaround
