### ISSUE TITLE
 Duplications in playlist

### ISSUE THREAD

**Issue by anxiouslelimo** [Malopieds/InnerTune#69]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When adding a song that is already in a playlist, a pop up that warns about it.

### Why do you want this feature?

It would resolve duplicating songs in playlists.

**Comment by Malopieds** [comment]
Should be implemented now ! Tell me if there is anything wrong with it.
