### ISSUE TITLE
Displays wrong artwork after changing track and turning lyrics on and off

### ISSUE THREAD

**Issue by PsychoAsylum** [Malopieds/InnerTune#7]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Start playing a song
2. Pressbnext song button
3. Now turn on lyrics and turn them off

### Expected behavior

It should show correct artwork

### Actual behavior

It shows artwork from previous song even though it showed correct one at the start

### Screenshots/Screen recordings

![Media_240322_223453](https://github.com/Malopieds/InnerTune/assets/72300906/fe2f1b1e-df72-4015-a05f-b824bee0f8da)

### Logs

Don't have

### InnerTune version

0.5.5 and 0.5.5 with " Fixing mini player problems"

### Android version

Android 10

**Comment by Malopieds** [comment]
When the build finishes, you can try the [latest debug version](https://github.com/Malopieds/InnerTune/actions), it fixes this issue, but maybe also #6 (that's a wild guess since I cannot reproduce it)

**Comment by PsychoAsylum** [comment]
This issue was solved but unfortunately #6 was not.
