### ISSUE TITLE
Open supported links by default 

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#72]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Instead of going to the app info, this feature lets you access the settings for default links automatically.

### Why do you want this feature?

You will make access to the settings faster and easier for everyone.

![Screenshot_2024-04-17-21-46-51-94_b30e2a162fc07e50d34f2e5a9b43b759](https://github.com/Malopieds/InnerTune/assets/80542861/4341309e-2008-4d20-85da-cea1c262c930)

**Comment by Malopieds** [comment]
What's this app ?
