### ISSUE TITLE
(BUG) No stream available 

### ISSUE THREAD

**Issue by zane17889900** [Malopieds/InnerTune#74]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Step 1 go to my playlist or search for a song, attempt to play it, error occurs

### Expected behavior

The music should play

### Actual behavior

Music refuses to play and instead says no stream available

### Screenshots/Screen recordings

![Screenshot_20240420-140614](https://github.com/Malopieds/InnerTune/assets/133840877/7e269cee-146c-4971-89ff-8faf6de69032)

### Logs

Unable to get logs

### InnerTune version

0.5.6

### Android version

Android 14

**Comment by Malopieds** [comment]
Plays fine for me. Share the song/your db otherwise I can't help.

**Comment by zane17889900** [comment]
I managed to find out what it was, it was an issue with my backup. I had to uninstall the app, then play all the songs that said no stream available, then restore from my backup and then they worked again.

**Comment by anxiouslelimo** [comment]
I too had this issue recently and did accordingly. But then i figured out that it was playing from the cache. Once i cleared the cache (from Innertune settings) the error happens again. @zane17889900 Can you try and see. If the issue remains can you reopen.

> I managed to find out what it was, it was an issue with my backup. I had to uninstall the app, then play all the songs that said no stream available, then restore from my backup and then they worked again.
