### ISSUE TITLE
 Choose to use Kugou or lerclib manually

### ISSUE THREAD

**Issue by houyan0111** [Malopieds/InnerTune#78]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can I choose to use Kugou or lerclib manually? For me, Kugou is better. 
The lyrics of lrclib cannot be synchronized with the song time.

### Why do you want this feature?

Kugou is better

**Comment by szaszlyki21** [comment]
Lrclib has synced lyrics, you can check if your song has them on their website: https://lrclib.net/

**Comment by SiddhantRakh** [comment]
I am getting synced lyrics from lrclib.net almost for all the songs. I know it depends upon the songs played but lyrics of lrclib are definitely synchronised with time.

**Comment by Malopieds** [comment]
You can now choose either lrclib or kugou as your first result, but you can also disable one (or both) of them. If not disabled it will still choose the closest one (based on title and duration)
