### ISSUE TITLE
Download songs

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#79]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Have an option to download songs in a visible directory so you can back them up

### Why do you want this feature?

When moving phones it's really annoying to have to download songs again. A download feature would mean you could save them easily to usb or the cloud

**Comment by Malopieds** [comment]
Closing this issue, duplicate of #36
