### ISSUE TITLE
Media player new icons 

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#8]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

This approach helps maintain a cleaner and more organized layout.
and it will be easy to access items placed at the bottom.

### Why do you want this feature?

New media player new icons 
![24-03-22_23-29-18-364](https://github.com/Malopieds/InnerTune/assets/80542861/4662d062-98fd-4fe8-8c60-c878205c61e3)

**Comment by PsychoAsylum** [comment]
Just my thought, but i actually like those icons above. 
Placing all of those icons above would also allow for cleaner look but also to leave main functionality of the player at the buttom so that first thing you press is one of the main controls.

**Comment by Malopieds** [comment]
> Just my thought, but i actually like those icons above. Placing all of those icons above would also allow for cleaner look but also to leave main functionality of the player at the buttom so that first thing you press is one of the main controls.

Yep, I would agree with this too

**Comment by mostafaalagamy** [comment]
> Just my thought, but i actually like those icons above. 
> Placing all of those icons above would also allow for cleaner look but also to leave main functionality of the player at the buttom so that first thing you press is one of the main controls.

It's possible to divide them between the top and the bottom.

**Comment by Malopieds** [comment]
Closing it (for now at least). I will keep the current design, but still open to some change.
