### ISSUE TITLE
Download status

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#82]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

On library screen an indicator against playlist to show if it's been downloaded 

### Why do you want this feature?

Not a big deal but at the moment you need to go into each playlist to see if you've downloaded it. Would be good to see it from the library screen with an icon indicating it against each playlist

**Comment by Malopieds** [comment]
Yes it can be a cool feature to have, why not. It won't be available for auto playlists (Liked, Offline, My Top -X)

**Comment by Lorestan00** [comment]
Awesome. Not technically possible for auto playlists?

**Comment by Malopieds** [comment]
> Awesome. Not technically possible for auto playlists?

Yes it's because auto playlists are not real playlists, they are automatically generated. So it's too costly to compute check on whether all the songs have been downloaded, etc...

**Comment by Lorestan00** [comment]
Oh I see that makes sense. If you could add it for manual playlists that would be great

**Comment by Malopieds** [comment]
Hi, after further investigation, I'm afraid that this is not possible for the moment.

**Comment by Lorestan00** [comment]
Oh okay. No way of surfacing the downloaded icon which appears in the actual playlist?

**Comment by Malopieds** [comment]
> No way of surfacing the downloaded icon which appears in the actual playlist?

It will be too costly, sorry :/
