### ISSUE TITLE
more enhancement for the stats

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#84]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

i think it would be cool if we can see how many times we played a single song.

### Why do you want this feature?

I want to know how many time I played a certain song sometimes..

**Comment by Malopieds** [comment]
Closing. Duplicate of #21.
