### ISSUE TITLE
Other Versions for albums

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#86]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

On Rimusic and Vimusic if you scroll down the album tracklist it shows you the other versions for the album (Also for the singles I think..)
the screenshot is not from Rimusic or Vimusic neither (its itunes)
![Screenshot_2024-04-30-19-08-20-717_org mozilla firefox_1](https://github.com/Malopieds/InnerTune/assets/156727749/b350b389-2fbf-4540-b66b-1f4aee5afb8c)

### Why do you want this feature?

because these versions doesn't appear if you search them

**Comment by SiddhantRakh** [comment]
This is a much needed feature. Many apps like ViTune have it. I did not realise it was missing in Innertune until your post.

**Comment by Spaceshiprace** [comment]
yea, I also noticed it lately.
