### ISSUE TITLE
No Stream Available

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#87]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search for the same song I played in the screenshot and try to play it

### Expected behavior

The song should play like any other song

### Actual behavior

it says "No Stream Available"

### Screenshots/Screen recordings

![Screenshot_2024-05-02-12-48-37-460_com zionhuang music_1](https://github.com/Malopieds/InnerTune/assets/156727749/65a3b51a-7ae4-4759-84a2-f471958df489)

### Logs

non

### InnerTune version

0.5.7

### Android version

Android

### Additional information

i tried the song on yt music and it plays without any issue

**Comment by Malopieds** [comment]
That's odd, it plays for me.
Does both sound have the same id?
You can check it out with :
- on innertune, three dots, details and check the media idea
- on ytm, settings, general, enable stats for nerds and when you play it, it should be there.

**Comment by Spaceshiprace** [comment]
the same id.
![327741015-bebaa88c-e83f-438e-9ffd-8a198edb43f3_1](https://github.com/Malopieds/InnerTune/assets/156727749/de6451c0-54e6-4aec-8b05-c22143486242)
![327741026-5b004918-9065-4645-9cb7-894924bf9d72_1](https://github.com/Malopieds/InnerTune/assets/156727749/e979f13e-ad59-4361-b228-a3c72e511abd)

**Comment by Spaceshiprace** [comment]
Update* : So i tried the debug version and the song plays without any issue, but I noticed that on the debug version the song bitrate is 169 kbps while on the stable version I'm using its 326kbps
Note : I turned the audio quality to " High" on the debug as well as the stable version I'm using
![Screenshot_2024-05-03-11-49-25-341_com zionhuang music debug_1](https://github.com/Malopieds/InnerTune/assets/156727749/82866706-b039-48b5-866b-725b56d275ce)
here's another song with same issue, also its bitrate is high just as the first song that I faced the issue with : 
![327846673-9a49f1b4-7887-4517-9c83-18904aa85cad_1](https://github.com/Malopieds/InnerTune/assets/156727749/0211a756-da98-412a-b950-fc07a0feda25)

**Comment by anxiouslelimo** [comment]
Happening for another song. Cleared app data. Song plays. Did a restore of the backup before the error. Song plays. Did a restore of the backup after the error and song doesn't play.

**Comment by Spaceshiprace** [comment]
I forget to close this issue cuz its fixed now, the issue was happening everytime I restore the backup and I still don't know why ? I still need a answer...

**Comment by anxiouslelimo** [comment]
@Spaceshiprace can you reopen the issue as the reason to why this happens is not yet sorted?

**Comment by anxiouslelimo** [comment]
@Malopieds https://github.com/Malopieds/InnerTune/issues/74

**Comment by Malopieds** [comment]
I have never encountered this issue and there is no way to reproduce it...

**Comment by anxiouslelimo** [comment]
[InnerTune_20240518120645.zip](https://github.com/Malopieds/InnerTune/files/15360334/InnerTune_20240518120645.zip)

@Malopieds Backup file. The song having issue is https://music.youtube.com/watch?v=0X9VZ7Nrlu8&si=UVkFka02YAqFcafx

**Comment by Richard38907** [comment]
I also have this issue on other forks of InnerTune due to a backup restoring.

**Comment by d4f5409d** [comment]
Same issue here with v0.5.7 and song: https://music.youtube.com/watch?v=1mEP02477z8

**Comment by Hikari2w2** [comment]
Same issue, restoring my backup is the problem
