### ISSUE TITLE
The new song or artist, it appears in the listening section without an image, displaying only the name.

### ISSUE THREAD

**Issue by mostafaalagamy** [Malopieds/InnerTune#9]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Start playing a song 
2. Go back to home and go to the keep listening section
3. You will find only the name without a photo 

### Expected behavior

When listening to a new song or artist, it appears in the listening section without an image, displaying only the name.

### Actual behavior

When listening to a new song or artist, it appears in the listening section without an image, displaying only the name.

### Screenshots/Screen recordings

![IMG-20240323-WA0000](https://github.com/Malopieds/InnerTune/assets/80542861/a65f3bdf-baaf-4ba7-947c-cc608b51471a)

### Logs

No logs

### InnerTune version

0.5.5

### Android version

10 and 14

**Comment by Malopieds** [comment]
You can try the [latest debug version](https://github.com/Malopieds/InnerTune/actions) it should fix this issue !

**Comment by mostafaalagamy** [comment]
> You can try the [latest debug version](https://github.com/Malopieds/InnerTune/actions) it should fix this issue !

The problem was solved with the songs but not the artists

**Comment by mostafaalagamy** [comment]
![Screenshot_20240323_014348.jpg](https://github.com/Malopieds/InnerTune/assets/80542861/bb800842-2e38-4a82-9771-8368907067fb)

this

**Comment by mostafaalagamy** [comment]
> You can try the [latest debug version](https://github.com/Malopieds/InnerTune/actions) it should fix this issue !

After a clean install again, the issue was resolved

**Comment by Malopieds** [comment]
Nice, closing it then.
