### ISSUE TITLE
Add a New section in the home page

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#90]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I wish if you could add a section just like this one in the sceenshot to the home page

### Why do you want this feature?

its a cool section gives you playlists from the community (users) themselves rather than other stupid playlists by yt music

**Comment by Malopieds** [comment]
This is from youtube music to a personal account based on what you listen. I don't have access to this unless you're logged in. I don't plan to add more logged in feature right now.

**Comment by Spaceshiprace** [comment]
okey then.
