### ISSUE TITLE
a new version...

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#92]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

will be there any new release soon ?

### Why do you want this feature?

cuz the app still has some bugs..

### Additional information

just a question.

**Comment by Malopieds** [comment]
There has been a new release, closing.

**Comment by Spaceshiprace** [comment]
@Malopieds thank you so much I've been waiting for it a long time ❤️
