### ISSUE TITLE
Make "AA", "Aa", "aa" and "Äa" just variations of "A"

### ISSUE THREAD

**Issue by darumanzane** [Malopieds/InnerTune#98]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![IMG-20240517-WA0005](https://github.com/Malopieds/InnerTune/assets/166534263/a0735b92-f26e-4405-a75f-ce3c2b1326d8)
Make "AURORA", "Amaarae", "aespa" and "Ängie" fall under the same category: "A".

### Why do you want this feature?

![IMG-20240517-WA0006](https://github.com/Malopieds/InnerTune/assets/166534263/6bfff187-f1fc-4e36-86bb-28afc018105d)
The way is implemented at the moment treats all this variations in lower and upper case (as well as special symbol vowels) as different, separate things. This results in the alphabetical order being inaccurate, because the way it orders artists is: UPPER CASE, UPPER-lower case, lower case and then special characters.

**Comment by darumanzane** [comment]
Hello!
Just wanted to check if there's any chance this gets implemented. I genuinely think this app is great and with this quality of life changes, the experience overall would improve a lot. Thanks for keep working on the app :)

**Comment by Malopieds** [comment]
Yep I've looked into it but I would need some example and what you expect from their output !

**Comment by darumanzane** [comment]
The app currently separates "A", "a" and "ä" as different things. That's the reason sorting in alphabetical order is inconsistent. If you take a look at the images I uploaded before, the app puts "SZA" first and then "Sabrina", that's cause it treats UPPER-CASE as a different things as a UPPER-lower case. Same thing can be noted with the second image: first sorts "Zella" and then it goes back to "a", in lower-case, to "aespa".
The ideal and logical output is: real alphabetical order, ignoring all the UPPER, lower, Mixed and special characters (example: ä, à, ã...) being treated as different things.
In this way, we would have "aespa" and "alt-J" in the same category as the rest of artist that also start with "A" (in UPPER-case), regardless of what type of characters they use.

Don't know if this explanation is better, so I'll try another way:
*CURRENT APP:*
AURORA (AA)
Anitta (Aa)
———then B and all the alphabet until Z———
aespa (aa)
———again, then b and all the alphabet until z———
Ängie (Äa)

*IDEAL APP:*
aespa 
Ängie
Anitta
AURORA
———then b (and all their variations) until z———

**Comment by Malopieds** [comment]
Hi, it should be implemented by now in last commit.
![image](https://github.com/Malopieds/InnerTune/assets/74783202/3774697e-d2b1-421c-bf1e-0ee3094ffdbc)
Here is the final result as you specified in the examples. Tell me if some things are missing and if not you can close the issue !

**Comment by darumanzane** [comment]
Hi! The new app is great, thanks for the changes and everything, specially the combination of the like and add buttons, and also the moving tittles when they're long.
Sadly, the problem with the letter variations is persistent. Here's a comparison between the alphabetical order in (New)InnerTune and Deezer:
*(New)InnerTune*
![Screenshot_2024-07-03-22-21-04-961_com malopieds innertune](https://github.com/Malopieds/InnerTune/assets/166534263/cbd6ae8e-dee6-4a19-b8b7-9ea974d01112)
*Deezer*
![IMG-20240703-WA0036](https://github.com/Malopieds/InnerTune/assets/166534263/069c2726-6f0b-407b-bd4d-385da4e714ef)
Hope you can keep working on the app, it would be great. I get that it can be frustrating seen how much work you've done and people still "complain", so I really want to emphasize that I think this app is great and I'm only being annoying with my petitions so I can like it even more. Thanks for the hard work. :)

**Comment by darumanzane** [comment]
Hi! The new app is great, but the letter variations problem persists. Here's a comparison between the alphabetical order in (New)InnerTune and Deezer:

*(New)InnerTune*
![(New)InnerTune](https://github.com/Malopieds/InnerTune/assets/166534263/bf8d9eba-059c-4a62-bd71-223d8cce3a00)

*Deezer*
![Deezer](https://github.com/Malopieds/InnerTune/assets/166534263/33691025-08d2-4ebc-9473-784540e11466)

As you can see, the new app still has the "AA, Aa, aa, Äa" system in place. In any case, I know it can be bothersome to work on something and have people be ungrateful and just ask for more, so I would like to emphasize that I like this app a lot and I think it's cool that you keep updating it. So yeah, thanks for keeping up the work!

**Comment by Malopieds** [comment]
Are you sure you are using the latest *debug* version? It's not in any stable release for now

**Comment by darumanzane** [comment]
Where can I access the latest debug version? Sorry, I thought the changes were implemented in the v0.5.7

**Comment by Malopieds** [comment]
No worries, go to the commits, see the latest, and click on the green checkmark, details, summary, at the bottom of the page you will find app.apk.

The link for this one is [this](https://github.com/Malopieds/InnerTune/actions/runs/9767786318/artifacts/1661371343)

**Comment by darumanzane** [comment]
Hello! I was able to access the debug version, thanks.
As for the letter variations, the problem was kinda solved. The thing is it only works in the "Songs" tab of the library:

![Screenshot_2024-07-04-14-32-59-411_com malopieds innertune debug](https://github.com/Malopieds/InnerTune/assets/166534263/0c8310bf-9269-4ed8-823a-afac6d6781dc)

It doesn't work in playlist:

![Screenshot_2024-07-04-14-43-18-789_com malopieds innertune debug](https://github.com/Malopieds/InnerTune/assets/166534263/fb2410c5-de7f-4854-81a3-e6448b1249c1)

Also, I would like to know if you're going to keep updating the new app —or how I call it: (New)InnerTune— in future builds from this point onward.

And, btw, don't know if I have to create a new task for this cause I think is kinda related to this one (?) but: can you change the way it shows the songs when you sort them by artist? Currently it just shows them depending on when you added them to the library, instead of grouping them by album:

![Screenshot_2024-07-04-14-58-12-785_com zionhuang music](https://github.com/Malopieds/InnerTune/assets/166534263/5c437083-d0c9-43d5-b60c-f2ae70ab6e92)

Have a good day, thank you!

**Comment by Malopieds** [comment]
> It doesn't work in playlist:

fixed in last push !

> don't know if I have to create a new task for this

I would appreciate you creating a new issue for this one yes ! It helps me clears things, if this is sorted feel free to close this issue.

**Comment by darumanzane** [comment]
Hey!
Just checked the last version and it works as intended!
Thanks for the update.
I have a question: if I use this debug version of the app, can it be updated and merged once we're in the v0.5.8?

**Comment by Malopieds** [comment]
>  I have a question: if I use this debug version of the app, can it be updated and merged once we're in the v0.5.8?

It's two separate app, but you can always backup your data, even though I don't recommend using debug since it's laggy

**Comment by darumanzane** [comment]
Alright, thank you!
